/* =============================================================
   SORA · CHEMICALS DATABASE · EDUCATIONAL/HISTORICAL
   The Shulgin lineage of psychoactive research chemistry.
   Documenting science, history, structural class, and current
   research status (MAPS, COMPASS, Johns Hopkins clinical trials).
   This is EDUCATIONAL content — NOT a use guide.
   Sourcing points to legitimate research channels only
   (clinical trials, peer-reviewed literature, books).
   Loaded as window.CHEMICALS.
   ============================================================= */
window.CHEMICALS = [

{ id:'mdma', category:'phenethylamine',
  name:{es:'MDMA · "Adam"',en:'MDMA · "Adam"'},
  origin:{es:'Anton Köllisch · Merck · 1912 · re-introducción Shulgin 1976',en:'Anton Köllisch · Merck · 1912 · Shulgin re-introduction 1976'},
  one:{es:'3,4-metilendioximetanfetamina · el "empathogen" prototípico.',en:'3,4-methylenedioxymethamphetamine · the prototypical "empathogen".'},
  story:{es:'Sintetizado por primera vez en 1912 por Anton Köllisch en los laboratorios Merck como intermediario en la síntesis de otro fármaco. Permaneció en archivos 60 años. En 1976 Alexander Shulgin lo re-sintetizó, auto-probó, y se lo presentó al psicoterapeuta Leo Zeff. Zeff lo distribuyó secretamente a ~4,000 terapeutas (lo llamaban "Adam") entre 1977-1985. La DEA lo programó Lista I en 1985 a pesar de protestas de psicoterapeutas. En 2024, MAPS Fase 3 mostró 67% remisión de PTSD severo con 3 sesiones de psicoterapia asistida — el primer fármaco psicodélico aprobado por FDA en evaluación final.',en:'First synthesized in 1912 by Anton Köllisch at Merck labs as an intermediate in another drug\'s synthesis. Stayed archived 60 years. In 1976 Alexander Shulgin re-synthesized it, self-tested it, and introduced it to psychotherapist Leo Zeff. Zeff secretly distributed it to ~4,000 therapists (called "Adam") between 1977-1985. DEA scheduled it Schedule I in 1985 despite psychotherapist protests. In 2024, MAPS Phase 3 showed 67% severe-PTSD remission with 3 assisted-psychotherapy sessions — first FDA-approved psychedelic drug in final evaluation.'},
  compounds:'C11H15NO2 · 3,4-metilendioxi-N-metilanfetamina · clase fenetilamina · liberador de serotonina · agonista 5-HT2A indirecto',
  effect:{es:'Libera serotonina + dopamina + norepinefrina simultáneamente. Suprime amígdala (centro del miedo) y eleva oxitocina + prolactina. El "empathogen" — produce cercanía emocional, autoaceptación, capacidad de procesar trauma. Duración 4-6h. Riesgos: hipertermia, hiponatremia, neurotoxicidad serotonérgica con uso repetido. La ventana terapéutica es estrecha; protocolo MAPS limita a 3 sesiones por vida con setting controlado.',en:'Releases serotonin + dopamine + norepinephrine simultaneously. Suppresses amygdala (fear center) and elevates oxytocin + prolactin. The "empathogen" — produces emotional closeness, self-acceptance, ability to process trauma. Duration 4-6h. Risks: hyperthermia, hyponatremia, serotonergic neurotoxicity with repeated use. Therapeutic window is narrow; MAPS protocol limits to 3 sessions per lifetime in controlled setting.'},
  ingredients:{es:['Acceso a estudios MAPS/Lykos · investigación activa','Libros: PIHKAL (Shulgin), Acid Test (Slater)','Sin sourcing personal — Lista I federal'],en:['MAPS/Lykos studies access · active research','Books: PIHKAL (Shulgin), Acid Test (Slater)','No personal sourcing — federal Schedule I']},
  recipe:{es:'No aplica recetas personales. El protocolo clínico MAPS (ahora en revisión FDA bajo Lykos Therapeutics): 3 sesiones espaciadas 3-4 semanas. Dosis 80-120mg + booster 40-60mg a las 2h. Setting controlado: 2 terapeutas presentes, música curada, antifaz, 8 horas de sesión + 12 sesiones de preparación/integración no-medicada. La FDA evaluó la solicitud Lykos en 2024 — decisión pendiente. Múltiples clínicas activas en Australia (legal 2023), Suiza y Países Bajos (uso compasivo).',en:'Personal recipes don\'t apply. MAPS clinical protocol (now under FDA review via Lykos Therapeutics): 3 sessions spaced 3-4 weeks. Dose 80-120mg + 40-60mg booster at 2h. Controlled setting: 2 therapists present, curated music, eyeshades, 8-hour session + 12 unmedicated prep/integration sessions. FDA reviewed Lykos application in 2024 — decision pending. Multiple active clinics in Australia (legal 2023), Switzerland and Netherlands (compassionate use).'},
  sourcing:{
    local:[],
    intl:[
      {name:'MAPS · Multidisciplinary Association for Psychedelic Studies',url:'https://maps.org',note:{es:'★ la fuente · papers + clinical trials + book recommendations',en:'★ the source · papers + clinical trials + book recommendations'}},
      {name:'Lykos Therapeutics (ex MAPS-PBC)',url:'https://lykospsychedelics.com',note:{es:'la compañía buscando aprobación FDA',en:'company pursuing FDA approval'}},
      {name:'PIHKAL · Alexander Shulgin (libro)',url:'https://www.amazon.com/PiHKAL-Chemical-Love-Story-Phenethylamines/dp/0963009605',note:{es:'★ catálogo completo de fenetilaminas · vía Aeropost',en:'★ complete phenethylamine catalog · via Aeropost'}},
      {name:'Erowid · Vault',url:'https://erowid.org/chemicals/mdma',note:{es:'archivo de research y reports históricos',en:'research and historical reports archive'}}
    ]
  }
},

{ id:'2cb', category:'phenethylamine',
  name:{es:'2C-B · "Nexus"',en:'2C-B · "Nexus"'},
  origin:{es:'Alexander Shulgin · USA · 1974',en:'Alexander Shulgin · USA · 1974'},
  one:{es:'La fenetilamina con sensorial intenso · cognición intacta · 4 horas.',en:'The phenethylamine with intense visuals · intact cognition · 4 hours.'},
  story:{es:'Shulgin sintetizó 2C-B (4-bromo-2,5-dimetoxifenetilamina) en 1974 buscando un compuesto entre MDMA y mescalina. Sus notas en PIHKAL describen la primera autoexperiencia: "Visual, en lugar de mental." Resultó vendido legalmente como afrodisíaco en farmacias alemanas hasta 1995 bajo el nombre "Nexus". DEA Lista I en USA desde 1995. Curiosamente, en el grupo de Shulgin se consideraba más fácil de manejar que LSD — duración más corta (4h), cognición no fragmentada, visuales geométricos intensos. Hoy es uno de los compuestos más investigados en el "Psychedelic Renaissance" — Imperial College London está estudiando su uso terapéutico.',en:'Shulgin synthesized 2C-B (4-bromo-2,5-dimethoxyphenethylamine) in 1974 seeking a compound between MDMA and mescaline. His PIHKAL notes describe the first self-experience: "Visual, rather than mental." It was sold legally as an aphrodisiac in German pharmacies until 1995 under the name "Nexus". DEA Schedule I in US since 1995. Curiously, in Shulgin\'s group it was considered easier to handle than LSD — shorter duration (4h), non-fragmented cognition, intense geometric visuals. Today one of the most-researched compounds in the "Psychedelic Renaissance" — Imperial College London is studying its therapeutic use.'},
  compounds:'C10H14BrNO2 · 4-bromo-2,5-dimetoxifenetilamina · clase 2C (phenethylamines bromados Shulgin)',
  effect:{es:'Agonista parcial 5-HT2A y 5-HT2C. Visuales geométricos vivos sin pérdida de control mental. Sensaciones somáticas amplificadas. Duración 3-4 horas (más corto que LSD/psilocibina). En dosis bajas (5-10mg): empathogen suave. En dosis altas (20-30mg): psicodélico clásico. Ventana terapéutica más estrecha que MDMA — efectos físicos prominentes (rubor, taquicardia).',en:'Partial 5-HT2A and 5-HT2C agonist. Vivid geometric visuals without loss of mental control. Amplified somatic sensations. Duration 3-4 hours (shorter than LSD/psilocybin). Low dose (5-10mg): mild empathogen. High dose (20-30mg): classic psychedelic. Narrower therapeutic window than MDMA — prominent physical effects (flushing, tachycardia).'},
  ingredients:{es:['Acceso a literatura: PIHKAL Entry #20','Studies: Imperial College Psychedelic Research','Sin sourcing personal'],en:['Access to literature: PIHKAL Entry #20','Studies: Imperial College Psychedelic Research','No personal sourcing']},
  recipe:{es:'No aplica receta personal. Para investigación: PIHKAL Entry #20 describe protocolo Shulgin original — comienzo en dosis 4mg ascendiendo. Imperial College London (UK) y Universidad de Maastricht (NL) tienen estudios de ketamina/psilocibina/2C-B activos abiertos a voluntarios. En Suiza permiso terapéutico compasivo desde 2014. NO autoadministración recreativa — la línea entre dosis "manejable" y "abrumadora" es estrecha.',en:'Personal recipe doesn\'t apply. For research: PIHKAL Entry #20 describes Shulgin\'s original protocol — start at 4mg ascending. Imperial College London (UK) and Maastricht University (NL) have active ketamine/psilocybin/2C-B studies open to volunteers. In Switzerland compassionate-use permit since 2014. NO recreational self-administration — line between "manageable" and "overwhelming" dose is narrow.'},
  sourcing:{
    local:[],
    intl:[
      {name:'PIHKAL · Alexander Shulgin',url:'https://www.amazon.com/PiHKAL-Chemical-Love-Story-Phenethylamines/dp/0963009605',note:{es:'★ Entry #20 catalogación completa · libro',en:'★ Entry #20 complete cataloging · book'}},
      {name:'Imperial College Psychedelic Research',url:'https://www.imperial.ac.uk/psychedelic-research-centre',note:{es:'★ estudios activos · centro líder UK',en:'★ active studies · UK leader center'}},
      {name:'Erowid · 2C-B Vault',url:'https://erowid.org/chemicals/2cb',note:{es:'archivo histórico + research',en:'historical + research archive'}},
      {name:'PsychonautWiki',url:'https://psychonautwiki.org/wiki/2C-B',note:{es:'documentación community',en:'community documentation'}}
    ]
  }
},

{ id:'mescaline', category:'phenethylamine',
  name:{es:'Mescalina · El Cactus Sagrado',en:'Mescaline · The Sacred Cactus'},
  origin:{es:'Wichita-Comanche · 8000 a.C. · aislada 1897 Arthur Heffter',en:'Wichita-Comanche · 8000 BCE · isolated 1897 Arthur Heffter'},
  one:{es:'La fenetilamina madre · peyote · 10,000 años de uso ceremonial.',en:'The mother phenethylamine · peyote · 10,000 years of ceremonial use.'},
  story:{es:'Mescalina es el psicoactivo activo de los cactus Lophophora williamsii (peyote, México) y Echinopsis pachanoi (San Pedro, Andes). Uso ceremonial documentado arqueológicamente hasta 8000 a.C. en Texas y norte de México. La Native American Church (~250,000 miembros) la usa legalmente en EUA bajo libertad religiosa desde 1978. El químico alemán Arthur Heffter la aisló y autoadministró en 1897 — el primer psicodélico identificado científicamente. Aldous Huxley la usó para escribir <em>Las Puertas de la Percepción</em> (1954). Estructura clásica fenetilamina — la base de todo el catálogo Shulgin. Duración larga: 8-12 horas.',en:'Mescaline is the psychoactive of Lophophora williamsii (peyote, Mexico) and Echinopsis pachanoi (San Pedro, Andes) cacti. Ceremonial use archaeologically documented to 8000 BCE in Texas and northern Mexico. Native American Church (~250,000 members) uses it legally in US under religious freedom since 1978. German chemist Arthur Heffter isolated and self-administered it in 1897 — the first scientifically identified psychedelic. Aldous Huxley used it to write <em>The Doors of Perception</em> (1954). Classic phenethylamine structure — the basis of the entire Shulgin catalog. Long duration: 8-12 hours.'},
  compounds:'C11H17NO3 · 3,4,5-trimetoxifenetilamina · fenetilamina prototípica · activa en cactus Lophophora y Echinopsis · ~250-500mg dosis ceremonial',
  effect:{es:'Agonista 5-HT2A. Duración larga (8-12h) — la más larga de los psicodélicos clásicos. Visuales suaves color-saturados, sensación de "tiempo profundo" y reverencia. Menos visual que LSD, más somático y emocional. Cognición permanece coherente — útil para introspección extendida. El "psicodélico de los abuelos" — fue usado por civilizaciones antes de existir LSD o psilocybin sintéticas.',en:'5-HT2A agonist. Long duration (8-12h) — longest of classical psychedelics. Soft color-saturated visuals, sensation of "deep time" and reverence. Less visual than LSD, more somatic and emotional. Cognition stays coherent — useful for extended introspection. The "psychedelic of grandparents" — used by civilizations before synthetic LSD or psilocybin existed.'},
  ingredients:{es:['Acceso a Native American Church (uso religioso protegido EUA)','Cactus San Pedro/Huachuma · legal en Perú/Ecuador/Bolivia','Libros: Doors of Perception (Huxley), San Pedro Cactus (Cassiel)'],en:['Native American Church access (US protected religious use)','San Pedro/Huachuma cactus · legal in Peru/Ecuador/Bolivia','Books: Doors of Perception (Huxley), San Pedro Cactus (Cassiel)']},
  recipe:{es:'En contexto ceremonial andino o NAC: el cactus se prepara como "wachuma" — el corazón verde del San Pedro se hierve por 8-12 horas hasta obtener un líquido amargo concentrado. Dosis ceremonial: 100-150g de cactus fresco. La ceremonia comienza al amanecer con curandero. Duración: 8-12 horas. En Perú y Ecuador es legal y existen retiros documentados. En México la NAC permite peyote en ceremonia. Fuera de estos contextos es Lista I (USA) / similar (México).',en:'In Andean ceremonial or NAC context: the cactus is prepared as "wachuma" — the green heart of San Pedro is boiled 8-12 hours yielding a concentrated bitter liquid. Ceremonial dose: 100-150g fresh cactus. Ceremony begins at dawn with curandero. Duration: 8-12 hours. In Peru and Ecuador it\'s legal and documented retreats exist. In Mexico the NAC permits peyote in ceremony. Outside these contexts it\'s Schedule I (US) / similar (Mexico).'},
  sourcing:{
    local:[],
    intl:[
      {name:'Native American Church',url:'https://nacofnorthamerica.org',note:{es:'★ contexto legal único en USA · ceremonia ancestral',en:'★ unique legal context in USA · ancestral ceremony'}},
      {name:'San Pedro · Sacred Valley Tribe (Perú)',url:'https://www.sacredvalleytribe.com',note:{es:'retiros legales Perú · curanderos locales',en:'legal Peru retreats · local curanderos'}},
      {name:'Doors of Perception · Aldous Huxley',url:'https://www.amazon.com/Doors-Perception-Heaven-Hell/dp/0061729078',note:{es:'★ relato de Huxley con mescalina · libro fundacional',en:'★ Huxley\'s mescaline account · foundational book'}},
      {name:'Erowid Mescaline Vault',url:'https://erowid.org/chemicals/mescaline',note:{es:'archivo científico y histórico',en:'scientific and historical archive'}}
    ]
  }
},

{ id:'lsd', category:'tryptamine',
  name:{es:'LSD-25 · Ácido Lisérgico',en:'LSD-25 · Lysergic Acid'},
  origin:{es:'Albert Hofmann · Sandoz · Suiza · 16 abril 1943',en:'Albert Hofmann · Sandoz · Switzerland · April 16, 1943'},
  one:{es:'El psicodélico que definió la era · 12 horas · 100 microgramos cambian todo.',en:'The psychedelic that defined the era · 12 hours · 100 micrograms change everything.'},
  story:{es:'Albert Hofmann sintetizó LSD-25 (dietilamida del ácido lisérgico) en 1938 como compuesto #25 en una serie buscando estimulante respiratorio del cornezuelo de centeno. Inactivo en animales, archivado. En abril 16, 1943, una intuición lo hizo re-sintetizar — y absorbió una pequeña cantidad por la piel mientras manipulaba el polvo. Tres días después, el famoso "Bicycle Day" — autoadministró 250mcg deliberadamente y experimentó el primer viaje de LSD intencional. Sandoz lo distribuyó como Delysid® a psicoterapeutas mundialmente 1947-1966 — había 1,000+ papers académicos antes de prohibirse. Re-sintetizado en proyectos modernos: COMPASS Pathways, MindMed, Filament Health.',en:'Albert Hofmann synthesized LSD-25 (lysergic acid diethylamide) in 1938 as compound #25 in a series seeking ergot-derived respiratory stimulant. Inactive in animals, archived. On April 16, 1943, an intuition made him re-synthesize — and he absorbed a small amount through skin while handling the powder. Three days later, the famous "Bicycle Day" — deliberately self-administered 250mcg and experienced the first intentional LSD trip. Sandoz distributed it as Delysid® to psychotherapists worldwide 1947-1966 — there were 1,000+ academic papers before prohibition. Re-synthesized in modern projects: COMPASS Pathways, MindMed, Filament Health.'},
  compounds:'C20H25N3O · dietilamida del ácido lisérgico · derivado de Claviceps purpurea (cornezuelo) · ergoloid · agonista 5-HT2A fuerte',
  effect:{es:'Agonista parcial 5-HT2A muy potente — activo en 50-200 microgramos. Duración 8-12 horas. Visuales geométricos profundos, dilución del ego (default mode network), conexiones cognitivas no-lineares, "noético" (insights percibidos como verdades). Hipótesis Hofmann: el Soma védico y el Kykeon de Eleusis fueron ergot — la misma molécula que LSD-25. Estudios COMPASS Pathways en deterioro cognitivo y depresión resistente.',en:'Very potent partial 5-HT2A agonist — active at 50-200 micrograms. Duration 8-12 hours. Deep geometric visuals, ego dissolution (default mode network), non-linear cognitive connections, "noetic" (insights felt as truths). Hofmann hypothesis: Vedic Soma and Eleusinian Kykeon were ergot — same molecule as LSD-25. COMPASS Pathways studies in cognitive decline and treatment-resistant depression.'},
  ingredients:{es:['Libros: LSD My Problem Child (Hofmann)','MAPS · COMPASS · MindMed clinical trials','Erowid + PsychonautWiki vaults'],en:['Books: LSD My Problem Child (Hofmann)','MAPS · COMPASS · MindMed clinical trials','Erowid + PsychonautWiki vaults']},
  recipe:{es:'Personal sin aplicar. En contexto clínico moderno: MindMed Phase 2 LSD-25 para ansiedad. COMPASS Pathways psilocibina. Acceso vía estudios clínicos solamente — Lista I federal USA y la mayoría de jurisdicciones. Suiza permite uso compasivo (~30 pacientes/año vía Dr. Peter Gasser). Microdosing recreativo NO recomendado fuera de protocolos investigación — interactions con SSRIs, MAOIs son peligrosas.',en:'Personal doesn\'t apply. Modern clinical context: MindMed Phase 2 LSD-25 for anxiety. COMPASS Pathways psilocybin. Access via clinical trials only — federal Schedule I US and most jurisdictions. Switzerland permits compassionate use (~30 patients/year via Dr. Peter Gasser). Recreational microdosing NOT recommended outside research protocols — SSRI, MAOI interactions are dangerous.'},
  sourcing:{
    local:[],
    intl:[
      {name:'LSD: My Problem Child · Albert Hofmann',url:'https://www.amazon.com/LSD-My-Problem-Child-Albert/dp/0979862221',note:{es:'★ memorias del descubridor',en:'★ discoverer\'s memoir'}},
      {name:'MindMed · clinical trials',url:'https://mindmed.co',note:{es:'★ Phase 2 LSD para ansiedad · acceso a estudios',en:'★ Phase 2 LSD for anxiety · study access'}},
      {name:'COMPASS Pathways',url:'https://compasspathways.com',note:{es:'psilocibina + LSD trials',en:'psilocybin + LSD trials'}},
      {name:'Erowid LSD Vault',url:'https://erowid.org/chemicals/lsd',note:{es:'archivo de 70 años de papers',en:'70 years of papers archive'}}
    ]
  }
},

{ id:'psilocybin', category:'tryptamine',
  name:{es:'Psilocibina · Hongos Sagrados',en:'Psilocybin · Sacred Mushrooms'},
  origin:{es:'Mazatecos Oaxaca · uso ancestral · aislada 1958 Hofmann',en:'Mazatec Oaxaca · ancestral use · isolated 1958 Hofmann'},
  one:{es:'La triptamina natural de los hongos · 4-6 horas · ahora en Fase 3 contra depresión.',en:'The natural mushroom tryptamine · 4-6 hours · now Phase 3 for depression.'},
  story:{es:'Los hongos Psilocybe han sido usados ceremonialmente en Mesoamérica por al menos 3,000 años — los Mazatecos los llaman "ndi xi tjo" (los pequeños que brotan). La sabia mazateca María Sabina los introdujo al mundo occidental cuando R. Gordon Wasson participó en una velada ceremonial en 1955. Albert Hofmann aisló psilocibina + psilocina de muestras enviadas por Wasson en 1958. Hopkins, NYU y COMPASS Pathways han revivido los estudios desde 2006 — la psilocibina muestra 67-75% remisión en depresión resistente a tratamiento (Compass COMP360 Phase 3). FDA designación de "Breakthrough Therapy" 2018 y 2019.',en:'Psilocybe mushrooms have been used ceremonially in Mesoamerica for at least 3,000 years — Mazatecs call them "ndi xi tjo" (the little ones that sprout). Mazatec sabia María Sabina introduced them to the Western world when R. Gordon Wasson participated in a ceremonial velada in 1955. Albert Hofmann isolated psilocybin + psilocin from samples Wasson sent in 1958. Hopkins, NYU and COMPASS Pathways have revived studies since 2006 — psilocybin shows 67-75% remission in treatment-resistant depression (Compass COMP360 Phase 3). FDA "Breakthrough Therapy" designation 2018 and 2019.'},
  compounds:'Psilocibina (C12H17N2O4P · pro-drug) → Psilocina (C12H16N2O · activa) · clase triptamina · 4-fosforiloxi-N,N-dimetiltriptamina · agonista 5-HT2A',
  effect:{es:'Psilocibina se desfosforila en psilocina (activa) en hígado. Agonista 5-HT2A. Duración 4-6 horas. Visuales suaves a moderados, conexiones emocionales con memoria, sensación de "comunión" con personas o naturaleza. La ventana terapéutica es más amplia que MDMA. En clínica: Compass COMP360 (sintética farmacéutica) para depresión-resistente. Mismas dosis cocidas en té de hongos suelen ser más leves por absorción gradual + alkaloides adicionales.',en:'Psilocybin dephosphorylates to psilocin (active) in liver. 5-HT2A agonist. Duration 4-6 hours. Mild to moderate visuals, emotional connections with memory, sensation of "communion" with people or nature. Therapeutic window wider than MDMA. Clinical: Compass COMP360 (pharmaceutical synthetic) for treatment-resistant depression. Same dose in mushroom tea tends to be milder due to gradual absorption + additional alkaloids.'},
  ingredients:{es:['Acceso clínico: COMPASS Pathways, Johns Hopkins, Usona Institute','Hongos legalmente despenalizados: Oregon (Measure 109), Colorado (Prop 122)','Libros: Mushrooms Russia and History (Wasson), How to Change Your Mind (Pollan)'],en:['Clinical access: COMPASS Pathways, Johns Hopkins, Usona Institute','Decriminalized fungi: Oregon (Measure 109), Colorado (Prop 122)','Books: Mushrooms Russia and History (Wasson), How to Change Your Mind (Pollan)']},
  recipe:{es:'En contexto Oregon legal: en clínica licenciada con facilitador certificado — dosis de 25mg psilocibina sintética + 8 horas sesión + integración. En México (legal en algunos retiros mazatecos): velada nocturna con curandera, 4-8g hongos secos. En Holanda: trufas de psilocibina legales (Psilocybe galindoii) — ~10g en sesión. En clínica USA: Johns Hopkins reclutamiento para depresión + adicciones · UCSF para PTSD. NO autoadministración fuera de contexto legal.',en:'In legal Oregon context: licensed clinic with certified facilitator — 25mg synthetic psilocybin + 8-hour session + integration. In Mexico (legal in some Mazatec retreats): nighttime velada with curandera, 4-8g dried mushrooms. In Holland: legal psilocybin truffles (Psilocybe galindoii) — ~10g per session. US clinic: Johns Hopkins recruiting for depression + addictions · UCSF for PTSD. NO self-administration outside legal context.'},
  sourcing:{
    local:[],
    intl:[
      {name:'COMPASS Pathways',url:'https://compasspathways.com',note:{es:'★ Phase 3 sintética COMP360 · trials abiertos',en:'★ Phase 3 synthetic COMP360 · open trials'}},
      {name:'Johns Hopkins Center for Psychedelic Research',url:'https://hopkinspsychedelic.org',note:{es:'★ centro líder · estudios + entrenamiento facilitadores',en:'★ leader center · studies + facilitator training'}},
      {name:'Oregon Psilocybin Services',url:'https://www.oregon.gov/oha/PH/PreventionWellness/Pages/Oregon-Psilocybin-Services.aspx',note:{es:'★ marco legal Oregon · clínicas certificadas',en:'★ Oregon legal framework · certified clinics'}},
      {name:'How to Change Your Mind · Michael Pollan',url:'https://www.amazon.com/How-Change-Your-Mind-Consciousness/dp/0735224153',note:{es:'★ visión general moderna · libro + Netflix doc',en:'★ modern overview · book + Netflix doc'}}
    ]
  }
},

{ id:'dmt', category:'tryptamine',
  name:{es:'DMT · La Molécula del Espíritu',en:'DMT · The Spirit Molecule'},
  origin:{es:'Amazonía · ayahuasca milenaria · aislada Manske 1931',en:'Amazon · millenia of ayahuasca · isolated Manske 1931'},
  one:{es:'La molécula más intensa de la biología · presente en cada planta y animal.',en:'Biology\'s most intense molecule · present in every plant and animal.'},
  story:{es:'N,N-dimetiltriptamina existe naturalmente en cientos de plantas (chacruna, mimosa) y en mamíferos — incluyendo humanos. Fumada o vaporizada produce una de las experiencias psicodélicas más intensas conocidas — 5-15 minutos de duración, "breakthrough" a una realidad aparente. Las tribus amazónicas combinan DMT (de chacruna) con MAOI (de Banisteriopsis caapi) en la "ayahuasca" — la combinación permite que DMT funcione oralmente. Dr. Rick Strassman (UNM) fue el primer científico en re-comenzar estudios humanos legales en 1990, documentados en su libro <em>DMT: The Spirit Molecule</em>. Hipótesis especulativa: la glándula pineal sintetiza DMT durante muerte y sueños profundos.',en:'N,N-dimethyltryptamine exists naturally in hundreds of plants (chacruna, mimosa) and in mammals — including humans. Smoked or vaporized produces one of the most intense psychedelic experiences known — 5-15 min duration, "breakthrough" to an apparent reality. Amazon tribes combine DMT (from chacruna) with MAOI (from Banisteriopsis caapi) in "ayahuasca" — combination allows DMT to work orally. Dr. Rick Strassman (UNM) was first scientist to restart legal human studies in 1990, documented in his book <em>DMT: The Spirit Molecule</em>. Speculative hypothesis: pineal gland synthesizes DMT during death and deep sleep.'},
  compounds:'C12H16N2 · N,N-dimetiltriptamina · presente en biología en pequeñas cantidades · activa por fumado/vapor (no oral sin MAOI)',
  effect:{es:'Agonista 5-HT2A muy intenso. Por vaporización: 5-15 minutos absoluto. Visuales geométricos hipercomplejos, sensación de viajar a un "espacio" alternativo donde aparecen "entidades" arquetípicas (consistencia cross-cultural notable). Cognición permanece. Vida media muy corta. En forma ayahuasca: dura 4-6 horas, más somático, frecuentemente catártico (vómito ceremonial "purga"). La hipótesis Strassman: durante experiencia near-death humanos secretan DMT endógeno.',en:'Very intense 5-HT2A agonist. Vaporized: 5-15 minutes absolute. Hypercomplex geometric visuals, sensation of traveling to alternative "space" where archetypal "entities" appear (notable cross-cultural consistency). Cognition stays. Very short half-life. In ayahuasca form: lasts 4-6 hours, more somatic, often cathartic (ceremonial "purge" vomiting). Strassman hypothesis: humans secrete endogenous DMT during near-death experience.'},
  ingredients:{es:['Acceso a ceremonia ayahuasca legal: UDV (Brasil), Santo Daime (legal en NL, BR, US religious exempt)','Libro: DMT: The Spirit Molecule (Strassman)','Imperial College + Johns Hopkins active studies'],en:['Ayahuasca ceremony access: UDV (Brazil), Santo Daime (legal in NL, BR, US religious exempt)','Book: DMT: The Spirit Molecule (Strassman)','Imperial College + Johns Hopkins active studies']},
  recipe:{es:'En contexto ayahuasca tradicional: chamán shipibo/yawanawá prepara cocción de B. caapi + chacruna (P. viridis) durante días. Sesión nocturna en maloca con canciones (ícaros). La purga es parte del rito. Dosis 50-150ml. Duración 4-6 horas. Retiros legales en Brasil (Santo Daime + UDV), Perú (sin restricción), Costa Rica (legal). Ibogaine + ayahuasca como Tx para adicción opioides en clínicas mexicanas. NUNCA combinar con SSRI/MAOI farmacéutico — síndrome serotoninérgico letal.',en:'Traditional ayahuasca context: Shipibo/Yawanawá shaman prepares B. caapi + chacruna (P. viridis) decoction over days. Nighttime session in maloca with songs (ícaros). Purge is part of rite. Dose 50-150ml. Duration 4-6 hours. Legal retreats in Brazil (Santo Daime + UDV), Peru (no restriction), Costa Rica (legal). Ibogaine + ayahuasca as opioid addiction Tx in Mexican clinics. NEVER combine with pharmaceutical SSRI/MAOI — lethal serotonin syndrome.'},
  sourcing:{
    local:[],
    intl:[
      {name:'DMT: The Spirit Molecule · Rick Strassman',url:'https://www.amazon.com/DMT-Spirit-Molecule-Doctors-Revolutionary/dp/0892819278',note:{es:'★ el libro fundacional · investigación UNM',en:'★ foundational book · UNM research'}},
      {name:'Soltara Healing Center (Costa Rica)',url:'https://soltara.co',note:{es:'★ ayahuasca legal Shipibo · CR',en:'★ legal Shipibo ayahuasca · CR'}},
      {name:'Rythmia (Costa Rica)',url:'https://rythmia.com',note:{es:'retiros medicalmente supervisados',en:'medically supervised retreats'}},
      {name:'União do Vegetal (UDV)',url:'https://udv.org.br',note:{es:'religión brasileña con sacramento legal · capítulos internacionales',en:'Brazilian religion with legal sacrament · international chapters'}}
    ]
  }
},

/* ============ EXPANSION · 10 NEW CHEMICALS (2026 research-verified) ============ */

{ id:'5meo-dmt', category:'tryptamine',
  name:{es:'5-MeO-DMT · Sapo del Sonora',en:'5-MeO-DMT · Sonoran Toad'},
  origin:{es:'Toshio Hoshino · síntesis 1936 · Bufo alvarius 1965',en:'Toshio Hoshino · synthesis 1936 · Bufo alvarius 1965'},
  one:{es:'La triptamina más intensa · 15 minutos · "Dios molecular" en una inhalación.',en:'The most intense tryptamine · 15 minutes · "Molecular God" in one inhalation.'},
  story:{es:'Sintetizada por el químico japonés Toshio Hoshino en 1936; aislada de la planta <em>Dictyoloma incanescens</em> en 1959. Su presencia en la secreción de la glándula parótida del sapo del desierto de Sonora (<em>Bufo/Incilius alvarius</em>) fue identificada por Erspamer en 1965-67. Pese a afirmaciones de uso indígena ancestral, el registro confiable comienza con el panfleto underground de 1984 "Albert Most" (Ken Nelson). Reckweg et al. (2022, <em>J. Neurochem</em>) revisaron su farmacología clínica; estudios observacionales (Uthaug 2019, Davis 2018/2019) reportan efectos rápidos en depresión y ansiedad. <strong>Beckley Psytech (Atai-afiliada)</strong> avanzó BPL-003 (mebufotenin/5-MeO-DMT intranasal) a Phase 2 para depresión resistente.',en:'Synthesized by Japanese chemist Toshio Hoshino in 1936; isolated from <em>Dictyoloma incanescens</em> in 1959. Its presence in Sonoran desert toad (<em>Bufo/Incilius alvarius</em>) parotoid gland secretion was identified by Erspamer in 1965-67. Despite frequent ancient-use claims, credible record begins with 1984 underground pamphlet by Ken Nelson ("Albert Most"). Reckweg et al. (2022, <em>J. Neurochem</em>) reviewed clinical pharmacology; observational studies (Uthaug 2019, Davis 2018/2019) report rapid effects on depression and anxiety. <strong>Beckley Psytech (Atai-affiliated)</strong> advanced BPL-003 (intranasal mebufotenin/5-MeO-DMT) to Phase 2 for treatment-resistant depression.'},
  compounds:'C13H18N2O · 5-metoxi-N,N-dimetiltriptamina · agonista 5-HT1A + 5-HT2A · selectividad 1A vs psicodélicos clásicos',
  effect:{es:'Agonista 5-HT1A y 5-HT2A — selectividad 1A inusual entre psicodélicos clásicos. Por vaporización: 5-15 minutos absoluto, "breakthrough" reportado como disolución completa del ego ("non-dual"). Sin visuales típicos — más bien "blanco luminoso". Efectos antidepresivos rápidos comparables a ketamina. NUNCA combinar con SSRI/MAOI farmacéutico — síndrome serotoninérgico letal.',en:'5-HT1A and 5-HT2A agonist — 1A selectivity unusual among classical psychedelics. Vaporized: 5-15 minutes absolute, "breakthrough" reported as complete ego dissolution ("non-dual"). No typical visuals — rather "luminous white". Rapid antidepressant effects comparable to ketamine. NEVER combine with pharmaceutical SSRI/MAOI — lethal serotonin syndrome.'},
  ingredients:{es:['Acceso retiros legales México: Tandava, F.I.V.E. (Tepoztlán)','Beckley Psytech BPL-003 clinical trials (Phase 2 TRD)','PIHKAL Entry #38 documentación Shulgin','Conservación: usar 5-MeO-DMT sintético, NO toad-derived'],en:['Legal Mexico retreat access: Tandava, F.I.V.E. (Tepoztlán)','Beckley Psytech BPL-003 clinical trials (Phase 2 TRD)','PIHKAL Entry #38 Shulgin documentation','Conservation: use synthetic 5-MeO-DMT, NOT toad-derived']},
  recipe:{es:'No aplica para personal. Acceso legal en contexto retreat: México no programa 5-MeO-DMT bajo Ley General de Salud — <strong>Tandava Retreats</strong> (Tepoztlán) y <strong>F.I.V.E.</strong> (5-MeO-DMT Information &amp; Vital Education, Joël Brierre + Victoria Wueschner) usan material sintético (no toad-derived por conservación). Sesiones individuales 4-6 horas + integración 1-2 semanas. Para clinical Phase 2 access: Beckley Psytech BPL-003 trials.',en:'Personal doesn\'t apply. Legal access via retreat: Mexico doesn\'t schedule 5-MeO-DMT under General Health Law — <strong>Tandava Retreats</strong> (Tepoztlán) and <strong>F.I.V.E.</strong> (5-MeO-DMT Information &amp; Vital Education, Joël Brierre + Victoria Wueschner) use synthetic material (not toad-derived for conservation). Individual sessions 4-6 hours + integration 1-2 weeks. For clinical Phase 2 access: Beckley Psytech BPL-003 trials.'},
  sourcing:{
    local:[],
    intl:[
      {name:'Tandava Retreats',url:'https://www.tandavaretreats.com',note:{es:'★ Tepoztlán México · 1,000+ ceremonias · sintético',en:'★ Tepoztlán Mexico · 1,000+ ceremonies · synthetic'}},
      {name:'F.I.V.E. (5-MeO Education)',url:'https://five-meo.education',note:{es:'★ training + education arm Tandava founders',en:'★ training + education arm Tandava founders'}},
      {name:'Beckley Psytech / Atai BPL-003',url:'https://beckleypsytech.com',note:{es:'★ Phase 2 TRD intranasal · trial access',en:'★ Phase 2 TRD intranasal · trial access'}},
      {name:'Reckweg et al 2022 (PMC9314805)',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC9314805/',note:{es:'review farmacología clínica',en:'clinical pharmacology review'}}
    ]
  }
},

{ id:'ibogaine', category:'tryptamine',
  name:{es:'Ibogaine · Bwiti · Detox Opioide',en:'Ibogaine · Bwiti · Opioid Detox'},
  origin:{es:'Tabernanthe iboga · Gabón · Bwiti milenario · aislado 1901',en:'Tabernanthe iboga · Gabon · ancient Bwiti · isolated 1901'},
  one:{es:'El alcaloide que detiene la abstinencia opioide en una dosis · ahora $50M en research Texas.',en:'The alkaloid that stops opioid withdrawal in one dose · now $50M Texas research.'},
  story:{es:'Ibogaine es el alcaloide indol principal de <em>Tabernanthe iboga</em>, arbusto Apocynaceae nativo de Gabón, Camerún, República del Congo. Iniciados Bwiti de Gabón lo usan como sacramento ceremonial hace siglos. Aislamiento occidental 1901; vendido en Francia como Lambarène (8mg tablets) hasta 1970. Propiedades anti-adictivas notadas clínicamente en NIMH Addiction Research Center 1955, famosamente re-descubierto por Howard Lotsof en 1962 tras auto-experimentación que interrumpió withdrawal opioide. <strong>2025: Texas asignó $50M para FDA-directed ibogaine clinical research para opioid use disorder</strong>; <strong>2026: US executive order acelerando federal review</strong>. Stanford/Nolan Williams (2024): ibogaine + magnesio para veteranos con TBI.',en:'Ibogaine is the principal indole alkaloid of <em>Tabernanthe iboga</em>, an Apocynaceae shrub native to Gabon, Cameroon, Republic of Congo. Gabon\'s Bwiti initiates have used iboga root bark as ceremonial sacrament for centuries. Western isolation 1901; sold in France as Lambarène (8mg tablets) until 1970. Anti-addictive properties noted clinically at NIMH Addiction Research Center 1955, famously rediscovered by Howard Lotsof in 1962 after self-experimentation interrupted opioid withdrawal. <strong>2025: Texas allocated $50M for FDA-directed ibogaine clinical research for opioid use disorder</strong>; <strong>2026: US executive order accelerating federal review</strong>. Stanford/Nolan Williams (2024): ibogaine + magnesium for veterans with TBI.'},
  compounds:'C19H26N2O · 12-metoxiibogamina · clase ibogamina · promiscuo: μ/κ-opioid, σ, NMDA, 5-HT, α3β4 nAChR · metabolito noribogaina SERT-inhibitor + κ-agonist',
  effect:{es:'Mecanismo principal anti-adictivo: antagonista α3β4 nAChR (hipótesis líder). Interrumpe withdrawal opioide en una dosis (8-12mg/kg). Estado "soñador" 4-8 horas de revisión visual autobiográfica intensa + 24-48h de "post-acute" introspection. CARDIOTOXICIDAD significativa — prolonga QT, requiere ECG monitoring continuo. NO en personas con problemas cardíacos. Stanford 2024 mostró ibogaine + magnesio (que mitiga QT) seguro para veteranos TBI con mejoras cognitivas significativas.',en:'Primary anti-addictive mechanism: α3β4 nAChR antagonist (leading hypothesis). Interrupts opioid withdrawal in one dose (8-12mg/kg). "Dreamy" state 4-8 hours of intense autobiographic visual review + 24-48h "post-acute" introspection. Significant CARDIOTOXICITY — prolongs QT, requires continuous ECG monitoring. NOT for people with cardiac issues. Stanford 2024 showed ibogaine + magnesium (mitigating QT) safe for TBI veterans with significant cognitive improvements.'},
  ingredients:{es:['Acceso clínico legal: México (Tepoztlán, Playa del Carmen, Cancún)','Costa Rica: Iboga Wellness Center · root bark psicoespiritual','Stanford research access (Nolan Williams TBI study)','Texas FDA-directed trials (2025-)'],en:['Legal clinical access: Mexico (Tepoztlán, Playa del Carmen, Cancún)','Costa Rica: Iboga Wellness Center · psycho-spiritual root bark','Stanford research access (Nolan Williams TBI study)','Texas FDA-directed trials (2025-)']},
  recipe:{es:'No aplica personal. Acceso clínico legal: <strong>IbogaQuest (Tepoztlán)</strong> y múltiples clínicas Playa del Carmen/Cancún ofrecen detox supervisado para opioid use disorder. Sesión típica: 12-72 horas en clínica con ECG continuo + soporte médico + integración post. Costa Rica <strong>Iboga Wellness Center</strong>: psico-espiritual con root bark, no detox. <strong>NUNCA</strong> autoadministración — cardiotoxicidad letal documentada en uso no-supervisado.',en:'Personal doesn\'t apply. Legal clinical access: <strong>IbogaQuest (Tepoztlán)</strong> and multiple Playa del Carmen/Cancún clinics offer supervised opioid detox. Typical session: 12-72 hours in clinic with continuous ECG + medical support + integration after. Costa Rica <strong>Iboga Wellness Center</strong>: psycho-spiritual root-bark only, not detox. <strong>NEVER</strong> self-administer — documented lethal cardiotoxicity in unsupervised use.'},
  sourcing:{
    local:[],
    intl:[
      {name:'IbogaQuest',url:'https://ibogaquest.com',note:{es:'★ Tepoztlán México · clínica supervisada · 4-7 días · ~$8K',en:'★ Tepoztlán Mexico · supervised clinic · 4-7 days · ~$8K'}},
      {name:'Iboga Wellness Center',url:'https://ibogawellness.com',note:{es:'★ Costa Rica · psico-espiritual root bark · ~$3-5K',en:'★ Costa Rica · psycho-spiritual root bark · ~$3-5K'}},
      {name:'Berkeley BCSP Ibogaine',url:'https://psychedelics.berkeley.edu/substance/ibogaine/',note:{es:'centro academic UC Berkeley',en:'UC Berkeley academic center'}},
      {name:'Stanford (Williams TBI study)',url:'https://med.stanford.edu/williamslab.html',note:{es:'access via veterans/TBI clinical research',en:'access via veterans/TBI clinical research'}}
    ]
  }
},

{ id:'salvinorin-a', category:'arylcyclohexylamine',
  name:{es:'Salvinorin A · La Mazateca',en:'Salvinorin A · The Mazatec'},
  origin:{es:'Salvia divinorum · Sierra Mazateca Oaxaca · aislado 1982 Ortega',en:'Salvia divinorum · Sierra Mazateca Oaxaca · isolated 1982 Ortega'},
  one:{es:'Único psicodélico mayor que NO actúa vía 5-HT2A · κ-opioid agonista · 10 minutos.',en:'Only major psychedelic that does NOT act via 5-HT2A · κ-opioid agonist · 10 minutes.'},
  story:{es:'Salvinorin A es el constituyente activo principal de <em>Salvia divinorum</em>, salvia perenne endémica de la Sierra Mazateca de Oaxaca, México, donde curanderos mazatecos la usan ceremonialmente desde tiempo inmemorial para tratar cefaleas, problemas gastrointestinales y dependencia al alcohol. R. Gordon Wasson y Albert Hofmann colectaron especímenes a inicios de los 60; Carl Epling describió la especie en 1962. El diterpeno fue aislado por <strong>Alfredo Ortega, Blount y Manchand (1982, <em>J. Chem. Soc.</em>)</strong>. El descubrimiento farmacológico clave: <strong>Bryan Roth et al. 2002 (<em>PNAS</em>)</strong> mostró que es un agonista κ-opioid potente selectivo — <strong>primer agonista opioid no-nitrogenado conocido</strong> y único hallucinógeno mayor cuyos efectos NO son mediados por 5-HT2A.',en:'Salvinorin A is the principal active constituent of <em>Salvia divinorum</em>, a perennial sage endemic to Oaxaca\'s Sierra Mazateca, Mexico, where Mazatec healers have used it ceremonially since immemorial time to treat headaches, GI complaints, and alcohol dependence. R. Gordon Wasson and Albert Hofmann collected specimens in early 60s; Carl Epling described the species 1962. The diterpene was isolated by <strong>Alfredo Ortega, Blount and Manchand (1982, <em>J. Chem. Soc.</em>)</strong>. Key pharmacological discovery: <strong>Bryan Roth et al. 2002 (<em>PNAS</em>)</strong> showed it\'s a potent selective κ-opioid agonist — <strong>first known non-nitrogenous opioid agonist</strong> and the only major hallucinogen whose effects are NOT mediated by 5-HT2A.'},
  compounds:'C23H30O8 · diterpeno neoclerodano · agonista κ-opioid selectivo Ki ~16nM · primer opioid no-nitrogenado · hidrólisis rápida 10-15 min',
  effect:{es:'Agonista κ-opioid → estado disociativo único — radicalmente diferente a 5-HT2A psicodélicos. Reportes consistentes: pérdida de identidad corporal, sensación de "ser todas las cosas a la vez", duración 10-15 min absoluto. NO es eufórico — frecuentemente disfórico, alienante. Research interest: scaffolds κ-agonista para analgésicos no-adictivos, neuroprotección, anestésicos cortos. La planta es no-programada federalmente en USA pero restringida en muchos estados.',en:'κ-opioid agonist → unique dissociative state — radically different from 5-HT2A psychedelics. Consistent reports: loss of body identity, sensation of "being all things at once", duration 10-15 min absolute. NOT euphoric — frequently dysphoric, alienating. Research interest: κ-agonist scaffolds for non-addictive analgesics, neuroprotection, short anesthetics. Plant is federally unscheduled in USA but restricted in many states.'},
  ingredients:{es:['Hojas Salvia divinorum (legal federalmente USA · restricto en algunos estados)','Acceso retiros mazatecos en Oaxaca (curandera tradicional)','Research papers: Roth 2002 PNAS · therapeutic potential PMC9364973','Libros: Wasson + Hofmann · Salvia divinorum'],en:['Salvia divinorum leaves (federally legal USA · restricted in some states)','Mazatec retreats access in Oaxaca (traditional curandera)','Research papers: Roth 2002 PNAS · therapeutic potential PMC9364973','Books: Wasson + Hofmann · Salvia divinorum']},
  recipe:{es:'Contexto tradicional mazateco: hojas frescas masticadas (quid) durante ceremonia con curandera. Plant Genetic Resources Centre tiene cultivos. <strong>No para uso recreativo</strong> — la intensidad y disforia frecuente hacen el uso no-ceremonial peligroso psicológicamente. Para research: estructura disponible via vendedores académicos con licencia DEA Schedule-N (analógico).',en:'Traditional Mazatec context: fresh leaves chewed (quid) during ceremony with curandera. Plant Genetic Resources Centre has cultivars. <strong>NOT for recreational use</strong> — intensity and frequent dysphoria make non-ceremonial use psychologically dangerous. For research: structure available via academic vendors with Schedule-N DEA license (analog).'},
  sourcing:{
    local:[],
    intl:[
      {name:'Roth et al 2002 PNAS',url:'https://www.pnas.org/doi/10.1073/pnas.182234399',note:{es:'★ paper fundacional κ-opioid mechanism',en:'★ foundational κ-opioid mechanism paper'}},
      {name:'Therapeutic Potential Review (PMC9364973)',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC9364973/',note:{es:'2024 review uso clínico potencial',en:'2024 review of clinical potential use'}},
      {name:'Erowid Salvia Vault',url:'https://erowid.org/plants/salvia',note:{es:'archivo histórico + research',en:'historical + research archive'}},
      {name:'Oaxaca retreats (Mazatec)',url:'https://www.tripsavvy.com/oaxaca-shamanism',note:{es:'guía contactos curanderas mazatecas',en:'Mazatec curandera contact guide'}}
    ]
  }
},

{ id:'2ci', category:'phenethylamine',
  name:{es:'2C-I · PIHKAL #33',en:'2C-I · PIHKAL #33'},
  origin:{es:'Alexander Shulgin · Lafayette CA · 1976-77',en:'Alexander Shulgin · Lafayette CA · 1976-77'},
  one:{es:'4-iodo phenethylamine · entry #33 PIHKAL · terminus de la serie halogenada Shulgin.',en:'4-iodo phenethylamine · PIHKAL entry #33 · terminus of Shulgin halogen series.'},
  story:{es:'2,5-dimetoxi-4-yodofenetilamina sintetizada por <strong>Alexander Shulgin</strong> en 1976-77 en su laboratorio casero en Lafayette, California (operando bajo licencia DEA Schedule I analítica) y publicada como entrada #33 de <em>PIHKAL: A Chemical Love Story</em> (Shulgin &amp; Shulgin, Transform Press 1991). Pertenece a la serie 2C — fenetilaminas ring-substituidas con 2,5-dimetoxi + halógeno/alquilo en posición 4 — estructuralmente homólogas a mescalina. El 4-iodo representa el terminus de la serie halogenada Shulgin discutió en PIHKAL. <strong>Frecuentemente confundido en seizure data con el derivado N-bencilado mucho más peligroso 25I-NBOMe.</strong> Schedule I USA bajo SDAPA 2012.',en:'2,5-dimethoxy-4-iodophenethylamine synthesized by <strong>Alexander Shulgin</strong> in 1976-77 at his home lab in Lafayette, California (operating under analytical DEA Schedule I license) and published as entry #33 of <em>PIHKAL: A Chemical Love Story</em> (Shulgin &amp; Shulgin, Transform Press 1991). Belongs to 2C series — ring-substituted phenethylamines with 2,5-dimethoxy + halogen/alkyl at position 4 — structurally homologous to mescaline. 4-iodo represents terminus of Shulgin\'s halogen series discussed in PIHKAL. <strong>Frequently confused in seizure data with the much more dangerous N-benzylated derivative 25I-NBOMe.</strong> US Schedule I under SDAPA 2012.'},
  compounds:'C10H14INO2 · 2,5-dimetoxi-4-yodofenetilamina · agonista parcial 5-HT2A/2C · clase 2C halogenada',
  effect:{es:'Agonista parcial 5-HT2A/2C. Visuales geométricos coloridos. Duración 6-10 horas — más largo que 2C-B. Componente físico significativo (rubor, taquicardia). Reportes en PIHKAL: "more intellectual, less sensual" que 2C-B. No usado en clínica humana actualmente. Tool compound en chemical-biology + toxicología forense.',en:'Partial 5-HT2A/2C agonist. Colorful geometric visuals. Duration 6-10 hours — longer than 2C-B. Significant physical component (flushing, tachycardia). PIHKAL reports: "more intellectual, less sensual" than 2C-B. Not in current human clinical use. Tool compound in chemical-biology + forensic toxicology.'},
  ingredients:{es:['PIHKAL Entry #33 documentación completa Shulgin','Para research: vendor académico con DEA Schedule I license','Erowid Vault archivo histórico'],en:['PIHKAL Entry #33 complete Shulgin documentation','For research: academic vendor with DEA Schedule I license','Erowid Vault historical archive']},
  recipe:{es:'No aplica personal. Acceso research: a través de vendor académico DEA-registrado Schedule I (no público). PIHKAL Entry #33 describe protocolo Shulgin original: dosis 14-22mg oral. <strong>CRÍTICO: jamás confundir con 25I-NBOMe</strong> — el N-bencilo derivado activo en microgramos pero con dosis letal a 1-2mg, responsable de docenas de muertes en mercado gris.',en:'Personal doesn\'t apply. Research access: through DEA-registered Schedule I academic vendor (not public). PIHKAL Entry #33 describes original Shulgin protocol: 14-22mg oral dose. <strong>CRITICAL: never confuse with 25I-NBOMe</strong> — the N-benzyl derivative active in micrograms but with lethal dose at 1-2mg, responsible for dozens of deaths in gray market.'},
  sourcing:{
    local:[],
    intl:[
      {name:'PIHKAL Entry #33 (Erowid)',url:'https://erowid.org/library/books_online/pihkal/pihkal033.shtml',note:{es:'★ documentación Shulgin completa',en:'★ complete Shulgin documentation'}},
      {name:'2C Designer Drug Review (PMC3657019)',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC3657019/',note:{es:'review científico clase 2C',en:'scientific 2C class review'}},
      {name:'PsychonautWiki 2C-I',url:'https://psychonautwiki.org/wiki/2C-I',note:{es:'community documentation',en:'community documentation'}},
      {name:'PIHKAL libro (Transform Press)',url:'https://www.amazon.com/PiHKAL-Chemical-Love-Story-Phenethylamines/dp/0963009605',note:{es:'★ catálogo completo · Amazon',en:'★ complete catalog · Amazon'}}
    ]
  }
},

{ id:'2ce', category:'phenethylamine',
  name:{es:'2C-E · PIHKAL #24 · Magical Half-Dozen',en:'2C-E · PIHKAL #24 · Magical Half-Dozen'},
  origin:{es:'Alexander Shulgin · 1977 · PIHKAL Entry #24',en:'Alexander Shulgin · 1977 · PIHKAL Entry #24'},
  one:{es:'Una de las seis "magical half-dozen" de Shulgin · 4-ethyl · 8-12 horas.',en:'One of Shulgin\'s six "magical half-dozen" · 4-ethyl · 8-12 hours.'},
  story:{es:'2,5-dimetoxi-4-etilfenetilamina sintetizada y bioasayada por <strong>Alexander Shulgin en 1977</strong> y catalogada como entrada #24 de PIHKAL (1991). Shulgin la clasificó entre la "magical half-dozen" (con mescalina, 2C-B, 2C-T-2, 2C-T-7, DOM) — fenetilaminas que él consideró las más personalmente informativas. Síntesis publicada vía Friedel-Crafts acilación de 1,4-dimetoxibenzeno, reducción Clemmensen, formilación Vilsmeier, condensación Henry a nitroestireno, reducción LAH. Studies de estructura-actividad muestran que el bulk estérico de la posición 4 modula la afinidad 5-HT2A. SDAPA 2012 Schedule I.',en:'2,5-dimethoxy-4-ethylphenethylamine synthesized and bioassayed by <strong>Alexander Shulgin in 1977</strong> and cataloged as entry #24 of PIHKAL (1991). Shulgin classed it among the "magical half-dozen" (with mescaline, 2C-B, 2C-T-2, 2C-T-7, DOM) — phenethylamines he considered the most personally informative. Published synthesis via Friedel-Crafts acylation of 1,4-dimethoxybenzene, Clemmensen reduction, Vilsmeier formylation, Henry condensation to nitrostyrene, LAH reduction. Structure-activity studies show position-4 steric bulk modulates 5-HT2A affinity. SDAPA 2012 Schedule I.'},
  compounds:'C12H19NO2 · 2,5-dimetoxi-4-etilfenetilamina · agonista parcial 5-HT2A/2B/2C · clase 2C alquilo',
  effect:{es:'Agonista parcial 5-HT2A/2B/2C. Visuales más intensos que 2C-B. Componente cognitivo profundo — reportes consistentes de "claridad de pensamiento" durante el viaje. PIHKAL: 10-25mg oral, 8-12 horas duración. Más somáticamente cargado que la mayoría de los 2Cs. No clinical trials humanos activos; tool compound en farmacología de receptores.',en:'Partial 5-HT2A/2B/2C agonist. Visuals more intense than 2C-B. Deep cognitive component — consistent reports of "thought clarity" during trip. PIHKAL: 10-25mg oral, 8-12 hour duration. More somatically loaded than most 2Cs. No active human clinical trials; tool compound in receptor pharmacology.'},
  ingredients:{es:['PIHKAL Entry #24 documentación','Para research: vendor académico Schedule I','PsychonautWiki community documentation'],en:['PIHKAL Entry #24 documentation','For research: Schedule I academic vendor','PsychonautWiki community documentation']},
  recipe:{es:'No aplica personal. PIHKAL #24 describe protocolo Shulgin original con dosis ascendentes 6-25mg. Acceso research requiere DEA Schedule I license para investigador. <strong>Recordar contexto</strong>: Shulgin lo categorizó como uno de los seis compuestos más informativos personalmente — pero su uso era riguroso, en contexto controlado, con notas exhaustivas y red de psicoterapeutas observando.',en:'Personal doesn\'t apply. PIHKAL #24 describes original Shulgin protocol with ascending doses 6-25mg. Research access requires investigator\'s DEA Schedule I license. <strong>Remember context</strong>: Shulgin categorized it as one of six most personally informative compounds — but his use was rigorous, in controlled context, with exhaustive notes and a psychotherapist network observing.'},
  sourcing:{
    local:[],
    intl:[
      {name:'PIHKAL Entry #24 (Erowid)',url:'https://erowid.org/library/books_online/pihkal/pihkal024.shtml',note:{es:'★ documentación Shulgin · magical half-dozen',en:'★ Shulgin documentation · magical half-dozen'}},
      {name:'PsychonautWiki 2C-E',url:'https://psychonautwiki.org/wiki/2C-E',note:{es:'community + structure-activity',en:'community + structure-activity'}},
      {name:'Wikipedia 2C-E',url:'https://en.wikipedia.org/wiki/2,5-Dimethoxy-4-ethyl-phenethylamine',note:{es:'overview accesible',en:'accessible overview'}},
      {name:'PIHKAL libro (Transform Press)',url:'https://www.amazon.com/PiHKAL-Chemical-Love-Story-Phenethylamines/dp/0963009605',note:{es:'catálogo completo',en:'complete catalog'}}
    ]
  }
},

{ id:'doi', category:'phenethylamine',
  name:{es:'DOI · El Tool Compound Maestro',en:'DOI · The Master Tool Compound'},
  origin:{es:'Coutts + Malicky · U. Alberta · 1973 · Shulgin elaboración',en:'Coutts + Malicky · U. Alberta · 1973 · Shulgin elaboration'},
  one:{es:'2,5-dimetoxi-4-iodoanfetamina · el radioligand 5-HT2A más usado en research mundial.',en:'2,5-dimethoxy-4-iodoamphetamine · the most-used 5-HT2A radioligand in world research.'},
  story:{es:'DOI es un homólogo α-metilado (anfetamina) de 2C-I. Reportado primero por <strong>Coutts y Malicky (U. Alberta, 1973)</strong> y detallado por Shulgin en PIHKAL (1991). Miembro de la serie DOx, DOI se ha convertido en <strong>uno de los compuestos farmacológicos tool más importantes en research serotonina</strong>: en 1987 un equipo que incluyó Dennis McKenna y Alexander Shulgin usó [125I]-DOI para mapear distribución de receptores 5-HT2 en cerebro de rata, y el radioligand permanece en uso rutinario hoy. <strong>Charles Nichols (LSU)</strong> demostró efectos antiinflamatorios potentes a concentraciones picomolar, con programas traslacionales en asma/inflamación pulmonar. DEA emergency-scheduled 2024.',en:'DOI is an α-methylated (amphetamine) homolog of 2C-I. First reported by <strong>Coutts and Malicky (U. Alberta, 1973)</strong> and elaborated by Shulgin in PIHKAL (1991). Member of DOx series, DOI has become <strong>one of the most important pharmacological tool compounds in serotonin research</strong>: in 1987 a team including Dennis McKenna and Alexander Shulgin used [125I]-DOI to map 5-HT2 receptor distribution in rat brain, and the radioligand remains in routine use today. <strong>Charles Nichols (LSU)</strong> demonstrated potent anti-inflammatory effects at picomolar concentrations, with translational programs in asthma/pulmonary inflammation. DEA emergency-scheduled 2024.'},
  compounds:'C11H16INO2 · 2,5-dimetoxi-4-yodoanfetamina · clase DOx · agonista 5-HT2A/2B/2C alta afinidad · sin actividad DA/NE',
  effect:{es:'Agonista 5-HT2A/2B/2C alta afinidad. ESENCIALMENTE no dopaminérgico ni noradrenérgico — selectivo serotonina. Duración larga 16-24 horas (la más larga de los psicodélicos clásicos). El isómero (R)-DOI tiene efectos antiinflamatorios a concentraciones picomolar — <strong>10,000x más potente que dexametasona en algunos modelos</strong>. (-)-DOI reduce drug-seeking en modelos preclínicos opioide/cocaine (2024 preclinical). Olson lab UC Davis lo usa en head-twitch assays para diseñar análogos no-alucinógenos.',en:'High-affinity 5-HT2A/2B/2C agonist. ESSENTIALLY non-dopaminergic and non-noradrenergic — serotonin-selective. Long duration 16-24 hours (longest of classical psychedelics). The (R)-DOI isomer has anti-inflammatory effects at picomolar concentrations — <strong>10,000x more potent than dexamethasone in some models</strong>. (-)-DOI reduces drug-seeking in opioid/cocaine preclinical models (2024 preclinical). Olson lab UC Davis uses it in head-twitch assays to design non-hallucinogenic analogs.'},
  ingredients:{es:['Acceso research: Charles Nichols Lab LSU (translational asthma)','David Olson Lab UC Davis (non-hallucinogenic analogs)','PIHKAL DOI entry (Shulgin)','DEA Schedule I license requerido'],en:['Research access: Charles Nichols Lab LSU (translational asthma)','David Olson Lab UC Davis (non-hallucinogenic analogs)','PIHKAL DOI entry (Shulgin)','DEA Schedule I license required']},
  recipe:{es:'No aplica personal. Acceso research solo. DOI es interesante porque Nichols Lab está desarrollando análogos NO-alucinógenos del scaffold DOI para asma, depresión, inflamación. Si el paradigma "psychedelic without trip" funciona, DOI será fundacional. Olson Lab también pioneros en "tabernanthine" — análogos no-psicodélicos.',en:'Personal doesn\'t apply. Research access only. DOI is interesting because Nichols Lab is developing NON-hallucinogenic analogs of the DOI scaffold for asthma, depression, inflammation. If the "psychedelic without trip" paradigm works, DOI will be foundational. Olson Lab also pioneers in "tabernanthine" — non-psychedelic analogs.'},
  sourcing:{
    local:[],
    intl:[
      {name:'Wikipedia DOI',url:'https://en.wikipedia.org/wiki/2,5-Dimethoxy-4-iodoamphetamine',note:{es:'overview accesible',en:'accessible overview'}},
      {name:'Charles Nichols Lab (LSU)',url:'https://www.lsuhsc.edu/no/charles-nichols',note:{es:'★ translational research antiinflammatory',en:'★ translational anti-inflammatory research'}},
      {name:'DOI/cocaine reward (PMC12297012)',url:'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12297012/',note:{es:'preclinical addiction model 2024',en:'2024 preclinical addiction model'}},
      {name:'Olson Lab UC Davis (Delix Therapeutics)',url:'https://delixtherapeutics.com',note:{es:'★ análogos no-alucinógenos comerciales',en:'★ commercial non-hallucinogenic analogs'}}
    ]
  }
},

{ id:'4aco-dmt', category:'tryptamine',
  name:{es:'4-AcO-DMT · Psilacetina',en:'4-AcO-DMT · Psilacetin'},
  origin:{es:'Albert Hofmann + Franz Troxler · Sandoz · 1963',en:'Albert Hofmann + Franz Troxler · Sandoz · 1963'},
  one:{es:'Prodroga sintética de psilocina · 99.9% se convierte en psilocina en 5 minutos.',en:'Synthetic prodrug of psilocin · 99.9% converts to psilocin in 5 minutes.'},
  story:{es:'4-Acetoxi-N,N-dimetiltriptamina patentada el <strong>16 enero 1963 por Albert Hofmann y Franz Troxler en Sandoz Laboratories</strong> como parte de la exploración SAR siguiendo el aislamiento de Hofmann de psilocibina/psilocina de <em>Psilocybe mexicana</em> en 1958. Como psilocibina (el éster O-fosfórico natural), 4-AcO-DMT es prodroga de psilocina; las esterasas plasmáticas convierten &gt;99.9% en 5 minutos (Frontiers in Psychiatry 2024 validación in-vivo). <strong>David E. Nichols</strong> en Purdue publicó síntesis mejorada en 1999 y propuso explícitamente 4-AcO-DMT como alternativa sintética económica a psilocibina para research (material GMP psilocibina siendo escaso/caro). <strong>NO scheduled internacionalmente</strong> (no listado en 1971 UN Convention).',en:'4-Acetoxy-N,N-dimethyltryptamine patented <strong>January 16, 1963 by Albert Hofmann and Franz Troxler at Sandoz Laboratories</strong> as part of SAR exploration following Hofmann\'s 1958 isolation of psilocybin/psilocin from <em>Psilocybe mexicana</em>. Like psilocybin (the natural O-phosphoryl ester), 4-AcO-DMT is psilocin prodrug; plasma esterases convert &gt;99.9% within 5 minutes (Frontiers in Psychiatry 2024 in-vivo validation). <strong>David E. Nichols</strong> at Purdue published improved synthesis 1999 and explicitly proposed 4-AcO-DMT as economical synthetic alternative to psilocybin for research (GMP psilocybin material being scarce/expensive). <strong>NOT internationally scheduled</strong> (not listed in 1971 UN Convention).'},
  compounds:'C14H18N2O2 · 4-acetoxi-N,N-dimetiltriptamina · prodroga psilocina · convierte rápidamente vía esterasas plasmáticas',
  effect:{es:'Como prodroga: indistinguible farmacológicamente de psilocibina porque ambos convierten en psilocina activa. Agonista 5-HT2A/1A/2C parcial. Estudios recientes in-vivo sugieren exposición sistemática a psilocina del psilacetin es ~70% del equivalente psilocibina. Para research: ventaja económica y de síntesis sobre psilocibina GMP. Todos los programas clínicos psilocibina (COMPASS COMP360, Usona Institute, Hopkins, Imperial) son directamente informativos.',en:'As prodrug: pharmacologically indistinguishable from psilocybin since both convert to active psilocin. Partial 5-HT2A/1A/2C agonist. Recent in-vivo studies suggest psilacetin systemic psilocin exposure is ~70% of equivalent psilocybin. For research: economic and synthesis advantage over GMP psilocybin. All psilocybin clinical programs (COMPASS COMP360, Usona Institute, Hopkins, Imperial) are directly informative.'},
  ingredients:{es:['Nichols 1999 paper · síntesis mejorada','Patente Sandoz CH 471157 (publica gratis)','Psychedelic Science Review artículo','Frontiers in Psychiatry 2024 in-vivo validation'],en:['Nichols 1999 paper · improved synthesis','Sandoz Patent CH 471157 (publicly free)','Psychedelic Science Review article','Frontiers in Psychiatry 2024 in-vivo validation']},
  recipe:{es:'No aplica personal. Documentación research: la patente Sandoz original CH 471157 está públicamente disponible. Nichols 1999 paper describe la síntesis económica. Para psicoterapia: usar acceso clínico legal a psilocibina (Oregon, Compass, Hopkins) — la psilocina activa es idéntica.',en:'Personal doesn\'t apply. Research documentation: original Sandoz patent CH 471157 publicly available. Nichols 1999 paper describes economical synthesis. For psychotherapy: use legal clinical psilocybin access (Oregon, Compass, Hopkins) — the active psilocin is identical.'},
  sourcing:{
    local:[],
    intl:[
      {name:'Psychedelic Science Review on Psilacetin',url:'https://psychedelicreview.com/the-state-of-the-art-of-psilacetin-4-aco-dmt/',note:{es:'★ state of the art article',en:'★ state of the art article'}},
      {name:'Frontiers in vivo validation',url:'https://www.frontiersin.org/journals/psychiatry/articles/10.3389/fpsyt.2023.1303365/full',note:{es:'2024 validación in-vivo psilocina',en:'2024 in-vivo psilocin validation'}},
      {name:'David Nichols Lab archive',url:'https://psychoactivescience.com/researchers/david-nichols',note:{es:'Purdue legacy + Heffter Institute',en:'Purdue legacy + Heffter Institute'}},
      {name:'Oregon Psilocybin Services',url:'https://www.oregon.gov/oha/PH/PreventionWellness/Pages/Oregon-Psilocybin-Services.aspx',note:{es:'★ acceso legal psilocina equivalente',en:'★ legal psilocin-equivalent access'}}
    ]
  }
},

{ id:'mda', category:'phenethylamine',
  name:{es:'MDA · "Eve" predecesor de MDMA',en:'MDA · "Eve" predecessor to MDMA'},
  origin:{es:'Carl Mannich + Willy Jacobsohn · Berlin · 1910',en:'Carl Mannich + Willy Jacobsohn · Berlin · 1910'},
  one:{es:'El primer compuesto del término "entactogen" · 16 años antes que MDMA.',en:'The first compound for the term "entactogen" · 16 years before MDMA.'},
  story:{es:'MDA fue <strong>sintetizado primero por Carl Mannich y Willy Jacobsohn (Berlin) en 1910</strong> y patentado en 1912. Gordon Alles lo autoadministró en 1930 y reportó efectos alucinógenos + entactogénicos en 1959; Smith, Kline &amp; French lo exploraron como antitusivo (1958), atarájico (1960), y anoréctico (1961). Entró trials humanos en SKF 1941 para Parkinson. <strong>Alexander Shulgin</strong> re-sintetizó MDA junto con MDMA y MDE ("Eve") en los 60s — el último siendo el homólogo N-etilo que Ann Shulgin popularizó en PIHKAL. MDA es <strong>el primer compuesto para el cual se acuñó el término "entactogen"</strong> (Nichols 1986, "tocando dentro"). Phase 1 clinical study NCT00823407 conducido por NIH.',en:'MDA was <strong>first synthesized by Carl Mannich and Willy Jacobsohn (Berlin) in 1910</strong> and patented 1912. Gordon Alles self-administered it in 1930 and reported hallucinogenic + entactogenic effects in 1959; Smith, Kline &amp; French explored as antitussive (1958), ataractic (1960), anorectic (1961). Entered SKF human trials 1941 for Parkinson\'s. <strong>Alexander Shulgin</strong> re-synthesized MDA along with MDMA and MDE ("Eve") in 60s — the latter being the N-ethyl homolog Ann Shulgin popularized in PIHKAL. MDA is <strong>the first compound for which the term "entactogen" was coined</strong> (Nichols 1986, "touching within"). Phase 1 clinical study NCT00823407 conducted by NIH.'},
  compounds:'C10H13NO2 · 3,4-metilendioxianfetamina · liberador 5-HT/NE/DA · agonista 5-HT2A · clase fenetilamina-anfetamina',
  effect:{es:'Liberador serotonina + norepinefrina + dopamina simultáneamente como MDMA, pero con perfil más alucinógeno (más visual). Duración 5-8 horas (más larga que MDMA). Más liberación de dopamina que MDMA → componente euforico más fuerte. NUNCA combinar con SSRI/MAOI farmacéutico — síndrome serotoninérgico. Schedule I 1970. La MAPS/Lykos MDMA Phase 3 enfrentó FDA CRL agosto 2024, lanzada mayo 2026; Lykos redujo staff ~75% y negocia trial pathway confirmatorio.',en:'Serotonin + norepinephrine + dopamine releaser simultaneously like MDMA, but with more hallucinogenic profile (more visual). Duration 5-8 hours (longer than MDMA). More dopamine release than MDMA → stronger euphoric component. NEVER combine with pharmaceutical SSRI/MAOI — serotonin syndrome. Schedule I 1970. The MAPS/Lykos MDMA Phase 3 faced FDA CRL August 2024, released May 2026; Lykos reduced staff ~75% and negotiating confirmatory trial pathway.'},
  ingredients:{es:['ClinicalTrials.gov NCT00823407 (Phase 1 MDA pharmacology)','Lykos Therapeutics confirmatory trial pathway','PIHKAL Entry MDA (Shulgin)','Erowid MDA Vault'],en:['ClinicalTrials.gov NCT00823407 (Phase 1 MDA pharmacology)','Lykos Therapeutics confirmatory trial pathway','PIHKAL Entry MDA (Shulgin)','Erowid MDA Vault']},
  recipe:{es:'No aplica personal. Acceso clínico actual: ninguno aprobado. La pathway clínica más cercana es MAPS/Lykos MDMA-AT — Lykos negociando trial confirmatorio post-CRL. Para research académico: NCT00823407 Phase 1 pharmacology study. Para uso terapéutico: esperar progreso post-CRL Lykos o programs internacionales legales.',en:'Personal doesn\'t apply. Current clinical access: none approved. Closest clinical pathway is MAPS/Lykos MDMA-AT — Lykos negotiating confirmatory trial post-CRL. For academic research: NCT00823407 Phase 1 pharmacology study. For therapeutic use: await Lykos post-CRL progress or international legal programs.'},
  sourcing:{
    local:[],
    intl:[
      {name:'Wikipedia MDA',url:'https://en.wikipedia.org/wiki/3,4-Methylenedioxyamphetamine',note:{es:'overview histórico',en:'historical overview'}},
      {name:'Lykos Therapeutics',url:'https://lykospsychedelics.com',note:{es:'★ MDMA Phase 3 post-CRL trajectory',en:'★ MDMA Phase 3 post-CRL trajectory'}},
      {name:'ClinicalTrials.gov NCT00823407',url:'https://clinicaltrials.gov/study/NCT00823407',note:{es:'Phase 1 MDA pharmacology study',en:'Phase 1 MDA pharmacology study'}},
      {name:'MAPS.org',url:'https://maps.org/mdma/ptsd/',note:{es:'★ MDMA-AT context + research',en:'★ MDMA-AT context + research'}}
    ]
  }
},

{ id:'lsa', category:'tryptamine',
  name:{es:'LSA · Ololiuhqui · Lysergamida Natural',en:'LSA · Ololiuhqui · Natural Lysergamide'},
  origin:{es:'Albert Hofmann · 1947 sintetizado · 1960 aislado de ololiuhqui',en:'Albert Hofmann · 1947 synthesized · 1960 isolated from ololiuhqui'},
  one:{es:'LSD con dos N-H en lugar de dietilo · Hofmann identificó las semillas aztecas en 1960.',en:'LSD with two N-H instead of diethyl · Hofmann identified the Aztec seeds in 1960.'},
  story:{es:'Amida del ácido lisérgico (ergina, LA-111) es la lisergamida natural más simple — LSD con dos N-H en lugar del sustituyente dietilo. Descrita como constituyente del cornezuelo en 1932; <strong>sintetizada y autoadministrada por Albert Hofmann en 1947</strong>, quien reportó "un estado cansado, soñador con incapacidad de mantener pensamientos claros" a 500µg IM. R. Gordon Wasson envió muestras de "ololiuhqui" mexicana (<em>Rivea/Turbina corymbosa</em>) a Hofmann, quien <strong>en 1960 identificó LSA, ácido isolisérgico amida y chanoclavina</strong> como los alcaloides activos — descubrimiento landmark mostrando que alcaloides ergoloid ocurren en plantas superiores (Convolvulaceae) y en el hongo simbiótico <em>Periglandula</em>. Uso ceremonial azteca documentado por Bernardino de Sahagún (<em>Códice Florentino</em>).',en:'Lysergic acid amide (ergine, LA-111) is the simplest natural lysergamide — LSD with two N-H in place of diethyl substituent. Described as ergot constituent in 1932; <strong>synthesized and self-administered by Albert Hofmann in 1947</strong>, who reported "a tired, dreamy state with inability to maintain clear thoughts" at 500µg IM. R. Gordon Wasson sent samples of Mexican "ololiuhqui" (<em>Rivea/Turbina corymbosa</em>) to Hofmann, who <strong>in 1960 identified LSA, isolysergic acid amide and chanoclavine</strong> as active alkaloids — landmark discovery showing ergoloid alkaloids occur in higher plants (Convolvulaceae) and symbiotic <em>Periglandula</em> fungus. Aztec ceremonial use documented by Bernardino de Sahagún (<em>Florentine Codex</em>).'},
  compounds:'C16H17N3O · amida del ácido lisérgico · ergoloid natural · agonista parcial 5-HT2A · presente en Argyreia nervosa, Ipomoea tricolor, Turbina corymbosa',
  effect:{es:'Agonista parcial 5-HT2A con afinidad sustancialmente menor que LSD y efectos sedativos/dopaminérgicos pronunciados. Duración 6-10 horas. Reportes consistentes: sedativo + "trip onírico" en lugar del crisp visual de LSD. Náusea común (ergoloid sequence). Las semillas mismas son no-programadas federalmente USA pero restringidas en algunos estados (Louisiana Act 159) y Australia.',en:'Partial 5-HT2A agonist with substantially lower affinity than LSD and pronounced sedative/dopaminergic effects. Duration 6-10 hours. Consistent reports: sedative + "dream-like trip" rather than LSD\'s crisp visuals. Common nausea (ergoloid sequence). Seeds themselves are federally unscheduled USA but restricted in some states (Louisiana Act 159) and Australia.'},
  ingredients:{es:['Semillas Hawaiian baby woodrose (Argyreia nervosa) · no programadas federal USA','Semillas morning glory (Ipomoea tricolor/violacea) · ornamentales','Hofmann 1960 paper sobre ololiuhqui · Sandoz archives','Bernardino de Sahagún Códice Florentino'],en:['Hawaiian baby woodrose seeds (Argyreia nervosa) · federally unscheduled USA','Morning glory seeds (Ipomoea tricolor/violacea) · ornamental','Hofmann 1960 paper on ololiuhqui · Sandoz archives','Bernardino de Sahagún Florentine Codex']},
  recipe:{es:'No aplica personal para alcaloide aislado (Schedule III LSD precursor USA). Las semillas son legales en muchas jurisdicciones pero contienen otros alcaloides (chanoclavine, sedativos secundarios). Históricamente usadas ceremonialmente azteca + zapoteca con curandero. Modernamente: research botánico y arqueológico. Para experiencia comparable acceder LSD-25 clinical research vía MindMed Phase 3 trials.',en:'Personal doesn\'t apply for isolated alkaloid (Schedule III LSD precursor USA). Seeds legal in many jurisdictions but contain other alkaloids (chanoclavine, secondary sedatives). Historically used ceremonially Aztec + Zapotec with curandero. Modernly: botanical and archaeological research. For comparable experience access LSD-25 clinical research via MindMed Phase 3 trials.'},
  sourcing:{
    local:[],
    intl:[
      {name:'Ergine — Wikipedia',url:'https://en.wikipedia.org/wiki/Ergine',note:{es:'overview alcaloide',en:'alkaloid overview'}},
      {name:'Two cases lysergamide intoxication (ScienceDirect)',url:'https://www.sciencedirect.com/science/article/abs/pii/S0379073809004745',note:{es:'caso clínico documentado',en:'documented clinical case'}},
      {name:'MindMed MM120 (LSD trials)',url:'https://ir.mindmed.co',note:{es:'★ Phase 3 LSD GAD · acceso alternativa legal',en:'★ Phase 3 LSD GAD · legal alternative access'}},
      {name:'Erowid LSA Vault',url:'https://erowid.org/chemicals/lsa',note:{es:'archivo histórico',en:'historical archive'}}
    ]
  }
},

{ id:'mxe', category:'arylcyclohexylamine',
  name:{es:'MXE · Methoxetamine',en:'MXE · Methoxetamine'},
  origin:{es:'Steve Heintz · Mexis Labs UK · 2010',en:'Steve Heintz · Mexis Labs UK · 2010'},
  one:{es:'El primer designer dissociative · diseñado como alternativa "bladder-friendly" a ketamina.',en:'The first designer dissociative · designed as "bladder-friendly" ketamine alternative.'},
  story:{es:'Methoxetamina — (RS)-2-(etilamino)-2-(3-metoxifenil)ciclohexanona — es una arilciclohexilamina disociativa diseñada en 2010 por el químico UK <strong>Steve Heintz de Mexis Labs</strong>, quien la diseñó explícitamente como alternativa "bladder-friendly" a ketamina para tratarse phantom-limb pain. La afirmación de "bladder-friendly" (marcada como "MEXXY") se demostró falsa posteriormente — datos preclínicos indican toxicidad renal/cística comparable a ketamina. Roth et al. (<em>PLoS One</em> 2013) demostró antagonista NMDA selectivo de alta afinidad con afinidad SERT apreciable distinto de ketamina. <strong>MXE fue históricamente pivotal como el primer "designer dissociative" ampliamente distribuido</strong> de la era NPS (novel-psychoactive-substance) y precipitó la UK Psychoactive Substances Act 2016.',en:'Methoxetamine — (RS)-2-(ethylamino)-2-(3-methoxyphenyl)cyclohexanone — is an arylcyclohexylamine dissociative designed in 2010 by UK chemist <strong>Steve Heintz of Mexis Labs</strong>, who designed it explicitly as a "bladder-friendly" ketamine alternative for self-treating phantom-limb pain. The "bladder-friendly" claim (marketed as "MEXXY") later shown false — preclinical data indicates renal/cystic toxicity comparable to ketamine. Roth et al. (<em>PLoS One</em> 2013) demonstrated high-affinity selective NMDA antagonist with appreciable SERT affinity unlike ketamine. <strong>MXE was historically pivotal as the first widely distributed "designer dissociative"</strong> of the NPS (novel-psychoactive-substance) era and precipitated the UK Psychoactive Substances Act 2016.'},
  compounds:'C15H21NO2 · 3-MeO-2-Oxo-PCE · antagonista NMDA selectivo · agente disociativo · vida media ~3h',
  effect:{es:'Antagonista NMDA uncompetitivo en el sitio PCP. Afinidad SERT apreciable (diferente de ketamina) le da componente serotonérgico. Behavioral pharmacology (Horsley et al. 2016) muestra perfil indistinguible de ketamina/PCP. Schedule I USA (2013 emergency, permanente 2015). Class B UK. Importancia traslacional actual: scaffolds MXE-derivados (3-MeO-PCE, fluorinated arylcyclohexylamines) aparecen en literatura académica sobre antidepresivos de acción rápida modeled on ketamine.',en:'Uncompetitive NMDA antagonist at PCP site. Appreciable SERT affinity (different from ketamine) gives it a serotonergic component. Behavioral pharmacology (Horsley et al. 2016) shows profile indistinguishable from ketamine/PCP. Schedule I USA (2013 emergency, permanent 2015). Class B UK. Current translational importance: MXE-derived scaffolds (3-MeO-PCE, fluorinated arylcyclohexylamines) appear in academic literature on rapid-acting antidepressants modeled on ketamine.'},
  ingredients:{es:['Roth 2013 PLoS One paper','Horsley 2016 behavioral pharmacology','Acceso ketamina clínica legal (Field Trip, Mindbloom, Spravato)','Tool compound NMDA pharmacology'],en:['Roth 2013 PLoS One paper','Horsley 2016 behavioral pharmacology','Legal clinical ketamine access (Field Trip, Mindbloom, Spravato)','NMDA pharmacology tool compound']},
  recipe:{es:'No aplica personal. Acceso clínico equivalente: ketamina IV/IM/sublingual via Mindbloom telehealth, Field Trip Health clínicas, Spravato (esketamine nasal) J&amp;J. Para research: tool compound NMDA pharmacology, no human trials activos. Importancia histórica: MXE fue el catalyst que llevó a la regulación NPS — su scaffold continúa influyendo el diseño de antidepresivos rápidos.',en:'Personal doesn\'t apply. Equivalent clinical access: ketamine IV/IM/sublingual via Mindbloom telehealth, Field Trip Health clinics, Spravato (esketamine nasal) J&amp;J. For research: NMDA pharmacology tool compound, no active human trials. Historical importance: MXE was catalyst leading to NPS regulation — its scaffold continues influencing rapid antidepressant design.'},
  sourcing:{
    local:[],
    intl:[
      {name:'Roth 2013 PLoS One (PMC3602154)',url:'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3602154/',note:{es:'★ paper fundacional NMDA pharmacology',en:'★ foundational NMDA pharmacology paper'}},
      {name:'Horsley 2016 (PMC5403250)',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC5403250/',note:{es:'behavioral pharmacology comparison',en:'behavioral pharmacology comparison'}},
      {name:'Mindbloom (ketamina legal alternativa)',url:'https://www.mindbloom.com',note:{es:'★ ketamina sublingual telehealth · USA',en:'★ ketamine sublingual telehealth · USA'}},
      {name:'Field Trip Health',url:'https://www.fieldtriphealth.com',note:{es:'★ ketamina IV clínica · USA/Canadá/UK',en:'★ ketamine IV clinic · USA/Canada/UK'}}
    ]
  }
}

];
