/* =============================================================
   SORA · MEDICINES DATABASE
   Modern pharmacology + clinical compounds for longevity,
   cognition, and treatment-resistant conditions.
   Includes both OTC supplements (NMN, methylene blue) and
   prescription compounds (modafinil, racetams, off-label
   metformin). Some require physician.
   Loaded as window.MEDICINES.
   ============================================================= */
window.MEDICINES = [

{ id:'methylene-blue', category:'mitochondrial',
  name:{es:'Azul de Metileno · Primer Fármaco Sintético',en:'Methylene Blue · First Synthetic Drug'},
  origin:{es:'Heinrich Caro · BASF · 1876 · primer compuesto sintético',en:'Heinrich Caro · BASF · 1876 · first synthetic compound'},
  one:{es:'El primer medicamento sintético de la historia · Paul Ehrlich · Szent-Györgyi.',en:'History\'s first synthetic medicine · Paul Ehrlich · Szent-Györgyi.'},
  story:{es:'Sintetizado en 1876 por Heinrich Caro en BASF como tinte textil azul. En 1891 Paul Ehrlich (Nobel 1908) lo usó para teñir microorganismos en biopsias — y descubrió que selectivamente penetraba ciertas células más que otras. Le dio el concepto de "bala mágica" — un compuesto que actúa selectivamente. Lo aplicó a malaria, fue el primer fármaco sintético del mundo. Albert Szent-Györgyi estudió su rol como dador de electrones en respiración mitocondrial — funciona como un "electron bypass" cuando la cadena respiratoria está dañada. Resurgió en biohacking 2010s para fatiga crónica, neurodegeneración y enhancement cognitivo.',en:'Synthesized in 1876 by Heinrich Caro at BASF as a blue textile dye. In 1891 Paul Ehrlich (1908 Nobel) used it to stain microorganisms in biopsies — and discovered it selectively penetrated some cells more than others. Gave him the concept of "magic bullet" — a compound that acts selectively. Applied to malaria, became the world\'s first synthetic drug. Albert Szent-Györgyi studied its role as electron donor in mitochondrial respiration — works as an "electron bypass" when the respiratory chain is damaged. Resurged in 2010s biohacking for chronic fatigue, neurodegeneration and cognitive enhancement.'},
  compounds:'C16H18ClN3S · methylthioninium chloride · USP grade (NO industrial grade — contiene metales pesados)',
  effect:{es:'Donante directo de electrones a citocromo C en mitocondria — útil cuando la cadena respiratoria celular está disfuncional. Inhibe monoamino oxidasa (MAOI suave). Atraviesa barrera hematoencefálica. Antimalárico clásico. Estudios modernos: mejora memoria en deterioro leve, fatiga crónica, sepsis (uso hospitalario para metahemoglobinemia). NO mezclar con SSRI/MAOI — riesgo síndrome serotoninérgico. NO usar grado industrial — contaminantes.',en:'Direct electron donor to cytochrome C in mitochondria — useful when cellular respiratory chain is dysfunctional. Inhibits monoamine oxidase (mild MAOI). Crosses blood-brain barrier. Classic antimalarial. Modern studies: improves memory in mild cognitive impairment, chronic fatigue, sepsis (hospital use for methemoglobinemia). DO NOT mix with SSRI/MAOI — serotonin syndrome risk. DO NOT use industrial grade — contaminants.'},
  ingredients:{es:['Methylene Blue USP grado farmacéutico · 1% solución (10mg/ml)','Pipeta gotero · 0.5ml','Vaso vidrio · 100ml agua filtrada','Vitamina C 500mg (acelera reducción si necesario)'],en:['USP pharmaceutical-grade Methylene Blue · 1% solution (10mg/ml)','Dropper pipette · 0.5ml','Glass · 100ml filtered water','Vitamin C 500mg (accelerates reduction if needed)']},
  recipe:{es:'Dosis baja-segura: 0.5-1mg/kg = 30-60mg para adulto. 1ml de solución 1% = 10mg. Diluir 3-6ml en 100ml de agua filtrada en vaso de vidrio (NO plástico — el azul se adhiere). Tomar en ayunas. La lengua y orina se tornan AZULES por 24h (es normal). Usar diariamente max 4 semanas, después 2 semanas off. Stack con vitamina C reduce el azul a leucometileno (color claro).',en:'Safe low dose: 0.5-1mg/kg = 30-60mg for adult. 1ml of 1% solution = 10mg. Dilute 3-6ml in 100ml filtered water in glass (NO plastic — blue adheres). Take fasted. Tongue and urine turn BLUE for 24h (normal). Use daily max 4 weeks, then 2 weeks off. Stack with vitamin C reduces the blue to leukomethylene (clear color).'},
  sourcing:{
    local:[],
    intl:[
      {name:'BlueBrainBoost',url:'https://bluebrainboost.com',note:{es:'★ USP farmacéutico · USA · 7-10d via Aeropost',en:'★ pharmaceutical USP · USA · 7-10d via Aeropost'}},
      {name:'Troscriptions Blue Cannatine',url:'https://troscriptions.com',note:{es:'sublingual premium · caffeine + L-theanine + nicotine',en:'premium sublingual · caffeine + L-theanine + nicotine'}},
      {name:'iHerb',url:'https://www.iherb.com/search?kw=methylene+blue',note:{es:'cápsulas orales · directo PA',en:'oral capsules · direct PA'}}
    ]
  }
},

{ id:'nmn', category:'longevity',
  name:{es:'NMN · Precursor de NAD+',en:'NMN · NAD+ Precursor'},
  origin:{es:'David Sinclair · Harvard · 2013-presente',en:'David Sinclair · Harvard · 2013-present'},
  one:{es:'La molécula con la que David Sinclair quiere vivir 150 años.',en:'The molecule David Sinclair plans to live 150 years on.'},
  story:{es:'Nicotinamide Mononucleotide (NMN) es un precursor directo de NAD+ — una de las moléculas más críticas del cuerpo. NAD+ se requiere para 500+ reacciones celulares, incluyendo activación de sirtuinas (SIRT1-7) — las "proteínas de longevidad". Niveles de NAD+ caen ~50% entre los 20 y los 60 años. David Sinclair, profesor de genética en Harvard y autor de <em>Lifespan</em> (2019), popularizó NMN como suplemento anti-envejecimiento. Estudios en ratones muestran restauración de función mitocondrial, mejora de resistencia, y aspecto más joven.',en:'Nicotinamide Mononucleotide (NMN) is a direct precursor to NAD+ — one of the body\'s most critical molecules. NAD+ required for 500+ cellular reactions, including activation of sirtuins (SIRT1-7) — the "longevity proteins". NAD+ levels drop ~50% between ages 20 and 60. David Sinclair, Harvard genetics professor and author of <em>Lifespan</em> (2019), popularized NMN as anti-aging supplement. Mouse studies show restoration of mitochondrial function, endurance improvement, and younger appearance.'},
  compounds:'Nicotinamide mononucleotide · C11H15N2O8P · precursor directo de NAD+ · pureza 99% requerida',
  effect:{es:'Eleva NAD+ celular 20-60% en humanos (medido en sangre). Activa SIRT1-7 (sirtuinas longevity). Mejora función mitocondrial. Up-regula DNA repair. Mejora resistencia cardiovascular. La ruta sublingual o liposomal es 10x más bioasimilable que cápsulas tradicionales.',en:'Raises cellular NAD+ 20-60% in humans. Activates SIRT1-7 (longevity sirtuins). Improves mitochondrial function. Up-regulates DNA repair. Boosts cardiovascular endurance. Sublingual or liposomal route is 10x more bioavailable than traditional capsules.'},
  ingredients:{es:['NMN polvo o sublingual · 500-1000mg/día (sublingual o liposomal preferido)','Pterostilbeno · 100mg · sinérgico (Sinclair stack)','TMG (trimetilglicina) · 500mg · evita depleción de metiles','Tomar en ayunas por la mañana'],en:['NMN powder or sublingual · 500-1000mg/day (sublingual or liposomal preferred)','Pterostilbene · 100mg · synergistic (Sinclair stack)','TMG (trimethylglycine) · 500mg · prevents methyl depletion','Take fasted in morning']},
  recipe:{es:'El stack Sinclair: 500-1000mg NMN sublingual + 100mg pterostilbeno + 500mg TMG en ayunas. El sublingual: polvo bajo la lengua 60-90s antes de tragar — evita primer paso hepático. Stack continuamente 6-12 meses, después medir niveles NAD+ si quieres datos. Más beneficio para personas 40+.',en:'Sinclair stack: 500-1000mg NMN sublingual + 100mg pterostilbene + 500mg TMG fasted. Sublingual: powder under tongue 60-90s before swallowing — bypasses hepatic first-pass. Stack continuously 6-12 months, then measure NAD+ if you want data. More benefit for people 40+.'},
  sourcing:{
    local:[
      {name:'GNC Multicentro David',url:'https://www.gnc.com.pa',note:{es:'NMN cápsulas básicas 250mg · revisar pureza',en:'basic NMN capsules 250mg · verify purity'}}
    ],
    intl:[
      {name:'ProHealth Longevity',url:'https://www.prohealthlongevity.com',note:{es:'★ NMN sublingual Sinclair-recomendado · USA',en:'★ Sinclair-recommended sublingual NMN · USA'}},
      {name:'iHerb',url:'https://www.iherb.com/search?kw=nmn+sublingual',note:{es:'múltiples marcas · directo PA · 7-14d',en:'multiple brands · direct PA · 7-14d'}},
      {name:'Renue by Science',url:'https://renuebyscience.com',note:{es:'NMN + liposomal NAD+ premium · USA',en:'NMN + premium liposomal NAD+ · USA'}}
    ]
  }
},

{ id:'modafinil', category:'cognitive',
  name:{es:'Modafinil · Vigilia Eugeroica',en:'Modafinil · Eugeroic Wakefulness'},
  origin:{es:'Michel Jouvet · Lafon · Francia · 1976 · aprobado FDA 1998',en:'Michel Jouvet · Lafon · France · 1976 · FDA approved 1998'},
  one:{es:'La pastilla "Limitless" de la vida real · vigilia limpia sin pico euforico.',en:'Real-life "Limitless" pill · clean wakefulness without euphoric peak.'},
  story:{es:'Desarrollado en los años 70 por el neuroquímico francés Michel Jouvet y los laboratorios Lafon. Aprobado en Francia (1986) y EEUU (1998) para narcolepsia, apnea del sueño, y trastornos del turno de trabajo. Diferente de las anfetaminas: no actúa como estimulante CNS directo sino que promueve la vigilia vía orexin/histamina. Adoptado por la Fuerza Aérea USA, NASA, ejecutivos Silicon Valley y estudiantes en exámenes. La película "Sin Límites" (2011) ficcionalizó modafinil como NZT-48. Rx en USA pero no controlado — vía telehealth (HoneyHill, Modafinil-Now) es accesible legalmente.',en:'Developed in 1970s by French neurochemist Michel Jouvet and Lafon labs. Approved in France (1986) and USA (1998) for narcolepsy, sleep apnea, and shift work disorder. Different from amphetamines: doesn\'t act as direct CNS stimulant but promotes wakefulness via orexin/histamine. Adopted by US Air Force, NASA, Silicon Valley executives, and exam students. "Limitless" movie (2011) fictionalized modafinil as NZT-48. US Rx but uncontrolled — via telehealth (HoneyHill, Modafinil-Now) is legally accessible.'},
  compounds:'C15H15NO2S · 2-(diphenylmethyl)sulfinyl)acetamide · eugeroico clase única · agonista dopamina indirecto via DAT',
  effect:{es:'Inhibe transportador de dopamina (DAT) y up-regula histamina + orexina = vigilia sin pico euforico ni crash. Vida media 12-15h — una dosis cubre el día. NO produce tolerancia significativa. Mejora memoria de trabajo, atención sostenida, motivación. Efectos secundarios: dolor de cabeza (hidratar), insomnio si se toma tarde, raro Stevens-Johnson syndrome (descontinuar si sarpullido). NO usar diario por meses — ciclar.',en:'Inhibits dopamine transporter (DAT) and up-regulates histamine + orexin = wakefulness without euphoric peak or crash. Half-life 12-15h — one dose covers the day. No significant tolerance. Improves working memory, sustained attention, motivation. Side effects: headache (hydrate), insomnia if taken late, rare Stevens-Johnson syndrome (discontinue if rash). DO NOT use daily for months — cycle.'},
  ingredients:{es:['Modafinil 200mg tablet · genérico (Sun Pharma · Modalert)','Armodafinil 150mg · isómero R · vida media más larga (Sun Pharma · Waklert)','Agua abundante (modafinil deshidrata)','Café con moderación · sinergia OK'],en:['Modafinil 200mg tablet · generic (Sun Pharma · Modalert)','Armodafinil 150mg · R-isomer · longer half-life (Sun Pharma · Waklert)','Abundant water (modafinil dehydrates)','Coffee in moderation · synergy OK']},
  recipe:{es:'Dosis estándar: 100-200mg modafinil al despertar (NO después de las 10am — interfiere sueño). Armodafinil: 75-150mg. Combinar con desayuno proteico para evitar dolor de cabeza. Hidratar 3L de agua durante el día. Si tienes Apple Watch/Oura, notarás resting heart rate sube 5-8 bpm — normal. Ciclar 5-on / 2-off para mantener sensibilidad. NO combinar con anticonceptivos (induce CYP3A4 → reduce eficacia). Tras 12 semanas continuas hacer 2 semanas off.',en:'Standard dose: 100-200mg modafinil upon waking (NOT after 10am — interferes sleep). Armodafinil: 75-150mg. Combine with protein breakfast to avoid headache. Hydrate 3L water during day. With Apple Watch/Oura, resting heart rate goes up 5-8 bpm — normal. Cycle 5-on / 2-off to maintain sensitivity. DO NOT combine with birth control pills (induces CYP3A4 → reduces efficacy). After 12 continuous weeks take 2 weeks off.'},
  sourcing:{
    local:[],
    intl:[
      {name:'HoneyHill Health (telehealth USA)',url:'https://www.honeyhill.health',note:{es:'★ Rx telehealth USA · evaluación + envío',en:'★ telehealth Rx USA · evaluation + shipping'}},
      {name:'AfinilExpress (India direct)',url:'https://afinilexpress.com',note:{es:'genérico Modalert/Waklert Sun Pharma · 10-15d',en:'Sun Pharma generic Modalert/Waklert · 10-15d'}},
      {name:'BuyModa',url:'https://buymoda.org',note:{es:'India directo · revisar legalidad importación PA',en:'India direct · verify PA import legality'}}
    ]
  }
},

{ id:'aniracetam', category:'cognitive',
  name:{es:'Aniracetam · Racetam Familia',en:'Aniracetam · Racetam Family'},
  origin:{es:'Hoffmann-La Roche · Bélgica · 1979',en:'Hoffmann-La Roche · Belgium · 1979'},
  one:{es:'El más estudiado de la familia "racetam" — Piracetam descubrió la categoría 1964.',en:'Most studied in the "racetam" family — Piracetam discovered the category 1964.'},
  story:{es:'En 1964 Corneliu Giurgea (rumano-belga) sintetizó <strong>piracetam</strong> en UCB-Belgium y acuñó el término "nootrópico" (del griego "nous" mente + "trepein" girar). Su criterio para nootrópico: (1) mejora aprendizaje y memoria, (2) protege el cerebro de daño, (3) no es tóxico, (4) no es estimulante CNS. Piracetam abrió una familia de moléculas: aniracetam (1979), oxiracetam (1977), pramiracetam (1979), fenibut, fenotropil. Aniracetam es liposoluble (atraviesa BBB mejor) y tiene componente ansiolítico. Rx en Europa, OTC en Rusia/Asia, gray-market en USA.',en:'In 1964 Corneliu Giurgea (Romanian-Belgian) synthesized <strong>piracetam</strong> at UCB-Belgium and coined the term "nootropic" (Greek "nous" mind + "trepein" turn). His criteria for nootropic: (1) improves learning and memory, (2) protects brain from damage, (3) non-toxic, (4) not a CNS stimulant. Piracetam opened a family of molecules: aniracetam (1979), oxiracetam (1977), pramiracetam (1979), phenibut, phenotropil. Aniracetam is fat-soluble (crosses BBB better) and has anxiolytic component. Rx in Europe, OTC in Russia/Asia, gray-market in US.'},
  compounds:'C12H13NO3 · 1-(4-methoxybenzoyl)-2-pyrrolidinone · clase racetam · modulador AMPA · liposoluble',
  effect:{es:'Modula receptores AMPA (glutamato) y up-regula acetilcolina. Mejora memoria episódica y verbal. Componente ansiolítico — único en la familia racetam. Vida media corta (2-3h) — dosis 2-3 veces al día. Liposoluble: requiere grasa para absorción óptima (combinar con desayuno aceitoso o ghee). Tolerancia mínima. Stack común con CDP-choline (Cognizin 250mg) para sinergia colinérgica.',en:'Modulates AMPA (glutamate) receptors and up-regulates acetylcholine. Improves episodic and verbal memory. Anxiolytic component — unique in racetam family. Short half-life (2-3h) — dose 2-3× daily. Fat-soluble: requires fat for optimal absorption (combine with oily breakfast or ghee). Minimal tolerance. Common stack with CDP-choline (Cognizin 250mg) for cholinergic synergy.'},
  ingredients:{es:['Aniracetam 750mg · 2-3 dosis al día (con grasa)','CDP-Choline (Cognizin) 250-500mg · sinérgico colinérgico','Ghee o aceite MCT · 1 cdita · facilita absorción','Para stack avanzado: agregar piracetam 1.6g por la mañana'],en:['Aniracetam 750mg · 2-3 doses daily (with fat)','CDP-Choline (Cognizin) 250-500mg · cholinergic synergistic','Ghee or MCT oil · 1 tsp · facilitates absorption','For advanced stack: add piracetam 1.6g in morning']},
  recipe:{es:'Aniracetam: 750mg con desayuno (en ghee/MCT) + 750mg con almuerzo. NO después de las 3pm. CDP-choline: 250mg con cada dosis de aniracetam (evita dolor de cabeza colinérgico). Efecto se construye en 1-2 semanas. Ciclar 6 semanas on / 2 off. Si stack avanzado: agregar piracetam 1.6g hidrosoluble por la mañana (loading 4.8g día 1).',en:'Aniracetam: 750mg with breakfast (in ghee/MCT) + 750mg with lunch. NOT after 3pm. CDP-choline: 250mg with each aniracetam dose (prevents cholinergic headache). Effect builds 1-2 weeks. Cycle 6 weeks on / 2 off. Advanced stack: add water-soluble piracetam 1.6g in morning (loading 4.8g day 1).'},
  sourcing:{
    local:[],
    intl:[
      {name:'Nootropics Depot',url:'https://nootropicsdepot.com',note:{es:'★ pruebas terceros · racetams + cofactor stacks · USA',en:'★ third-party tested · racetams + cofactor stacks · USA'}},
      {name:'Cosmic Nootropic',url:'https://cosmicnootropic.com',note:{es:'fenotropil + fenibut rusos · racetams Europeos',en:'Russian phenotropil + phenibut · European racetams'}},
      {name:'Liftmode',url:'https://liftmode.com',note:{es:'racetams + CDP-choline · USA',en:'racetams + CDP-choline · USA'}}
    ]
  }
},

{ id:'metformin', category:'longevity',
  name:{es:'Metformina · La Diabetes Lottery',en:'Metformin · The Diabetes Lottery'},
  origin:{es:'Jean Sterne · París · 1922 sintetizada · 1957 uso clínico',en:'Jean Sterne · Paris · 1922 synthesized · 1957 clinical use'},
  one:{es:'El fármaco diabético que extiende la vida en personas sin diabetes.',en:'The diabetic drug that extends lifespan in people without diabetes.'},
  story:{es:'Derivado sintético de la galega officinalis (lila francesa), planta medieval. Sintetizado en 1922, archivado por descubrimiento de insulina. Re-introducida por Jean Sterne (Francia 1957) para diabetes tipo 2. En 2014 un estudio observacional de la Universidad de Cardiff con 180,000 pacientes diabéticos vs no-diabéticos encontró que los diabéticos en metformina vivieron MÁS que los no-diabéticos sanos. Repetido en múltiples cohortes. Ahora la base del trial TAME (Targeting Aging with Metformin) de Albert Einstein College — 3,000 ancianos no-diabéticos, primer trial de "anti-envejecimiento" aprobado por FDA. Off-label uso popular en biohackers y geriatras.',en:'Synthetic derivative of galega officinalis (French lilac), medieval medicinal plant. Synthesized 1922, archived after insulin discovery. Re-introduced by Jean Sterne (France 1957) for type 2 diabetes. In 2014 a Cardiff University observational study of 180,000 diabetic vs non-diabetic patients found diabetics on metformin lived LONGER than healthy non-diabetics. Repeated in multiple cohorts. Now the basis for Albert Einstein College\'s TAME trial (Targeting Aging with Metformin) — 3,000 non-diabetic elderly, first FDA-approved "anti-aging" trial. Off-label use popular among biohackers and geriatricians.'},
  compounds:'C4H11N5 · 1,1-dimetilbiguanida · activa AMPK · clase biguanida · derivado de galegina',
  effect:{es:'Activa AMPK (sensor de energía celular) → simula estado de restricción calórica sin restringir. Reduce gluconeogénesis hepática. Inhibe complejo I mitocondrial (controvertido — algunos creen es vía + el beneficio, otros vía -). Mejora sensibilidad a insulina. Reduce LDL. Estudios anti-aging in vivo. Efectos secundarios: GI (diarrea, nausea — comenzar dosis baja), B12 absorción reducida (suplementar metilcobalamina 1000mcg). Contraindicada en falla renal severa.',en:'Activates AMPK (cellular energy sensor) → simulates caloric restriction state without restricting. Reduces hepatic gluconeogenesis. Inhibits mitochondrial complex I (controversial — some think this is the + benefit, others the -). Improves insulin sensitivity. Reduces LDL. Anti-aging studies in vivo. Side effects: GI (diarrhea, nausea — start low dose), reduced B12 absorption (supplement 1000mcg methylcobalamin). Contraindicated in severe renal failure.'},
  ingredients:{es:['Metformina HCl 500mg · tablet (Glucophage o genérico)','Metformina extended-release 500mg · mejor tolerancia GI','Vit B12 metilcobalamina 1000mcg · contrarrestar depleción','Tomar con comida principal'],en:['Metformin HCl 500mg · tablet (Glucophage or generic)','Metformin extended-release 500mg · better GI tolerance','Vit B12 methylcobalamin 1000mcg · counter depletion','Take with main meal']},
  recipe:{es:'Off-label longevidad: 500mg con cena × 2 semanas (probar tolerancia), después 500mg dos veces al día (almuerzo + cena), después 1000mg dos veces al día. NUNCA antes de ejercicio intenso o ayuno prolongado — riesgo lactic acidosis. Suplementar B12 metilcobalamina 1000mcg diariamente. Monitorear función renal cada 6 meses. Si planeas embarazo, descontinuar. Requiere Rx en USA — telehealth (Lifeforce, Henry Meds, Marek Health) accesible.',en:'Off-label longevity: 500mg with dinner × 2 weeks (tolerance test), then 500mg twice daily (lunch + dinner), then 1000mg twice daily. NEVER before intense exercise or prolonged fasting — lactic acidosis risk. Supplement B12 methylcobalamin 1000mcg daily. Monitor renal function every 6 months. If pregnancy planned, discontinue. Requires Rx in US — telehealth (Lifeforce, Henry Meds, Marek Health) accessible.'},
  sourcing:{
    local:[
      {name:'Farmacias David (Rx)',url:'#',note:{es:'metformina genérica disponible con receta · ~$5/mes',en:'generic metformin available with prescription · ~$5/mo'}}
    ],
    intl:[
      {name:'Marek Health',url:'https://marekhealth.com',note:{es:'★ telehealth longevity-focused · USA',en:'★ longevity-focused telehealth · USA'}},
      {name:'Lifeforce',url:'https://mylifeforce.com',note:{es:'plataforma longevity con metformin protocolo',en:'longevity platform with metformin protocol'}},
      {name:'Henry Meds',url:'https://henrymeds.com',note:{es:'telehealth USA · metformin Rx · 7-10d',en:'US telehealth · metformin Rx · 7-10d'}}
    ]
  }
},

{ id:'ketamine-therapy', category:'therapy',
  name:{es:'Ketamina · Terapia Clínica',en:'Ketamine · Clinical Therapy'},
  origin:{es:'Calvin Stevens · Parke-Davis · 1962 · re-introducción terapéutica 2000s',en:'Calvin Stevens · Parke-Davis · 1962 · therapeutic re-introduction 2000s'},
  one:{es:'Anestésico de campo de batalla que ahora es el antidepresivo de acción más rápida.',en:'Battlefield anesthetic that\'s now the fastest-acting antidepressant.'},
  story:{es:'Sintetizada en 1962 por Calvin Stevens en Parke-Davis como alternativa más segura al PCP. Aprobada FDA 1970 como anestésico — usada extensivamente en Vietnam como anestésico de campo (no deprime respiración). En los 2000s investigadores notaron que pacientes con depresión severa post-anestesia con ketamina reportaban mejoría inmediata. Estudios en Yale y Hopkins confirmaron: <strong>dosis sub-anestésica (0.5mg/kg)</strong> produce remisión de depresión resistente a tratamiento en horas — vs SSRI que toman 6-8 semanas. FDA aprobó esketamina (spray nasal Spravato, J&J) en 2019. Clínicas de ketamina IV/IM proliferaron — Field Trip, Nue Life, Mindbloom (telehealth con lozenges).',en:'Synthesized in 1962 by Calvin Stevens at Parke-Davis as safer PCP alternative. FDA approved 1970 as anesthetic — used extensively in Vietnam as field anesthetic (doesn\'t depress respiration). In 2000s researchers noticed patients with severe depression post-anesthesia reported immediate improvement. Yale and Hopkins studies confirmed: <strong>sub-anesthetic dose (0.5mg/kg)</strong> produces remission of treatment-resistant depression in hours — vs SSRIs taking 6-8 weeks. FDA approved esketamine (Spravato nasal spray, J&J) in 2019. Ketamine IV/IM clinics proliferated — Field Trip, Nue Life, Mindbloom (telehealth with lozenges).'},
  compounds:'C13H16ClNO · clorhidrato de ketamina · arilciclohexilamina · antagonista NMDA · disociativo',
  effect:{es:'Antagonista NMDA — bloquea glutamato en sinapsis. Induce estado disociativo (los pensamientos se separan del afecto emocional). Up-regula BDNF y sinaptogénesis en 24h post-infusión. Para depresión resistente: 6 sesiones IV (0.5mg/kg en 40 min) sobre 3 semanas + mantenimiento. Para PTSD, ansiedad, adicciones: protocolos similares. Riesgos: posible abuso recreativo (efecto disociativo placentero), daño vesical con uso crónico alto, hipertensión transitoria.',en:'NMDA antagonist — blocks glutamate at synapses. Induces dissociative state (thoughts separate from emotional affect). Up-regulates BDNF and synaptogenesis within 24h post-infusion. For treatment-resistant depression: 6 IV sessions (0.5mg/kg over 40 min) over 3 weeks + maintenance. For PTSD, anxiety, addictions: similar protocols. Risks: potential recreational abuse (pleasurable dissociative effect), bladder damage with chronic high use, transient hypertension.'},
  ingredients:{es:['IV en clínica (Field Trip, Nue Life, Ketamine Wellness Network)','Spravato esketamine nasal · solo Rx clínica certificada','Lozenges sublinguales · Mindbloom telehealth · pacientes en casa','Set + setting controlado, terapeuta de integración'],en:['IV in clinic (Field Trip, Nue Life, Ketamine Wellness Network)','Spravato esketamine nasal · only certified clinic Rx','Sublingual lozenges · Mindbloom telehealth · at-home patients','Set + setting controlled, integration therapist']},
  recipe:{es:'Protocolo clínico: 6 sesiones IV durante 3 semanas. Cada sesión: 0.5mg/kg en infusión de 40 minutos con monitoreo cardiovascular. El paciente experimenta 30-60 min de estado disociativo. Sesión de integración con terapeuta en 24h. Mantenimiento: una sesión cada 4-8 semanas según respuesta. Para Mindbloom telehealth: lozenges sublinguales 200-400mg, sesiones en casa con coach virtual presente. NUNCA mezclar con alcohol o benzodiacepinas — depresión respiratoria.',en:'Clinical protocol: 6 IV sessions over 3 weeks. Each session: 0.5mg/kg in 40-minute infusion with cardiovascular monitoring. Patient experiences 30-60 min dissociative state. Integration session with therapist within 24h. Maintenance: one session every 4-8 weeks per response. For Mindbloom telehealth: 200-400mg sublingual lozenges, at-home sessions with virtual coach present. NEVER mix with alcohol or benzodiazepines — respiratory depression.'},
  sourcing:{
    local:[],
    intl:[
      {name:'Mindbloom (telehealth USA)',url:'https://www.mindbloom.com',note:{es:'★ lozenges en casa · psiquiatra + coach · USA',en:'★ at-home lozenges · psychiatrist + coach · USA'}},
      {name:'Field Trip Health',url:'https://www.fieldtriphealth.com',note:{es:'★ IV en clínica · USA + Canadá + UK',en:'★ IV in clinic · USA + Canada + UK'}},
      {name:'Nue Life',url:'https://www.nue.life',note:{es:'telehealth con lozenges · 6 sesiones programa',en:'telehealth with lozenges · 6-session program'}},
      {name:'Spravato (J&J Pharma)',url:'https://www.spravato.com',note:{es:'esketamine nasal · prescripción especializada FDA',en:'nasal esketamine · specialized FDA prescription'}}
    ]
  }
},

{ id:'rapamycin', category:'longevity',
  name:{es:'Rapamicina · Isla de Pascua',en:'Rapamycin · Easter Island'},
  origin:{es:'Suren Sehgal · Ayerst · Streptomyces hygroscopicus · Rapa Nui 1972',en:'Suren Sehgal · Ayerst · Streptomyces hygroscopicus · Rapa Nui 1972'},
  one:{es:'Encontrada en el suelo de Rapa Nui · ahora el fármaco más prometedor de longevidad humana.',en:'Found in Rapa Nui soil · now the most promising human longevity drug.'},
  story:{es:'En 1964 una expedición canadiense a Isla de Pascua recolectó muestras de suelo. En 1972 Suren Sehgal en Ayerst Research aisló <em>Streptomyces hygroscopicus</em> y un compuesto antifúngico que llamó <strong>rapamicina</strong> (por Rapa Nui). Sehgal guardó cultivos en su congelador casero cuando Ayerst cerró el programa. Décadas después se descubrió que la rapamicina inhibe mTOR — el "thermostato celular" de crecimiento. Aprobada FDA 1999 como inmunosupresor (Rapamune) para trasplantes. En 2009 el estudio ITP (Interventions Testing Program) del NIH demostró que rapamicina extendía vida útil en ratones más que cualquier compuesto probado — incluso comenzando a edad media. Matt Kaeberlein (U Washington) lanzó el Dog Aging Project con rapamicina. El trial PEARL (AgelessRx, 2020-2025) en humanos completó en abril 2025: 5mg/semana × 48 semanas mostró mejoras en composición corporal, dolor y función. Mikhail Blagosklonny propuso desde 2006 que rapamicina pulsátil es la intervención de longevidad más segura para humanos.',en:'In 1964 a Canadian expedition to Easter Island collected soil samples. In 1972 Suren Sehgal at Ayerst Research isolated <em>Streptomyces hygroscopicus</em> and an antifungal compound he called <strong>rapamycin</strong> (after Rapa Nui). Sehgal kept cultures in his home freezer when Ayerst closed the program. Decades later it was discovered rapamycin inhibits mTOR — the cellular "growth thermostat". FDA approved 1999 as immunosuppressant (Rapamune) for transplants. In 2009 the NIH ITP (Interventions Testing Program) showed rapamycin extended lifespan in mice more than any tested compound — even starting in middle age. Matt Kaeberlein (U Washington) launched the Dog Aging Project with rapamycin. The PEARL trial (AgelessRx, 2020-2025) in humans completed April 2025: 5mg/week × 48 weeks showed improvements in body composition, pain and function. Mikhail Blagosklonny proposed since 2006 that pulsatile rapamycin is the safest longevity intervention for humans.'},
  compounds:'C51H79NO13 · sirolimus · macrólido · inhibidor selectivo mTORC1 · alotrópica · vida media 60h',
  effect:{es:'Inhibe selectivamente mTORC1 (mammalian target of rapamycin complex 1) → simula restricción calórica + induce autofagia (limpieza celular). Up-regula mecanismos de reparación. Dosis pulsátil semanal evita los efectos secundarios crónicos del uso diario (inmunosupresión, dislipidemia). Estudios humanos muestran: mejor composición corporal, dolor articular reducido, función inmune T-cell mejorada (paradójico — modulación, no supresión), marcadores epigenéticos más jóvenes. Efectos secundarios pulsátiles: úlceras orales transitorias (mucositis), niveles lipídicos elevados, infecciones leves. NO usar si embarazada, infección activa, cirugía próxima.',en:'Selectively inhibits mTORC1 (mammalian target of rapamycin complex 1) → simulates caloric restriction + induces autophagy (cellular cleanup). Up-regulates repair mechanisms. Weekly pulsatile dose avoids chronic daily side effects (immunosuppression, dyslipidemia). Human studies show: better body composition, reduced joint pain, improved T-cell immune function (paradoxical — modulation, not suppression), younger epigenetic markers. Pulsatile side effects: transient oral ulcers (mucositis), elevated lipid levels, mild infections. DO NOT use if pregnant, active infection, upcoming surgery.'},
  ingredients:{es:['Rapamicina (Sirolimus) 1mg tablet · genérico (Rapamune original)','Dosis pulsátil: 5-8mg una vez por semana (NO diario)','Comer ligero antes — la absorción varía con grasa','Monitoreo médico: lípidos + función renal cada 6 meses'],en:['Rapamycin (Sirolimus) 1mg tablet · generic (Rapamune original)','Pulsatile dose: 5-8mg once weekly (NOT daily)','Eat light beforehand — absorption varies with fat','Medical monitoring: lipids + renal function every 6 months']},
  recipe:{es:'Protocolo Kaeberlein/Blagosklonny: 5-8mg una vez por semana en ayunas. Día consistente (ej domingo por la mañana). Esperar 2h antes de comer grasa. Si aparece úlcera oral (más común en primeras semanas), reducir dosis a 4mg. Si lípidos suben mucho, reducir a 3mg o ciclar (8 semanas on / 4 off). NUNCA combinar con vacunas vivas en ventana de 2 semanas. NO en infección activa. Telehealth Healthspan ($249 inicial + ~$65/mes) o AgelessRx ($65/mes incluido el PEARL protocol original).',en:'Kaeberlein/Blagosklonny protocol: 5-8mg once weekly fasted. Consistent day (e.g. Sunday morning). Wait 2h before eating fat. If oral ulcer appears (more common in first weeks), reduce dose to 4mg. If lipids rise significantly, reduce to 3mg or cycle (8 weeks on / 4 off). NEVER combine with live vaccines in 2-week window. NOT during active infection. Telehealth Healthspan ($249 initial + ~$65/mo) or AgelessRx ($65/mo includes the original PEARL protocol).'},
  sourcing:{
    local:[],
    intl:[
      {name:'AgelessRx',url:'https://agelessrx.com',note:{es:'★ corrió el trial PEARL · $65/mes incluido todo · USA',en:'★ ran the PEARL trial · $65/mo all-in · USA'}},
      {name:'Healthspan',url:'https://gethealthspan.com',note:{es:'telehealth longevity-focused · $249 inicial · Kaeberlein advisor',en:'longevity-focused telehealth · $249 initial · Kaeberlein advisor'}},
      {name:'Marek Health',url:'https://marekhealth.com',note:{es:'paneles completos + rapamicina · USA',en:'comprehensive panels + rapamycin · USA'}},
      {name:'Lifeforce',url:'https://mylifeforce.com',note:{es:'plataforma longevity con protocolo rapamicina',en:'longevity platform with rapamycin protocol'}}
    ]
  }
},

{ id:'spermidine', category:'longevity',
  name:{es:'Espermidina · Inductor de Autofagia',en:'Spermidine · Autophagy Inducer'},
  origin:{es:'Leeuwenhoek 1678 (semen) · Frank Madeo · U Graz · autofagia 2009',en:'Leeuwenhoek 1678 (semen) · Frank Madeo · U Graz · autophagy 2009'},
  one:{es:'La poliamina que activa autofagia sin medicamentos · descubierta en semen 1678.',en:'The polyamine that activates autophagy without drugs · discovered in semen 1678.'},
  story:{es:'Antonie van Leeuwenhoek descubrió cristales de "espermina" en semen humano en 1678 — primer compuesto bioquímico identificado. Su precursor, espermidina, está presente en TODAS las células vivas. Frank Madeo en la Universidad de Graz (Austria) demostró en 2009 que espermidina extiende la vida útil en levaduras, gusanos, moscas y ratones — vía inducción de autofagia (Nobel 2016 Yoshinori Ohsumi). Estudios poblacionales en Italia (Bruneck) y Alemania mostraron que dietas altas en espermidina (germen de trigo, soja fermentada, queso curado, hongos shiitake, brócoli) se correlacionan con menor mortalidad cardiovascular y mejor cognición. La empresa austriaca <strong>The Longevity Labs</strong> (spermidineLIFE) extrae espermidina de germen de trigo. Trial SmartAge (2022, Berlín) con 100 adultos mostró mejora cognitiva. Es uno de los pocos compuestos donde puedes obtenerlo de comida real O suplemento.',en:'Antonie van Leeuwenhoek discovered "spermine" crystals in human semen in 1678 — first identified biochemical compound. Its precursor, spermidine, is present in ALL living cells. Frank Madeo at University of Graz (Austria) demonstrated in 2009 that spermidine extends lifespan in yeast, worms, flies and mice — via autophagy induction (Yoshinori Ohsumi, 2016 Nobel). Population studies in Italy (Bruneck) and Germany showed high-spermidine diets (wheat germ, fermented soy, aged cheese, shiitake mushrooms, broccoli) correlate with lower cardiovascular mortality and better cognition. The Austrian company <strong>The Longevity Labs</strong> (spermidineLIFE) extracts spermidine from wheat germ. SmartAge trial (2022, Berlin) with 100 adults showed cognitive improvement. One of few compounds you can get from real food OR supplement.'},
  compounds:'C7H19N3 · poliamina natural · activa autofagia vía hipusinación de eIF5A · sustrato deacetilasas',
  effect:{es:'Induce autofagia (proceso celular de reciclaje — limpieza de proteínas dañadas y orgánelos). Estabiliza histonas (epigenética). Reduce inflamación. En humanos: mejora función cardiaca, cognición, regeneración celular. Datos epidemiológicos Bruneck Study (Italia): personas en cuartil alto de espermidina vivieron 5.7 años más que cuartil bajo. SmartAge (Berlín): mejora memoria episódica. Activa autofagia a dosis humanas razonables (1-6mg/día), a diferencia de la rapamicina que requiere Rx.',en:'Induces autophagy (cellular recycling — cleanup of damaged proteins and organelles). Stabilizes histones (epigenetics). Reduces inflammation. In humans: improves cardiac function, cognition, cellular regeneration. Bruneck Study epidemiological data (Italy): people in high spermidine quartile lived 5.7 years more than low quartile. SmartAge (Berlin): improves episodic memory. Activates autophagy at reasonable human doses (1-6mg/day), unlike rapamycin which requires Rx.'},
  ingredients:{es:['SpermidineLIFE · 1.2mg cápsulas (germen trigo extracto)','Alternativa alimentaria: 30g germen de trigo crudo/día = ~3mg','Hongos shiitake secos · 5g/día = ~1mg adicional','Natto japonés · 50g = ~3mg (más alto de cualquier alimento)'],en:['SpermidineLIFE · 1.2mg capsules (wheat germ extract)','Food alternative: 30g raw wheat germ/day = ~3mg','Dried shiitake mushrooms · 5g/day = ~1mg additional','Japanese natto · 50g = ~3mg (highest of any food)']},
  recipe:{es:'Vía alimentaria (preferida): 2 cdas de germen de trigo crudo en yogurt griego por la mañana + hongos shiitake en almuerzo + natto si tolera (sabor adquirido). Vía suplemento: SpermidineLIFE 1.2mg cápsula con desayuno. Sin efectos secundarios significativos a dosis fisiológicas. Stack con NMN y resveratrol = "stack Sinclair-Madeo" para autofagia + sirtuinas. Continuo · sin necesidad de ciclar. Mejor con vitamina B12 (espermidina ↑ ↓ B12 levemente).',en:'Food route (preferred): 2 tbsp raw wheat germ in Greek yogurt in morning + shiitake mushrooms at lunch + natto if tolerated (acquired taste). Supplement route: SpermidineLIFE 1.2mg capsule with breakfast. No significant side effects at physiological doses. Stack with NMN and resveratrol = "Sinclair-Madeo stack" for autophagy + sirtuins. Continuous · no cycling needed. Best with vitamin B12 (spermidine ↑ ↓ B12 slightly).'},
  sourcing:{
    local:[
      {name:'Riba Smith David',url:'https://www.ribasmith.com.pa',note:{es:'germen de trigo crudo + natto si llega · alimentario',en:'raw wheat germ + natto if available · food route'}}
    ],
    intl:[
      {name:'spermidineLIFE',url:'https://www.spermidinelife.us',note:{es:'★ extracto germen de trigo Austria · Madeo formula',en:'★ Austrian wheat germ extract · Madeo formula'}},
      {name:'Double Wood Supplements',url:'https://www.doublewoodsupplements.com/products/spermidine',note:{es:'5mg cápsulas más alta concentración',en:'5mg highest-concentration capsules'}},
      {name:'iHerb',url:'https://www.iherb.com/search?kw=spermidine',note:{es:'múltiples marcas · directo PA · 7-14d',en:'multiple brands · direct PA · 7-14d'}}
    ]
  }
},

{ id:'fisetin', category:'longevity',
  name:{es:'Fisetina · Senolítico Natural',en:'Fisetin · Natural Senolytic'},
  origin:{es:'Mayo Clinic · James Kirkland · 2018 · descubierto en fresas',en:'Mayo Clinic · James Kirkland · 2018 · found in strawberries'},
  one:{es:'Flavonol de fresas que mata células zombi · más potente que quercetina.',en:'Strawberry flavonol that kills zombie cells · more potent than quercetin.'},
  story:{es:'Las células senescentes ("zombi") son células viejas que dejaron de dividirse pero siguen secretando inflamación (SASP — senescence-associated secretory phenotype). Acumulan con edad y causan envejecimiento sistémico. James Kirkland (Mayo Clinic) acuñó el término <strong>senolítico</strong> en 2015 — compuestos que matan selectivamente células senescentes. El cocktail original fue Dasatinib (quimio leucemia) + Quercetina. En 2018 el equipo de Kirkland tamizó 10 candidatos y encontró que <strong>fisetina</strong> — flavonol en fresas, manzanas, kiwi — era el más potente. En ratones, extendió vida útil 10-15% incluso comenzando viejos. Mayo Clinic ahora corre múltiples trials humanos: artrosis, fragilidad, Alzheimer, COVID long-haul. <strong>Protocolo Mayo</strong>: 20mg/kg × 2 días consecutivos, una vez al mes (hit-and-run pulsátil — porque senolíticos solo necesitan eliminar las zombis, no acción crónica).',en:'Senescent ("zombie") cells are old cells that stopped dividing but keep secreting inflammation (SASP — senescence-associated secretory phenotype). Accumulate with age and cause systemic aging. James Kirkland (Mayo Clinic) coined <strong>senolytic</strong> in 2015 — compounds that selectively kill senescent cells. Original cocktail was Dasatinib (leukemia chemo) + Quercetin. In 2018 Kirkland\'s team screened 10 candidates and found <strong>fisetin</strong> — flavonol in strawberries, apples, kiwi — was most potent. In mice, extended lifespan 10-15% even starting old. Mayo Clinic now runs multiple human trials: osteoarthritis, frailty, Alzheimer\'s, long COVID. <strong>Mayo protocol</strong>: 20mg/kg × 2 consecutive days, once monthly (hit-and-run pulsatile — because senolytics only need to eliminate zombies, not chronic action).'},
  compounds:'C15H10O6 · 3,3\',4\',7-tetrahidroxiflavona · flavonol natural · senolítico vía Bcl-2 pathway',
  effect:{es:'Inhibe selectivamente Bcl-2/Bcl-xL (proteínas anti-apoptóticas que protegen células senescentes). Las células sanas no dependen de Bcl-2, las zombis sí — por eso es selectivo. Reduce SASP (inflamación crónica de bajo grado). Estudios humanos en marcha. Pulsátil = mínimos efectos secundarios. Vida media corta — necesita dosis altas para alcanzar concentración terapéutica en tejidos. Biodisponibilidad pobre — formulación liposomal/micronizada importa.',en:'Selectively inhibits Bcl-2/Bcl-xL (anti-apoptotic proteins that protect senescent cells). Healthy cells don\'t depend on Bcl-2, zombies do — that\'s why selective. Reduces SASP (chronic low-grade inflammation). Human studies ongoing. Pulsatile = minimal side effects. Short half-life — needs high doses to reach therapeutic tissue concentration. Poor bioavailability — liposomal/micronized formulation matters.'},
  ingredients:{es:['Fisetina 100mg cápsula (Doctor\'s Best · Pure Encapsulations · DoNotAge)','Cuajar con grasa: aceite MCT, aguacate o yema de huevo (liposoluble)','Cálculo de dosis Mayo: 20mg/kg × peso = ej. 70kg × 20 = 1400mg/día','Hidratación: 3L agua durante los 2 días'],en:['Fisetin 100mg capsule (Doctor\'s Best · Pure Encapsulations · DoNotAge)','Pair with fat: MCT oil, avocado, or egg yolk (fat-soluble)','Mayo dose calc: 20mg/kg × weight = e.g. 70kg × 20 = 1400mg/day','Hydration: 3L water during the 2 days']},
  recipe:{es:'Protocolo Mayo (hit-and-run mensual): día 1 y 2 consecutivos, tomar 20mg/kg dividido en 2 dosis con grasa. Persona 70kg = 1400mg total/día = 700mg AM + 700mg PM con MCT o aguacate. Después 28 días sin nada (las zombis tardan en re-acumular). Repetir mensualmente. Stack opcional con quercetina 1g los mismos días (sinergia senolítica original Kirkland). Beneficios visibles típicamente después de 3-4 ciclos: piel mejor, energía, menor dolor articular. Sin efectos secundarios significativos a esta cadencia. NO usar continuamente.',en:'Mayo protocol (monthly hit-and-run): days 1 and 2 consecutive, take 20mg/kg divided in 2 doses with fat. Person 70kg = 1400mg total/day = 700mg AM + 700mg PM with MCT or avocado. Then 28 days nothing (zombies take time to re-accumulate). Repeat monthly. Optional stack with 1g quercetin same days (original Kirkland senolytic synergy). Visible benefits typically after 3-4 cycles: better skin, energy, less joint pain. No significant side effects at this cadence. DO NOT use continuously.'},
  sourcing:{
    local:[],
    intl:[
      {name:'DoNotAge',url:'https://donotage.org/products/pure-fisetin',note:{es:'★ pruebas terceros · cápsulas 200mg dosis alta · UK',en:'★ third-party tested · 200mg high-dose capsules · UK'}},
      {name:'Doctor\'s Best Fisetin (iHerb)',url:'https://www.iherb.com/search?kw=fisetin',note:{es:'100mg estándar · directo PA · 7-14d',en:'100mg standard · direct PA · 7-14d'}},
      {name:'ProHealth Longevity',url:'https://www.prohealthlongevity.com',note:{es:'fisetin micronizada para biodisponibilidad · USA',en:'micronized fisetin for bioavailability · USA'}},
      {name:'Pure Encapsulations',url:'https://www.pureencapsulations.com',note:{es:'farma-grade · disponible iHerb · USA',en:'pharma-grade · available iHerb · USA'}}
    ]
  }
},

{ id:'tirzepatide', category:'mitochondrial',
  name:{es:'Tirzepatida · Dual GLP-1/GIP',en:'Tirzepatide · Dual GLP-1/GIP'},
  origin:{es:'Eli Lilly · 2022 (Mounjaro) · 2023 (Zepbound) · SURMOUNT-5 NEJM mayo 2025',en:'Eli Lilly · 2022 (Mounjaro) · 2023 (Zepbound) · SURMOUNT-5 NEJM May 2025'},
  one:{es:'GLP-1 + GIP en una sola molécula · 22% pérdida de peso · revolución metabólica.',en:'GLP-1 + GIP in one molecule · 22% weight loss · metabolic revolution.'},
  story:{es:'La familia GLP-1 (glucagon-like peptide-1) revolucionó medicina metabólica desde semaglutida (Ozempic/Wegovy, Novo Nordisk 2017-2021). En 2022 Eli Lilly lanzó <strong>tirzepatida</strong> (Mounjaro para diabetes, Zepbound para obesidad 2023) — primer agonista dual de receptores GLP-1 Y GIP (gastric inhibitory polypeptide). El trial SURMOUNT-5 (NEJM mayo 2025) mostró tirzepatida 15mg/semana × 72 semanas = <strong>20.2% pérdida de peso</strong> vs semaglutida 13.7% — superioridad estadísticamente significativa. Para diabetes tipo 2, tirzepatida produjo remisión completa en 51% de pacientes. Efectos secundarios: náusea/vómito (titrar lento), riesgo pancreatitis raro, contraindicado historia familiar carcinoma medular tiroides. Versión compuesta (preparación farmacéutica no-FDA pero legal) disponible vía telehealth: Henry Meds ($349/mes Zepbound real, ~$199/mes compounded), Mochi Health ($79-199/mes según paquete), Future Med, Eden, Mochi.',en:'The GLP-1 family (glucagon-like peptide-1) revolutionized metabolic medicine from semaglutide (Ozempic/Wegovy, Novo Nordisk 2017-2021). In 2022 Eli Lilly launched <strong>tirzepatide</strong> (Mounjaro for diabetes, Zepbound for obesity 2023) — first dual agonist of GLP-1 AND GIP (gastric inhibitory polypeptide) receptors. The SURMOUNT-5 trial (NEJM May 2025) showed tirzepatide 15mg/week × 72 weeks = <strong>20.2% weight loss</strong> vs semaglutide 13.7% — statistically significant superiority. For type 2 diabetes, tirzepatide produced complete remission in 51% of patients. Side effects: nausea/vomiting (titrate slow), rare pancreatitis risk, contraindicated family history of medullary thyroid carcinoma. Compounded version (pharmacy-prepared non-FDA but legal) available via telehealth: Henry Meds ($349/mo real Zepbound, ~$199/mo compounded), Mochi Health ($79-199/mo per package), Future Med, Eden, Mochi.'},
  compounds:'C225H348N48O68 · péptido sintético 39 aa · dual GLP-1R + GIPR agonista · vida media ~5 días',
  effect:{es:'Activa GLP-1R + GIPR → retrasa vaciado gástrico (saciedad temprana), reduce apetito hipotalámico, mejora sensibilidad a insulina, estimula secreción de insulina dependiente de glucosa (NO causa hipoglicemia espontánea como sulfonilureas). Reduce grasa visceral preferentemente. Mejora hígado graso (NASH). Reduce LDL e inflamación cardiovascular. Estudios cardiovasculares en marcha (SURPASS-CVOT) — primera lectura 2026 Q4. Efectos secundarios: náusea (40%) y vómito si titulación rápida — empezar 2.5mg y subir mensualmente. Pancreatitis muy rara. Pérdida muscular (~25-40% del peso perdido es muscular) — combinar con proteína 1.6-2g/kg + resistencia.',en:'Activates GLP-1R + GIPR → delays gastric emptying (early satiety), reduces hypothalamic appetite, improves insulin sensitivity, stimulates glucose-dependent insulin secretion (does NOT cause spontaneous hypoglycemia like sulfonylureas). Reduces visceral fat preferentially. Improves fatty liver (NASH). Reduces LDL and cardiovascular inflammation. Cardiovascular studies ongoing (SURPASS-CVOT) — first readout 2026 Q4. Side effects: nausea (40%) and vomiting if titration rapid — start 2.5mg and increase monthly. Pancreatitis very rare. Muscle loss (~25-40% of weight lost is muscle) — combine with protein 1.6-2g/kg + resistance training.'},
  ingredients:{es:['Zepbound · plumas semanales (FDA-approved Lilly · $349-549/mes telehealth)','Compounded tirzepatide · vial multidosis · $199-249/mes','Jeringa BD insulin 0.5cc/8mm para dosis precisa','Hielera para almacenamiento (refrigeración 2-8°C requerida)'],en:['Zepbound · weekly pens (FDA-approved Lilly · $349-549/mo telehealth)','Compounded tirzepatide · multi-dose vial · $199-249/mo','BD insulin 0.5cc/8mm syringe for precise dosing','Cooler for storage (refrigeration 2-8°C required)']},
  recipe:{es:'Titrar lentamente para minimizar náusea: 2.5mg/semana × 4 semanas → 5mg × 4 semanas → 7.5mg × 4 → 10mg × 4 → 12.5mg → mantenimiento 15mg semanal. Inyección subcutánea (abdomen, muslo, brazo) misma día cada semana (ej. sábado AM). Rotar sitio. Proteína 1.6-2g/kg + resistencia 3x/semana CRÍTICO para preservar músculo. Hidratación 3L/día. Si náusea: comer menos volumen, más frecuente, evitar grasa pesada. Si plateau: aumentar dosis o cambiar a semaglutida (rotar agentes). NO descontinuar abruptamente — recuperación de peso ~2/3 del perdido. Estrategia: mantenimiento dosis baja (2.5-5mg) post-pérdida.',en:'Titrate slowly to minimize nausea: 2.5mg/week × 4 weeks → 5mg × 4 weeks → 7.5mg × 4 → 10mg × 4 → 12.5mg → maintenance 15mg weekly. Subcutaneous injection (abdomen, thigh, arm) same day each week (e.g. Saturday AM). Rotate sites. Protein 1.6-2g/kg + resistance 3x/week CRITICAL to preserve muscle. Hydration 3L/day. If nausea: eat less volume, more frequent, avoid heavy fat. If plateau: increase dose or switch to semaglutide (rotate agents). DO NOT discontinue abruptly — weight regain ~2/3 of loss. Strategy: low-dose maintenance (2.5-5mg) post-loss.'},
  sourcing:{
    local:[],
    intl:[
      {name:'Henry Meds',url:'https://henrymeds.com',note:{es:'★ compounded tirzepatide $349/mes incluye médico · USA',en:'★ compounded tirzepatide $349/mo includes physician · USA'}},
      {name:'Mochi Health',url:'https://joinmochi.com',note:{es:'★ telehealth GLP-1 desde $79/mes (compounded más barato del mercado) · USA',en:'★ telehealth GLP-1 from $79/mo (cheapest compounded on market) · USA'}},
      {name:'Eden',url:'https://www.tryeden.com',note:{es:'compounded tirzepatide + GLP-1 + supervisión · USA',en:'compounded tirzepatide + GLP-1 + supervision · USA'}},
      {name:'Lifeforce',url:'https://mylifeforce.com',note:{es:'tirzepatide oficial con paneles longevity · USA',en:'official tirzepatide with longevity panels · USA'}},
      {name:'LillyDirect Zepbound',url:'https://lillydirect.com',note:{es:'directo Lilly · USA · plumas FDA-approved oficiales',en:'direct Lilly · USA · official FDA-approved pens'}}
    ]
  }
},

{ id:'ldn-low-dose-naltrexone', category:'therapy',
  name:{es:'LDN · Naltrexona Baja Dosis',en:'LDN · Low Dose Naltrexone'},
  origin:{es:'Bernard Bihari · NYC · 1985 · pacientes VIH y autoinmunes',en:'Bernard Bihari · NYC · 1985 · HIV and autoimmune patients'},
  one:{es:'A 1/10 dosis estándar, naltrexona modula el sistema inmune en lugar de bloquear opiáceos.',en:'At 1/10 standard dose, naltrexone modulates immune system instead of blocking opioids.'},
  story:{es:'Naltrexona fue aprobada FDA 1984 para adicción al opiáceos a 50mg/día. En 1985 el psiquiatra neoyorquino <strong>Bernard Bihari</strong> notó que a dosis MUY bajas (1.5-4.5mg en la noche) producía efectos opuestos: en lugar de bloquear opiáceos, los pacientes reportaban más energía, mejor humor, y — sorprendentemente — sus enfermedades autoinmunes mejoraban. Bihari trataba pacientes VIH y descubrió que LDN mantenía estables sus CD4 counts. Después extendió uso a EM (esclerosis múltiple), Crohn, fibromialgia, Hashimoto, lupus, cáncer. Falleció 2010 sin trial randomizado grande, pero <strong>LDN Research Trust</strong> (UK) ahora coordina red global de prescribers (1,000+). Trials pequeños han confirmado eficacia en fibromialgia (Stanford 2013), Crohn (2007), EM (2010). El mecanismo es paradójico: la dosis baja causa bloqueo BREVE de receptores opioides → cuerpo aumenta producción de endorfinas → cuando naltrexona se metaboliza (vida media 4h), las endorfinas elevadas modulan sistema inmune.',en:'Naltrexone was FDA approved 1984 for opioid addiction at 50mg/day. In 1985 New York psychiatrist <strong>Bernard Bihari</strong> noticed at VERY low doses (1.5-4.5mg at night) it produced opposite effects: instead of blocking opioids, patients reported more energy, better mood, and — surprisingly — their autoimmune diseases improved. Bihari was treating HIV patients and discovered LDN kept their CD4 counts stable. Then extended use to MS (multiple sclerosis), Crohn\'s, fibromyalgia, Hashimoto, lupus, cancer. Died 2010 without large randomized trial, but <strong>LDN Research Trust</strong> (UK) now coordinates global prescriber network (1,000+). Small trials have confirmed efficacy in fibromyalgia (Stanford 2013), Crohn\'s (2007), MS (2010). Mechanism is paradoxical: low dose causes BRIEF opioid receptor blockade → body increases endorphin production → when naltrexone metabolizes (4h half-life), elevated endorphins modulate immune system.'},
  compounds:'C20H23NO4 · clorhidrato de naltrexona · antagonista opioide · dosis baja (1.5-4.5mg) vs estándar (50mg)',
  effect:{es:'Mecanismo principal: bloqueo BREVE (3-4h) de receptores opioides μ → rebote endorfinas (β-endorfina + met-encefalina) hasta 300% basal por 18-20h post-dosis. Endorfinas elevadas modulan células T, reducen TNF-α, IL-6, normalizan Th17/Treg balance. Secundario: antagonismo TLR4 en microglía → reduce inflamación neuroinmune. Efectos clínicos reportados: reducción dolor crónico (fibromialgia), remisión Crohn, frenar progresión EM, reducción síntomas long-COVID (uso reciente 2023+), mejor humor. Efectos secundarios mínimos: sueños vívidos primeras semanas (dosis nocturna), insomnio transitorio. NO usar si paciente toma opiáceos para dolor (bloquea analgesia). NO mezclar con tramadol, codeína.',en:'Primary mechanism: BRIEF (3-4h) blockade of μ-opioid receptors → endorphin rebound (β-endorphin + met-enkephalin) up to 300% baseline for 18-20h post-dose. Elevated endorphins modulate T-cells, reduce TNF-α, IL-6, normalize Th17/Treg balance. Secondary: TLR4 antagonism on microglia → reduces neuroinflammation. Reported clinical effects: chronic pain reduction (fibromyalgia), Crohn\'s remission, MS progression slowed, long-COVID symptom reduction (recent use 2023+), better mood. Minimal side effects: vivid dreams first weeks (nighttime dose), transient insomnia. DO NOT use if patient takes opioids for pain (blocks analgesia). DO NOT mix with tramadol, codeine.'},
  ingredients:{es:['Naltrexona compounded 4.5mg cápsula (farmacia compounding LDN-friendly)','Comenzar 1.5mg primera semana, subir lentamente','Tomar a las 9-10pm (rebote endorfinas pico durante sueño)','Mantener mínimo 3-6 meses para evaluar respuesta'],en:['Naltrexone compounded 4.5mg capsule (LDN-friendly compounding pharmacy)','Start 1.5mg first week, increase slowly','Take 9-10pm (endorphin rebound peaks during sleep)','Maintain minimum 3-6 months to evaluate response']},
  recipe:{es:'Titrar para evitar sueños vívidos intensos: 1.5mg × 1-2 semanas → 3mg × 1-2 semanas → 4.5mg mantenimiento. Tomar 9-10pm. NO tomar opiáceos las 12h antes/después. Si insomnio: cambiar a tomar mañana (efecto similar). Efecto se construye lentamente 2-3 meses. Si autoinmune: chequear marcadores (CRP, anti-TPO, etc) a los 6 meses. AgelessRx ($25/mes) es la opción más barata telehealth USA con prescriber LDN-experto. LDN Research Trust mantiene mapa global de doctores. Para Crohn y EM dosis pueden subir a 6mg.',en:'Titrate to avoid intense vivid dreams: 1.5mg × 1-2 weeks → 3mg × 1-2 weeks → 4.5mg maintenance. Take 9-10pm. DO NOT take opioids 12h before/after. If insomnia: switch to morning (similar effect). Effect builds slowly 2-3 months. If autoimmune: check markers (CRP, anti-TPO, etc) at 6 months. AgelessRx ($25/mo) is cheapest US telehealth option with LDN-expert prescriber. LDN Research Trust maintains global doctor map. For Crohn\'s and MS doses can go up to 6mg.'},
  sourcing:{
    local:[],
    intl:[
      {name:'AgelessRx LDN',url:'https://agelessrx.com/low-dose-naltrexone',note:{es:'★ $25/mes telehealth + compounded · USA (más barato)',en:'★ $25/mo telehealth + compounded · USA (cheapest)'}},
      {name:'LDN Research Trust',url:'https://ldnresearchtrust.org',note:{es:'★ red global médicos · directorio + comunidad pacientes · UK',en:'★ global doctor network · directory + patient community · UK'}},
      {name:'Belmar Pharmacy',url:'https://www.belmarpharmacy.com',note:{es:'compounded LDN · histórica Bihari · USA',en:'compounded LDN · historic Bihari · USA'}},
      {name:'Skip\'s Pharmacy',url:'https://skipsrxonline.com',note:{es:'compounded LDN especialista · USA',en:'specialist compounded LDN · USA'}}
    ]
  }
},

{ id:'tianeptine', category:'cognitive',
  name:{es:'Tianeptina · El Antidepresivo Atípico',en:'Tianeptine · The Atypical Antidepressant'},
  origin:{es:'Servier · Francia · 1989 (Stablon · Coaxil)',en:'Servier · France · 1989 (Stablon · Coaxil)'},
  one:{es:'Antidepresivo que reduce serotonina en vez de aumentarla · agonista μ-opioide oculto.',en:'Antidepressant that reduces serotonin instead of raising it · hidden μ-opioid agonist.'},
  story:{es:'Sintetizada por Servier (Francia) en 1989 como antidepresivo atípico — comercializada como Stablon en Francia, Coaxil en Europa del Este, ampliamente prescrita en Rusia, Hungría, América Latina (algunos países). El mecanismo originalmente propuesto era un "enhancer de recaptación de serotonina" (opuesto de SSRI) — una rareza en farmacología. En 2014 investigadores de Wayne State y Florida descubrieron el secreto: tianeptina y su metabolito MC5 son <strong>agonistas selectivos del receptor μ-opioide</strong> — pero a dosis terapéuticas (12.5mg TID) no produce euforia opiácea, sino acción antidepresiva limpia con perfil único de glutamato/AMPA. Reduce LTD y restaura plasticidad sináptica hipocampal en depresión crónica. Trials demostraron eficacia equivalente a SSRI sin efectos sexuales/sedativos. NO aprobada FDA en USA — un riesgo serio: ha sido objeto de abuso a dosis MUY altas (200mg+) por efecto opioide (apodada "gas station heroin" en USA — vendida en gasolineras como "Tianna Red" hasta ban). A dosis terapéuticas en supervisión: seguro, único. Banned o restricted en Rusia 2018, Lituania, varios estados USA.',en:'Synthesized by Servier (France) in 1989 as atypical antidepressant — marketed as Stablon in France, Coaxil in Eastern Europe, widely prescribed in Russia, Hungary, Latin America (some countries). The originally proposed mechanism was a "serotonin reuptake enhancer" (opposite of SSRIs) — a pharmacological rarity. In 2014 Wayne State and Florida researchers discovered the secret: tianeptine and its metabolite MC5 are <strong>selective μ-opioid receptor agonists</strong> — but at therapeutic doses (12.5mg TID) it doesn\'t produce opioid euphoria, but rather clean antidepressant action with unique glutamate/AMPA profile. Reduces LTD and restores hippocampal synaptic plasticity in chronic depression. Trials demonstrated efficacy equivalent to SSRIs without sexual/sedating side effects. NOT FDA-approved in USA — a serious risk: it has been abused at VERY high doses (200mg+) for opioid effect (nicknamed "gas station heroin" in USA — sold in gas stations as "Tianna Red" until ban). At therapeutic doses under supervision: safe, unique. Banned or restricted in Russia 2018, Lithuania, several US states.'},
  compounds:'C21H25ClN2O4S · sulfato sódico (Stablon) · μ-opioid agonist atípico · modulador AMPA/NMDA · pro-BDNF',
  effect:{es:'Mecanismo único: agonista parcial μ-opioide (Ki ~383nM — débil pero suficiente a dosis terapéuticas) + modulación AMPA/NMDA + up-regulación BDNF en hipocampo. Restaura plasticidad sináptica perdida en depresión crónica (TCA y SSRI también lo hacen — pero tianeptina vía única). Efecto rápido (1-2 semanas vs 6-8 SSRI). Sin efectos sexuales (vs SSRI 30-70% disfunción). Sin sedación significativa. Sin aumento de peso. Vida media corta (3h) — TID dosis 12.5mg × 3. PELIGRO REAL: a dosis altas (75mg+) produce euforia opiácea, dependencia física, síndrome de abstinencia opiácea. Por eso banned en algunos países. Adherirse estrictamente a 12.5mg TID = seguro. NUNCA combinar con opiáceos, benzodiacepinas, alcohol.',en:'Unique mechanism: partial μ-opioid agonist (Ki ~383nM — weak but sufficient at therapeutic doses) + AMPA/NMDA modulation + BDNF upregulation in hippocampus. Restores synaptic plasticity lost in chronic depression (TCAs and SSRIs also do this — but tianeptine via unique route). Fast effect (1-2 weeks vs 6-8 SSRI). No sexual side effects (vs SSRI 30-70% dysfunction). No significant sedation. No weight gain. Short half-life (3h) — TID 12.5mg × 3. REAL DANGER: at high doses (75mg+) produces opioid euphoria, physical dependence, opioid withdrawal syndrome. That\'s why banned in some countries. Strict adherence to 12.5mg TID = safe. NEVER combine with opioids, benzodiazepines, alcohol.'},
  ingredients:{es:['Stablon 12.5mg tabletas (Servier · Francia origen)','Coaxil 12.5mg (versión Europa Este · genérico)','Importante: vigilar dosis · NO exceder 37.5mg/día','Si suspende: titrar gradualmente · 1 tableta menos cada 3 días'],en:['Stablon 12.5mg tablets (Servier · French origin)','Coaxil 12.5mg (Eastern European version · generic)','Critical: monitor dose · DO NOT exceed 37.5mg/day','If discontinuing: gradual taper · 1 tablet less every 3 days']},
  recipe:{es:'Dosis terapéutica estándar: 12.5mg tres veces al día (mañana, mediodía, tarde). NUNCA antes de dormir (puede activar). NUNCA exceder 37.5mg/día. Efecto inicial 1-2 semanas, completo a 4-6 semanas. Sin restricciones dietéticas. Si necesita descontinuar: reducir 12.5mg cada 3-5 días sobre 2 semanas (NO abrupto — síndrome de abstinencia incluso a dosis terapéuticas crónicas). Acceso vía: Francia/España con Rx (más fácil), México/Argentina (Coaxil OTC en algunos lugares), telehealth europea limitada. NO disponible USA legalmente — riesgo legal importación.',en:'Standard therapeutic dose: 12.5mg three times daily (morning, midday, afternoon). NEVER before sleep (can activate). NEVER exceed 37.5mg/day. Initial effect 1-2 weeks, full at 4-6 weeks. No dietary restrictions. If discontinuation needed: reduce 12.5mg every 3-5 days over 2 weeks (NOT abrupt — withdrawal syndrome even at chronic therapeutic doses). Access via: France/Spain with Rx (easiest), Mexico/Argentina (Coaxil OTC in some places), limited European telehealth. NOT legally available USA — legal risk on import.'},
  sourcing:{
    local:[],
    intl:[
      {name:'Servier Stablon (Francia · Rx)',url:'https://www.servier.com',note:{es:'★ Rx en Francia · acceso vía teleconsulta francesa',en:'★ Rx in France · access via French teleconsultation'}},
      {name:'Pharmacy Mexico (Coaxil)',url:'https://www.farmaciasguadalajara.com',note:{es:'México · disponible en farmacias mayores · revisar Rx local',en:'Mexico · available at major pharmacies · check local Rx'}},
      {name:'Reddit r/tianeptine',url:'https://www.reddit.com/r/tianeptine',note:{es:'comunidad uso responsable · NO endorse vendors gris',en:'responsible-use community · DO NOT endorse gray vendors'}}
    ]
  }
},

{ id:'berberine', category:'longevity',
  name:{es:'Berberina · Metformina Natural',en:'Berberine · Nature\'s Metformin'},
  origin:{es:'Coptis chinensis · Berberis vulgaris · MTC + Ayurveda · 3000 años',en:'Coptis chinensis · Berberis vulgaris · TCM + Ayurveda · 3000 years'},
  one:{es:'Alcaloide amarillo de raíz de uva de Oregón · activa AMPK como metformina sin Rx.',en:'Yellow alkaloid from Oregon grape root · activates AMPK like metformin without Rx.'},
  story:{es:'Berberina es un alcaloide isoquinolina amarillo brillante encontrado en raíces de <em>Berberis</em> (uva de Oregón, ágracejo), <em>Coptis chinensis</em> (huang lian — flor de oro china), <em>Hydrastis canadensis</em> (goldenseal nativo americano), y <em>Phellodendron amurense</em> (huang bai). En Medicina Tradicional China se usa hace 3000 años para diarrea, infecciones, diabetes ("xiao ke" — sed excesiva). En Ayurveda se usa en formula Triphala. La ciencia moderna confirmó: <strong>berberina activa AMPK</strong> (el mismo sensor energético que metformina) → reduce glucosa, mejora lípidos, induce autofagia, anti-inflamatorio. Multiples meta-análisis muestran eficacia comparable a metformina en diabetes tipo 2 (HbA1c reducción 0.7-1.2%). Bonus: <strong>actúa sobre microbioma</strong> — reduce bacterias patógenas, modula AMPs intestinales. El compuesto avanzado <strong>HTD1801 (berberine ursodeoxycholate)</strong> de HighTide Therapeutics completó trial Fase 3 vs metformina en 2025 — comparable eficacia con perfil GI superior. Disponible OTC, $20/mes.',en:'Berberine is a bright yellow isoquinoline alkaloid found in roots of <em>Berberis</em> (Oregon grape, barberry), <em>Coptis chinensis</em> (huang lian — Chinese goldthread), <em>Hydrastis canadensis</em> (Native American goldenseal), and <em>Phellodendron amurense</em> (huang bai). In Traditional Chinese Medicine used 3000 years for diarrhea, infections, diabetes ("xiao ke" — excessive thirst). In Ayurveda used in Triphala formula. Modern science confirmed: <strong>berberine activates AMPK</strong> (same energy sensor as metformin) → reduces glucose, improves lipids, induces autophagy, anti-inflammatory. Multiple meta-analyses show comparable efficacy to metformin in type 2 diabetes (HbA1c reduction 0.7-1.2%). Bonus: <strong>acts on microbiome</strong> — reduces pathogenic bacteria, modulates intestinal AMPs. Advanced compound <strong>HTD1801 (berberine ursodeoxycholate)</strong> from HighTide Therapeutics completed Phase 3 trial vs metformin in 2025 — comparable efficacy with superior GI profile. Available OTC, $20/mo.'},
  compounds:'C20H18NO4 · alcaloide isoquinolina · activa AMPK · inhibidor PCSK9 · vida media 4-6h',
  effect:{es:'Mecanismo principal: activación AMPK (no compite con metformina — vía complementaria). Inhibe PCSK9 → reduce LDL 20-25% (similar a estatinas suaves). Activa adiponectina. Reduce glucosa en ayunas 10-25%. Mejora HbA1c 0.7-1.2% en diabéticos. Inhibe inflamación intestinal vía NF-κB. Antimicrobiano frente a SIBO, H. pylori, Candida. Biodisponibilidad pobre (~0.5%) — formulaciones liposomales/dihidroberberina/HTD1801 son superiores. Efectos secundarios: diarrea/cólicos (dosis-dependiente), interacciones con CYP3A4 (precaución con estatinas, ciclosporina). NO durante embarazo o lactancia. Pruebas terceros importantes — algunos productos contaminados con metales pesados.',en:'Primary mechanism: AMPK activation (doesn\'t compete with metformin — complementary pathway). Inhibits PCSK9 → reduces LDL 20-25% (similar to mild statins). Activates adiponectin. Reduces fasting glucose 10-25%. Improves HbA1c 0.7-1.2% in diabetics. Inhibits intestinal inflammation via NF-κB. Antimicrobial against SIBO, H. pylori, Candida. Poor bioavailability (~0.5%) — liposomal/dihydroberberine/HTD1801 formulations are superior. Side effects: diarrhea/cramping (dose-dependent), CYP3A4 interactions (caution with statins, cyclosporine). NOT during pregnancy or lactation. Third-party testing important — some products contaminated with heavy metals.'},
  ingredients:{es:['Berberina HCl 500mg cápsula (Thorne · Pure Encapsulations · California Gold)','Dihidroberberina 100mg (formulación 5x más biodisponible — GlucoVantage)','Tomar con comidas grasas — mejora absorción','Stack con ácido alfa-lipoico 600mg + cromo picolinato 200mcg'],en:['Berberine HCl 500mg capsule (Thorne · Pure Encapsulations · California Gold)','Dihydroberberine 100mg (5x more bioavailable formulation — GlucoVantage)','Take with fatty meals — improves absorption','Stack with alpha-lipoic acid 600mg + chromium picolinate 200mcg']},
  recipe:{es:'Dosis estándar: 500mg × 3 veces al día con comidas (vida media corta). O dihidroberberina 100mg × 2 veces al día (más práctico). Comenzar con 500mg × 1 para tolerar GI. Si SIBO o disbiosis: 1500mg total dividido × 4-8 semanas, después mantener 500-1000mg/día. Para diabetes/prediabetes: monitor glucosa 2-3 meses (HbA1c). Para lípidos: panel a 3 meses. Stack tradicional MTC: huang lian (berberina) + xiao chai hu tang (escutelaria) para inflamación. Discontinuar 2 semanas antes de cirugía mayor. NO con anticoagulantes sin médico.',en:'Standard dose: 500mg × 3 daily with meals (short half-life). Or dihydroberberine 100mg × 2 daily (more practical). Start with 500mg × 1 to tolerate GI. If SIBO or dysbiosis: 1500mg total divided × 4-8 weeks, then maintain 500-1000mg/day. For diabetes/prediabetes: monitor glucose 2-3 months (HbA1c). For lipids: panel at 3 months. Traditional TCM stack: huang lian (berberine) + xiao chai hu tang (skullcap) for inflammation. Discontinue 2 weeks before major surgery. NOT with anticoagulants without physician.'},
  sourcing:{
    local:[
      {name:'Riba Smith David',url:'https://www.ribasmith.com.pa',note:{es:'cápsulas básicas berberina · marcas USA importadas',en:'basic berberine capsules · imported US brands'}}
    ],
    intl:[
      {name:'Thorne Berberine 500mg',url:'https://www.thorne.com',note:{es:'★ pruebas terceros · médicos-grade · USA · iHerb directo',en:'★ third-party tested · physician-grade · USA · iHerb direct'}},
      {name:'GlucoVantage Dihydroberberine',url:'https://nnbnutrition.com/glucovantage',note:{es:'★ 5x más biodisponible que berberina HCl · USA',en:'★ 5x more bioavailable than berberine HCl · USA'}},
      {name:'iHerb California Gold',url:'https://www.iherb.com/search?kw=berberine',note:{es:'múltiples marcas tested · directo PA · más barato',en:'multiple tested brands · direct PA · cheapest'}},
      {name:'Designs for Health',url:'https://www.designsforhealth.com',note:{es:'BerbEvail formula concentrada · practitioner-grade',en:'BerbEvail concentrated formula · practitioner-grade'}}
    ]
  }
},

{ id:'selegiline', category:'cognitive',
  name:{es:'Selegilina · MAO-B Selectivo',en:'Selegiline · Selective MAO-B'},
  origin:{es:'József Knoll · Hungría · 1962 · Deprenyl/Jumex',en:'József Knoll · Hungary · 1962 · Deprenyl/Jumex'},
  one:{es:'Geniales húngaros otra vez · inhibidor MAO-B que protege dopamina y extiende vida.',en:'Hungarian geniuses again · MAO-B inhibitor that protects dopamine and extends life.'},
  story:{es:'En 1962 el farmacólogo húngaro <strong>József Knoll</strong> en Semmelweis University sintetizó <strong>(-)-deprenyl</strong> (selegilina) — primer inhibidor irreversible <em>selectivo</em> de MAO-B (monoamino oxidasa B). Diferente de MAOI no-selectivos (que requieren dieta sin tiramina o causan crisis hipertensiva), selegilina a dosis terapéutica (5-10mg) inhibe casi solo MAO-B, dejando MAO-A intacta. MAO-B degrada dopamina y feniletilamina (PEA) específicamente — al inhibirla, preserva dopamina cerebral. Knoll demostró en 1989 que <strong>selegilina extiende vida útil de ratas 36%</strong> — el primer estudio rigoroso de extensión de vida con fármaco. Aprobada en Hungría 1977, FDA 1989 para Parkinson (retrasa progresión). En 2006 aprobada como parche EMSAM para depresión. Knoll vio selegilina como <strong>"compuesto enhancer"</strong> que mejora "drive" psicomotor — vinculado a longevidad. Estudios en perros (DGP — Anipryl FDA 1998) muestran reducir demencia canina. Linaje magnífico: Knoll fue parte de la generación de "marcianos húngaros" — von Neumann, Wigner, Szilárd, Szent-Györgyi, Teller — todos del mismo gymnasium Budapest.',en:'In 1962 Hungarian pharmacologist <strong>József Knoll</strong> at Semmelweis University synthesized <strong>(-)-deprenyl</strong> (selegiline) — first irreversible <em>selective</em> inhibitor of MAO-B (monoamine oxidase B). Different from non-selective MAOIs (which require tyramine-free diet or cause hypertensive crisis), selegiline at therapeutic dose (5-10mg) almost exclusively inhibits MAO-B, leaving MAO-A intact. MAO-B specifically degrades dopamine and phenylethylamine (PEA) — by inhibiting it, preserves brain dopamine. Knoll demonstrated in 1989 that <strong>selegiline extends rat lifespan 36%</strong> — the first rigorous lifespan extension study with a drug. Approved in Hungary 1977, FDA 1989 for Parkinson\'s (slows progression). In 2006 approved as EMSAM patch for depression. Knoll saw selegiline as a <strong>"enhancer compound"</strong> that improves psychomotor "drive" — linked to longevity. Canine studies (DGP — Anipryl FDA 1998) show reducing dog dementia. Magnificent lineage: Knoll was part of generation of "Hungarian Martians" — von Neumann, Wigner, Szilárd, Szent-Györgyi, Teller — all from same Budapest gymnasium.'},
  compounds:'C13H17N · (R)-(-)-N,α-dimethyl-N-2-propynylphenethylamine · MAO-B inhibidor irreversible',
  effect:{es:'Inhibición irreversible selectiva MAO-B (a dosis ≤10mg/día — sobre 20mg pierde selectividad). Preserva dopamina, feniletilamina (PEA — "neurotrasmisor del enamoramiento"), y norepinefrina. Metaboliza a (-)-metanfetamina y (-)-anfetamina (formas inactivas, no eufóricas como sus enantiómeros (+)). Neuroprotector: estimula SOD y catalasa, reduce radicales libres en sustancia nigra, induce GDNF/BDNF. Knoll: "Para mantener la capacidad de drive psicomotor — la voluntad de actuar — selegilina sustenta la vida". Estudios humanos: trial DATATOP demostró retraso de necesidad de levodopa en Parkinson temprano. EMSAM (parche 6/9/12mg) para depresión mayor. Off-label longevidad/cognición: 1-5mg/día. NUNCA combinar con SSRI/SNRI/MDMA/dextrometorfano (sx serotoninérgico).',en:'Selective irreversible MAO-B inhibition (at doses ≤10mg/day — above 20mg loses selectivity). Preserves dopamine, phenylethylamine (PEA — "infatuation neurotransmitter"), and norepinephrine. Metabolizes to (-)-methamphetamine and (-)-amphetamine (inactive forms, not euphoric like their (+) enantiomers). Neuroprotective: stimulates SOD and catalase, reduces free radicals in substantia nigra, induces GDNF/BDNF. Knoll: "To maintain psychomotor drive capacity — the will to act — selegiline sustains life". Human studies: DATATOP trial demonstrated delay of levodopa need in early Parkinson\'s. EMSAM (6/9/12mg patch) for major depression. Off-label longevity/cognition: 1-5mg/day. NEVER combine with SSRI/SNRI/MDMA/dextromethorphan (serotonin syndrome).'},
  ingredients:{es:['Selegilina 5mg tabletas (Jumex de Hungría · genéricos)','Parche EMSAM 6mg/24h (transdermal · evita primer paso hepático)','Dosis longevidad off-label: 1mg × 2 días/semana (protocolo Knoll en vejez)','NO mezclar con: SSRI, SNRI, tramadol, MDMA, DXM'],en:['Selegiline 5mg tablets (Jumex from Hungary · generics)','EMSAM patch 6mg/24h (transdermal · bypasses hepatic first pass)','Off-label longevity dose: 1mg × 2 days/week (Knoll protocol for elderly)','DO NOT mix with: SSRIs, SNRIs, tramadol, MDMA, DXM']},
  recipe:{es:'Para Parkinson: 5mg × 2/día (mañana + mediodía — NO en la tarde, activante). Para depresión refractaria: parche EMSAM 6mg/24h (sin restricción tiramina). Off-label longevidad-Knoll: 1mg/día Lunes-Miércoles-Viernes (3x/semana) edad 40-60; 2.5mg MWF edad 60-70; 5mg MWF edad 70+. Para dopamina/motivación crónica: 2.5mg en ayunas 2-3x/semana. CRÍTICO: lavout de 14 días al cambiar de SSRI a selegilina (MAO-B se regenera 14 días). Stack con L-tirosina 500mg, mucuna pruriens 400mg = "stack dopamina". Si parche: rotar sitio (espalda, cadera).',en:'For Parkinson\'s: 5mg × 2/day (morning + midday — NOT afternoon, activating). For refractory depression: EMSAM patch 6mg/24h (no tyramine restriction). Off-label Knoll longevity: 1mg/day Monday-Wednesday-Friday (3x/week) age 40-60; 2.5mg MWF age 60-70; 5mg MWF age 70+. For chronic dopamine/motivation: 2.5mg fasted 2-3x/week. CRITICAL: 14-day washout when switching from SSRI to selegiline (MAO-B regenerates 14 days). Stack with L-tyrosine 500mg, mucuna pruriens 400mg = "dopamine stack". If patch: rotate site (back, hip).'},
  sourcing:{
    local:[
      {name:'Farmacias David (Rx)',url:'#',note:{es:'selegilina genérica con Rx neurólogo · Parkinson context',en:'generic selegiline with neurologist Rx · Parkinson context'}}
    ],
    intl:[
      {name:'CosmicNootropic Jumex',url:'https://cosmicnootropic.com',note:{es:'★ Jumex Hungría genuino (Knoll labs original) · envío internacional',en:'★ genuine Hungarian Jumex (original Knoll labs) · international ship'}},
      {name:'EMSAM (Mylan USA Rx)',url:'https://www.emsam.com',note:{es:'parche transdermal · Rx psiquiatra USA',en:'transdermal patch · US psychiatrist Rx'}},
      {name:'Marek Health',url:'https://marekhealth.com',note:{es:'telehealth USA · selegilina con consulta',en:'US telehealth · selegiline with consultation'}}
    ]
  }
},

{ id:'hbot-hyperbaric', category:'mitochondrial',
  name:{es:'HBOT · Cámara Hiperbárica',en:'HBOT · Hyperbaric Oxygen Therapy'},
  origin:{es:'Henshaw 1662 · USS Squalus 1939 · Shai Efrati · Tel Aviv 2010s',en:'Henshaw 1662 · USS Squalus 1939 · Shai Efrati · Tel Aviv 2010s'},
  one:{es:'Oxígeno puro a 2-3 atmósferas regenera telómeros, cerebro post-stroke, tejido isquémico.',en:'Pure oxygen at 2-3 atmospheres regenerates telomeres, post-stroke brain, ischemic tissue.'},
  story:{es:'En 1662 el clérigo británico Henshaw construyó "domicilium" — primera cámara hiperbárica de la historia. La medicina hiperbárica nació formalmente con buceadores en los 1930s (enfermedad descompresión). El cambio paradigmático llegó con <strong>Shai Efrati</strong>, director del Centro Sagol de Medicina Hiperbárica (Israel) — demostró desde 2010 que HBOT regenera tejido cerebral post-stroke años después del evento (tradicionalmente considerado irreversible). En 2020 su grupo publicó (<em>Aging</em>) que <strong>60 sesiones HBOT alargan telómeros 20-38% e invierten senescencia celular</strong> — primer estudio robusto de inversión de envejecimiento celular en humanos. Protocolo Efrati: 90 minutos a 2.0 ATA × 60 sesiones × 5 días/semana (12 semanas). En USA David Sinclair, Peter Attia, Mark Hyman han adoptado HBOT. Aviv Clinics (USA · Florida + Dubai) ofrece protocolo Efrati clínicamente. Cámaras "soft-shell" 1.3 ATA (Vitaeris, OxyHealth) están en domicilio pero alcanzan menor presión — beneficio principal post-COVID y recuperación. Cámaras "hard-shell" 2-3 ATA son las que producen efectos regenerativos Efrati. Riesgos: barotrauma oído (igualar presión), miopía transitoria, riesgo fuego (no llevar electrónicos a hard-shell).',en:'In 1662 British clergyman Henshaw built "domicilium" — first hyperbaric chamber in history. Hyperbaric medicine formally born with divers in 1930s (decompression sickness). The paradigm shift came with <strong>Shai Efrati</strong>, director of Sagol Center for Hyperbaric Medicine (Israel) — demonstrated since 2010 that HBOT regenerates brain tissue post-stroke years after event (traditionally considered irreversible). In 2020 his group published (<em>Aging</em>) that <strong>60 HBOT sessions lengthen telomeres 20-38% and reverse cellular senescence</strong> — first robust study of human cellular aging reversal. Efrati protocol: 90 minutes at 2.0 ATA × 60 sessions × 5 days/week (12 weeks). In USA David Sinclair, Peter Attia, Mark Hyman have adopted HBOT. Aviv Clinics (USA · Florida + Dubai) offers Efrati protocol clinically. "Soft-shell" 1.3 ATA chambers (Vitaeris, OxyHealth) are home but reach lower pressure — main benefit post-COVID and recovery. "Hard-shell" 2-3 ATA chambers produce the Efrati regenerative effects. Risks: ear barotrauma (equalize pressure), transient myopia, fire risk (no electronics in hard-shell).'},
  compounds:'O₂ 100% a 1.3-3.0 ATA · presión parcial oxígeno 760-2280 mmHg · disuelto en plasma · saturación sin hemoglobina',
  effect:{es:'A presión atmosférica normal, hemoglobina transporta 97% O₂. A 2.0 ATA oxígeno puro: <strong>plasma transporta 10x más O₂ disuelto</strong> — alcanza tejidos isquémicos sin necesitad de eritrocitos. Mecanismos: (1) angiogénesis (nuevos vasos), (2) movilización células madre desde médula ósea, (3) alargamiento telómeros, (4) inducción HIF-1α paradójica + factor reparación tisular, (5) anti-inflamatorio crónico, (6) reducción inflamación cerebral en TBI/stroke. Estudios: post-stroke (Efrati 2013), TBI veteranos (Harch 2017), envejecimiento (Hachmo 2020), long-COVID (multiples 2022-2024), fibromialgia (Efrati 2015), Lyme crónica. NO sustituye medicina convencional — complementario. Sesión típica: 60-90 min, presurización 5-10 min, descompresión 10 min. Costo: $200-400/sesión · paquetes 60 = $12-24K USD.',en:'At normal atmospheric pressure, hemoglobin carries 97% O₂. At 2.0 ATA pure oxygen: <strong>plasma carries 10x more dissolved O₂</strong> — reaches ischemic tissue without erythrocytes. Mechanisms: (1) angiogenesis (new vessels), (2) stem cell mobilization from bone marrow, (3) telomere lengthening, (4) paradoxical HIF-1α induction + tissue repair factor, (5) chronic anti-inflammatory, (6) brain inflammation reduction in TBI/stroke. Studies: post-stroke (Efrati 2013), veteran TBI (Harch 2017), aging (Hachmo 2020), long-COVID (multiple 2022-2024), fibromyalgia (Efrati 2015), chronic Lyme. NOT substitute for conventional medicine — complementary. Typical session: 60-90 min, pressurization 5-10 min, decompression 10 min. Cost: $200-400/session · 60 packages = $12-24K USD.'},
  ingredients:{es:['Cámara hard-shell 2.0-3.0 ATA en clínica (Aviv, Sagol)','Alternativa home: cámara soft-shell 1.3 ATA (OxyHealth Vitaeris 320 ~$22K)','Oxígeno concentrador 5-10 LPM con máscara facial','Hidratación 2L por sesión + evitar electrónicos en hard-shell'],en:['Hard-shell 2.0-3.0 ATA chamber in clinic (Aviv, Sagol)','Home alternative: soft-shell 1.3 ATA chamber (OxyHealth Vitaeris 320 ~$22K)','Oxygen concentrator 5-10 LPM with facial mask','2L hydration per session + avoid electronics in hard-shell']},
  recipe:{es:'Protocolo Efrati regenerativo: 60 sesiones × 90 minutos a 2.0 ATA × 5 días/semana = 12 semanas. Mascarilla con O₂ 100%, pausas de 5 min cada 20 min de aire ambiente (Berry break — previene toxicidad oxígeno SNC). Igualar oídos durante presurización (Valsalva o swallow). Llevar ropa 100% algodón (NO sintéticos en hard-shell — fuego). Si soft-shell home: 60 min/día × 30-60 sesiones a 1.3 ATA, beneficio principal recovery deportivo, post-COVID, ansiedad. Después de protocolo base, mantenimiento 1-2 sesiones/semana. CONTRAINDICACIONES: neumotórax actual, enfermedad pulmonar severa, embarazo (relative), claustrofobia severa.',en:'Efrati regenerative protocol: 60 sessions × 90 minutes at 2.0 ATA × 5 days/week = 12 weeks. Mask with 100% O₂, 5-min air breaks every 20 min (Berry break — prevents CNS oxygen toxicity). Equalize ears during pressurization (Valsalva or swallow). Wear 100% cotton (NO synthetics in hard-shell — fire risk). If soft-shell home: 60 min/day × 30-60 sessions at 1.3 ATA, main benefit athletic recovery, post-COVID, anxiety. After base protocol, maintenance 1-2 sessions/week. CONTRAINDICATIONS: current pneumothorax, severe lung disease, pregnancy (relative), severe claustrophobia.'},
  sourcing:{
    local:[
      {name:'Hospital Punta Pacífica HBOT',url:'https://www.hospitalpuntapacifica.com',note:{es:'Panamá City · cámara hard-shell clínica · referido necesario',en:'Panama City · clinical hard-shell chamber · referral needed'}}
    ],
    intl:[
      {name:'Aviv Clinics (Florida · Dubai)',url:'https://aviv-clinics.com',note:{es:'★ protocolo Efrati oficial · 12 semanas · USA / EAU',en:'★ official Efrati protocol · 12 weeks · USA / UAE'}},
      {name:'Sagol Center Tel Aviv',url:'https://www.assuta.co.il',note:{es:'★ ORIGEN · centro de Efrati · Israel',en:'★ ORIGIN · Efrati center · Israel'}},
      {name:'OxyHealth (cámaras soft-shell)',url:'https://oxyhealth.com',note:{es:'cámara casa Vitaeris 320 1.3 ATA · USA',en:'home chamber Vitaeris 320 1.3 ATA · USA'}},
      {name:'UHMS Find a Clinic',url:'https://www.uhms.org/find-a-clinic',note:{es:'directorio clínicas certificadas globalmente · gratis',en:'globally certified clinic directory · free'}}
    ]
  }
},

{ id:'nsi-189', category:'cognitive',
  name:{es:'NSI-189 · Neurogénesis Hipocampal',en:'NSI-189 · Hippocampal Neurogenesis'},
  origin:{es:'Neuralstem · 2008 · primer fármaco específicamente neurogénico',en:'Neuralstem · 2008 · first specifically neurogenic drug'},
  one:{es:'Primer compuesto diseñado específicamente para producir neuronas nuevas en hipocampo.',en:'First compound specifically designed to grow new neurons in hippocampus.'},
  story:{es:'En 2008 la biotech <strong>Neuralstem</strong> en Maryland diseñó NSI-189 (también llamado <em>amdiglurax</em>) — primer fármaco creado específicamente para estimular neurogénesis hipocampal en adultos. La premisa: depresión mayor está asociada con atrofia hipocampal (Sapolsky, Duman 1990s); restaurar neurogénesis = restaurar función. Fase 1 (2010) y fase 2a (2014): NSI-189 produjo mejoras significativas en depresión refractaria con perfil de seguridad excelente. Fase 2 grande (NDC-189-101, 2017, 220 pacientes): el endpoint primario (cambio MADRS) NO alcanzó significancia, aunque endpoints secundarios cognitivos y de calidad de vida sí. Neuralstem decidió no proseguir Fase 3. El compuesto entró el "valle de la muerte" comercial — pero la comunidad nootropic biohacker continuó investigándolo como research chemical. Reportes anecdóticos: mejora memoria episódica, reducción ansiedad social, sensación de "anti-depresión cognitiva" (vs SSRI emotional flatness). Efectos no inmediatos — neurogénesis toma 4-8 semanas. Vida media 17h, dosis típica 40mg/día. Status: research chemical (no aprobado), comprado vía vendors no-FDA (con riesgos asociados de pureza).',en:'In 2008 biotech <strong>Neuralstem</strong> in Maryland designed NSI-189 (also called <em>amdiglurax</em>) — first drug created specifically to stimulate adult hippocampal neurogenesis. Premise: major depression associated with hippocampal atrophy (Sapolsky, Duman 1990s); restoring neurogenesis = restoring function. Phase 1 (2010) and 2a (2014): NSI-189 produced significant improvement in treatment-resistant depression with excellent safety profile. Large Phase 2 (NDC-189-101, 2017, 220 patients): primary endpoint (MADRS change) did NOT reach significance, though secondary cognitive and quality-of-life endpoints did. Neuralstem decided not to pursue Phase 3. The compound entered the commercial "valley of death" — but the nootropic biohacker community continued investigating it as research chemical. Anecdotal reports: improved episodic memory, reduced social anxiety, "cognitive anti-depression" sensation (vs SSRI emotional flatness). Effects not immediate — neurogenesis takes 4-8 weeks. Half-life 17h, typical dose 40mg/day. Status: research chemical (unapproved), purchased via non-FDA vendors (with associated purity risks).'},
  compounds:'C18H22N4O · 4-benzilamino-2-(N,N-dimetilamino)-7-(1-piperidinilmetil)-quinazolina · estimulante BDNF',
  effect:{es:'Mecanismo proceso: estimula proliferación de células madre neurales en giro dentado (DG) hipocampal. Induce expresión BDNF + IGF-1 + NT-3 (neurotrofinas). NO actúa via monoaminas (no SSRI, no MAOI). NO afecta dopamina/serotonina/norepinefrina directamente. Selectivo para hipocampo — explica perfil distinto vs antidepresivos clásicos. Estudios: pacientes Fase 2 mostraron mejora cognitiva (procesamiento ejecutivo, memoria de trabajo) y QoL — aunque endpoint depresión primario falló. Reportes biohacker: efecto requiere 4-8 semanas continuas para sentirse, no inmediato. Efectos secundarios reportados: cefalea leve transitoria, vivid dreams (5% biohackers). Sin liability de abuso. Larga vida media (17h) permite dosificación una vez al día. RIESGO CLAVE: research chemical vendors — exigir COA (certificado de análisis) para evitar impurezas/contaminación. NO mezclar con MAOIs hasta más datos.',en:'Process mechanism: stimulates neural stem cell proliferation in hippocampal dentate gyrus (DG). Induces BDNF + IGF-1 + NT-3 expression (neurotrophins). Does NOT act via monoamines (not SSRI, not MAOI). Does NOT directly affect dopamine/serotonin/norepinephrine. Selective for hippocampus — explains distinct profile vs classical antidepressants. Studies: Phase 2 patients showed cognitive improvement (executive processing, working memory) and QoL — though primary depression endpoint failed. Biohacker reports: effect requires 4-8 continuous weeks to feel, not immediate. Reported side effects: mild transient headache, vivid dreams (5% biohackers). No abuse liability. Long half-life (17h) allows once-daily dosing. KEY RISK: research chemical vendors — require COA (Certificate of Analysis) to avoid impurities/contamination. DO NOT mix with MAOIs until more data.'},
  ingredients:{es:['NSI-189 polvo o cápsulas · 40mg/día (vendors research chemical con COA)','Báscula miligramo 0.001g · esencial para dosis precisa','Cápsulas vacías + cápsula filler · si compras polvo bruto','Stack opcional: Lion\'s Mane 1g + EGCG 400mg (sinergia BDNF)'],en:['NSI-189 powder or capsules · 40mg/day (research chemical vendors with COA)','Milligram scale 0.001g · essential for precise dosing','Empty capsules + filler · if buying raw powder','Optional stack: Lion\'s Mane 1g + EGCG 400mg (BDNF synergy)']},
  recipe:{es:'Dosis trial: 40mg/día (una sola dosis en la mañana — vida media 17h cubre 24h). Comenzar 20mg primera semana para valorar respuesta. Comer con desayuno (mejor absorción). Esperar 4-8 semanas para evaluar efecto cognitivo (neurogénesis lleva tiempo). Si beneficio: continuar 12-16 semanas, después break 4 semanas. Stack tradicional biohacker: NSI-189 40mg + Lion\'s Mane 1g + Bacopa 300mg = "stack de neurogénesis". NUNCA combinar con MAOI (selegilina, fenelzina) — interacción no estudiada. VERIFICAR vendor: pedir COA con LC-MS de tercero (UmbrellaLabs, IntelliMeds, NootropicSources son vendors comunes pero verificar lote a lote).',en:'Trial dose: 40mg/day (single morning dose — 17h half-life covers 24h). Start 20mg first week to assess response. Eat with breakfast (better absorption). Wait 4-8 weeks to evaluate cognitive effect (neurogenesis takes time). If benefit: continue 12-16 weeks, then 4-week break. Traditional biohacker stack: NSI-189 40mg + Lion\'s Mane 1g + Bacopa 300mg = "neurogenesis stack". NEVER combine with MAOI (selegiline, phenelzine) — interaction unstudied. VERIFY vendor: request third-party LC-MS COA (UmbrellaLabs, IntelliMeds, NootropicSources are common vendors but verify lot by lot).'},
  sourcing:{
    local:[],
    intl:[
      {name:'UmbrellaLabs',url:'https://umbrellalabs.is',note:{es:'★ research chemicals con COA · NSI-189 disponible · USA',en:'★ research chemicals with COA · NSI-189 available · USA'}},
      {name:'NootropicSources',url:'https://nootropicsource.com',note:{es:'★ NSI-189 cápsulas con análisis 3rd-party · USA',en:'★ NSI-189 capsules with 3rd-party analysis · USA'}},
      {name:'IntelliMeds',url:'https://www.intellimeds.net',note:{es:'NSI-189 polvo bruto con COA · USA',en:'NSI-189 raw powder with COA · USA'}},
      {name:'Reddit r/Nootropics NSI-189',url:'https://www.reddit.com/r/Nootropics/search?q=nsi-189',note:{es:'comunidad evaluación vendors · COA reports',en:'community vendor evaluation · COA reports'}}
    ]
  }
}

];
