/* =============================================================
   SORA · LAND & PROPERTY DATABASE
   47 verified-live listings across 9 LATAM countries +
   per-region administrative contacts for due diligence.
   Each listing has: verified URL, photo URL, area-search
   fallback URL, source label.
   Last URL-validation pass: 2026-05-25 (33/41 + 14/14 batch).
   Listings rotate; re-validate quarterly.
   Loaded as window.SORA_LAND.
   ============================================================= */
window.SORA_LAND = {

LISTINGS: [
  /* ============================== MX ============================== */
  /* San Miguel de Allende — verified Sotheby's via LuxuryEstate aggregator */
  { id:'mx-sma-1', country:'MX', region:'San Miguel de Allende', type:'house',
    name:'Casa Nueva Aventura', sizeM2:753, bedrooms:8, priceUSD:2645000,
    status:'available', source:'Sotheby\'s SMA', broker:'San Miguel Sotheby\'s International Realty',
    url:'https://www.luxuryestate.com/p132117976-detached-house-for-sale-san-miguel-de-allende',
    areaUrl:'https://www.luxuryestate.com/mexico/guanajuato/san-miguel-de-allende',
    photo:'https://pic.le-cdn.com/thumbs/520x390/08/1/properties/Property-1efeb318e7ae833a50dcd219721c44f4-132117976.jpg',
    notes:{es:'Extraordinaria residencia en Colonia Guadiana, dos cuadras de Ancha de San Antonio.',
           en:'Extraordinary residence in Colonia Guadiana, two blocks from Ancha de San Antonio.'} },
  { id:'mx-sma-2', country:'MX', region:'San Miguel de Allende · Centro', type:'house',
    name:'Casa de la Canal', sizeM2:915, bedrooms:9, priceUSD:3308000,
    status:'available', source:'Sotheby\'s SMA', broker:'San Miguel Sotheby\'s International Realty',
    url:'https://www.luxuryestate.com/p132117790-detached-house-for-sale-san-miguel-de-allende',
    areaUrl:'https://www.luxuryestate.com/mexico/guanajuato/san-miguel-de-allende',
    photo:'https://pic.le-cdn.com/thumbs/520x390/08/1/properties/Property-3e38be8d2344581a8e3413624a46b574-132117790.jpg',
    notes:{es:'Residencia histórica 1717 en pleno Centro Histórico, patio central, esencia colonial.',
           en:'Historic 1717 residence in heart of Centro Histórico, central courtyard, colonial essence.'} },
  { id:'mx-sma-3', country:'MX', region:'San Miguel de Allende', type:'house',
    name:'Villa Serena', sizeM2:570, bedrooms:4, priceUSD:1322000,
    status:'available', source:'Sotheby\'s SMA', broker:'San Miguel Sotheby\'s International Realty',
    url:'https://www.luxuryestate.com/p132213024-detached-house-for-sale-san-miguel-de-allende',
    areaUrl:'https://www.luxuryestate.com/mexico/guanajuato/san-miguel-de-allende',
    photo:null,
    notes:{es:'Comunidad Los Lopez, 20 min del centro. Escape sereno con opciones de expansión.',
           en:'Los Lopez community, 20 min from town. Serene escape with expansion potential.'} },
  { id:'mx-sma-4', country:'MX', region:'San Miguel de Allende', type:'house',
    name:'Casa Cúpula', sizeM2:408, bedrooms:5, priceUSD:930000,
    status:'available', source:'Sotheby\'s SMA', broker:'San Miguel Sotheby\'s International Realty',
    url:'https://www.luxuryestate.com/p132129665-detached-house-for-sale-san-miguel-de-allende',
    areaUrl:'https://www.luxuryestate.com/mexico/guanajuato/san-miguel-de-allende',
    photo:null,
    notes:{es:'Casa de 5 dormitorios, 408 m², colonial-contemporánea.',
           en:'5-bedroom colonial-contemporary, 408 m².'} },
  { id:'mx-sma-5', country:'MX', region:'San Miguel de Allende', type:'house',
    name:'Casa El Refugio', sizeM2:637, bedrooms:6, priceUSD:2550000,
    status:'available', source:'Sotheby\'s SMA', broker:'San Miguel Sotheby\'s International Realty',
    url:'https://www.luxuryestate.com/p131218865-detached-house-for-sale-san-miguel-de-allende',
    areaUrl:'https://www.luxuryestate.com/mexico/guanajuato/san-miguel-de-allende',
    photo:null,
    notes:{es:'15 min del corazón de SMA. Retiro privado donde diseño contemporáneo armoniza con naturaleza.',
           en:'15 min from heart of SMA. Private retreat where contemporary design harmonizes with nature.'} },

  /* Tulum / Quintana Roo */
  { id:'mx-tulum-1', country:'MX', region:'Tulum', type:'house',
    name:'Villa Tulum', sizeM2:300, bedrooms:5, priceUSD:655000,
    status:'available', source:'LuxuryEstate · Mexico', broker:'Verified via LuxuryEstate aggregator',
    url:'https://www.luxuryestate.com/p129575868-villa-for-sale-tulum',
    areaUrl:'https://www.luxuryestate.com/mexico/quintana-roo/tulum',
    photo:'https://pic.le-cdn.com/thumbs/520x390/04/1/properties/Property-bc2b0000000007b900016569014c-129575868.jpg',
    notes:{es:'Villa 5BR estilo selvático, 300 m² construidos.',
           en:'5BR jungle-style villa, 300 m² built.'} },
  { id:'mx-tulum-2', country:'MX', region:'Tulum · Aldea Zama area', type:'apartment',
    name:'Departamento Panorámico Tulum', sizeM2:91, bedrooms:2, priceUSD:264000,
    status:'available', source:'LuxuryEstate · Mexico', broker:'Verified via LuxuryEstate aggregator',
    url:'https://www.luxuryestate.com/p129498610-apartment-for-sale-tulum',
    areaUrl:'https://www.luxuryestate.com/mexico/quintana-roo/tulum',
    photo:'https://pic.le-cdn.com/thumbs/520x390/08/1/properties/Property-261871c1950d249a9057deb046179b8c-129498610.jpg',
    notes:{es:'2BR con vista panorámica 360°. Apartamento boutique entrada de mercado.',
           en:'2BR with panoramic 360° view. Entry-level boutique apartment.'} },
  { id:'mx-tulum-3', country:'MX', region:'Tulum · beachfront', type:'apartment',
    name:'Beachfront Apartment Tulum', sizeM2:305, bedrooms:3, priceUSD:1837000,
    status:'available', source:'LuxuryEstate · Mexico', broker:'Verified via LuxuryEstate aggregator',
    url:'https://www.luxuryestate.com/p127702609-apartment-for-sale-tulum',
    areaUrl:'https://www.luxuryestate.com/mexico/quintana-roo/tulum',
    photo:null,
    notes:{es:'Frente al mar 3BR 305 m². Restricción zona costera — usar fideicomiso.',
           en:'Oceanfront 3BR 305 m². Coastal restricted zone — use fideicomiso.'} },
  { id:'mx-tulum-4', country:'MX', region:'Tulum · compound', type:'house',
    name:'Luxury 5-Villa Compound', sizeM2:1800, bedrooms:27, priceUSD:2776000,
    status:'available', source:'LuxuryEstate · Mexico', broker:'Verified via LuxuryEstate aggregator',
    url:'https://www.luxuryestate.com/p128419011-luxury-home-for-sale-tulum',
    areaUrl:'https://www.luxuryestate.com/mexico/quintana-roo/tulum',
    photo:null,
    notes:{es:'Compound de 5 villas, 27 BR total. Listo para hotel boutique o multi-familia.',
           en:'5-villa compound, 27 BR total. Boutique hotel or multi-family ready.'} },

  /* ============================== CO ============================== */
  /* Medellín */
  { id:'co-mde-1', country:'CO', region:'Medellín · El Poblado', type:'house',
    name:'Art Mansion El Poblado', sizeM2:2600, bedrooms:8, priceUSD:4100000,
    status:'available', source:'LuxuryEstate · Colombia', broker:'Premium Medellín agency',
    url:'https://www.luxuryestate.com/p131095767-luxury-home-for-sale-medellin',
    areaUrl:'https://www.luxuryestate.com/colombia/departamento-de-antioquia/medellin/medellin',
    photo:'https://pic.le-cdn.com/thumbs/520x390/152/1/properties/Property-a8065f0f697ad1fbe4080b7707e1cc0a-131095767.jpg',
    notes:{es:'Obra maestra de 2,600 m² en zona más valuada de Medellín.',
           en:'2,600 m² masterpiece in Medellín\'s safest and most valuable area.'} },
  { id:'co-mde-2', country:'CO', region:'Medellín · Golden Mile', type:'apartment',
    name:'Penthouse Golden Mile Duplex', sizeM2:0, bedrooms:8, priceUSD:1650000,
    status:'available', source:'LuxuryEstate · Colombia', broker:'Premium Medellín agency',
    url:'https://www.luxuryestate.com/p130020019-penthouse-for-sale-medellin',
    areaUrl:'https://www.luxuryestate.com/colombia/departamento-de-antioquia/medellin/medellin',
    photo:'https://pic.le-cdn.com/thumbs/520x390/152/1/properties/Property-6d9a16db35966f21e39530cef8a5d298-130020019.jpg',
    notes:{es:'PH duplex en Golden Mile, cerca Oviedo + San Fernando Plaza + Provenza.',
           en:'PH duplex on Golden Mile, near Oviedo + San Fernando Plaza + Provenza.'} },
  { id:'co-mde-3', country:'CO', region:'Medellín · Provenza', type:'apartment',
    name:'Penthouse Provenza/Vizcaya', sizeM2:0, bedrooms:6, priceUSD:1975000,
    status:'available', source:'LuxuryEstate · Colombia', broker:'Premium Medellín agency',
    url:'https://www.luxuryestate.com/p131525550-penthouse-for-sale-medellin',
    areaUrl:'https://www.luxuryestate.com/colombia/departamento-de-antioquia/medellin/medellin',
    photo:null,
    notes:{es:'Corazón Provenza/Vizcaya — el barrio más deseado de Medellín. Gastronomía mundial.',
           en:'Heart of Provenza/Vizcaya — Medellín\'s most desirable neighborhood. World cuisine.'} },
  { id:'co-mde-4', country:'CO', region:'Medellín · Las Palmas', type:'rural',
    name:'Farmhouse Las Palmas', sizeM2:3200, bedrooms:9, priceUSD:2580000,
    status:'available', source:'LuxuryEstate · Colombia', broker:'Premium Medellín agency',
    url:'https://www.luxuryestate.com/p131598314-farmhouse-for-sale-medellin',
    areaUrl:'https://www.luxuryestate.com/colombia/departamento-de-antioquia/medellin/medellin',
    photo:null,
    notes:{es:'Finca 3,200 m² lot, 800 m² construido. Vista panorámica Aburrá.',
           en:'3,200 m² lot, 800 m² built. Panoramic Aburrá Valley view.'} },
  { id:'co-mde-5', country:'CO', region:'Medellín · Las Palmas', type:'house',
    name:'Luxury Home Las Palmas', sizeM2:0, bedrooms:9, priceUSD:3095000,
    status:'available', source:'LuxuryEstate · Colombia', broker:'Premium Medellín agency',
    url:'https://www.luxuryestate.com/p130833556-luxury-home-for-sale-medellin',
    areaUrl:'https://www.luxuryestate.com/colombia/departamento-de-antioquia/medellin/medellin',
    photo:null,
    notes:{es:'Vista panorámica ciudad. Spa privado, pool, jacuzzi, fire pit.',
           en:'Panoramic city views. Private spa, pool, jacuzzi, fire pit.'} },

  /* Cartagena */
  { id:'co-cart-1', country:'CO', region:'Cartagena · Bocagrande', type:'apartment',
    name:'Penthouse Bocagrande', sizeM2:1100, bedrooms:5, priceUSD:2058000,
    status:'available', source:'LuxuryEstate · Colombia', broker:'Cartagena luxury agency',
    url:'https://www.luxuryestate.com/p82440145-penthouse-for-sale-cartagena',
    areaUrl:'https://www.luxuryestate.com/colombia/departamento-de-bolivar/cartagena/cartagena',
    photo:'https://pic.le-cdn.com/thumbs/520x390/152/1/properties/Property-13b23a6e792273f57c37081322850321-82440145.jpg',
    notes:{es:'PH 5BR en Portomarine Luxury Residences. 1,100 m².',
           en:'5BR PH in Portomarine Luxury Residences. 1,100 m².'} },
  { id:'co-cart-2', country:'CO', region:'Cartagena · Aguamarina', type:'apartment',
    name:'Aguamarina Beach Resort Apartment', sizeM2:0, bedrooms:7, priceUSD:1800000,
    status:'available', source:'LuxuryEstate · Colombia', broker:'Cartagena luxury agency',
    url:'https://www.luxuryestate.com/p129453315-apartment-for-sale-cartagena',
    areaUrl:'https://www.luxuryestate.com/colombia/departamento-de-bolivar/cartagena/cartagena',
    photo:'https://pic.le-cdn.com/thumbs/520x390/152/1/properties/Property-ea7f80cebd73c1d1ef7bc48fdb76fa46-129453315.jpg',
    notes:{es:'Condominio Aguamarina Beach Resort km 64 Cartagena-Barranquilla.',
           en:'Aguamarina Beach Resort condo km 64 Cartagena-Barranquilla.'} },
  { id:'co-cart-3', country:'CO', region:'Cartagena · Bocagrande', type:'apartment',
    name:'Penthouse Bocagrande #2', sizeM2:0, bedrooms:7, priceUSD:1955000,
    status:'available', source:'LuxuryEstate · Colombia', broker:'Cartagena luxury agency',
    url:'https://www.luxuryestate.com/p92151765-penthouse-for-sale-cartagena',
    areaUrl:'https://www.luxuryestate.com/colombia/departamento-de-bolivar/cartagena/cartagena',
    photo:null,
    notes:{es:'PH 7BR Bocagrande. Vista parcial al mar.',
           en:'7BR PH Bocagrande. Partial sea view.'} },
  { id:'co-cart-4', country:'CO', region:'Cartagena · Infinitum', type:'apartment',
    name:'Apartment Infinitum', sizeM2:0, bedrooms:5, priceUSD:2546000,
    status:'available', source:'LuxuryEstate · Colombia', broker:'Cartagena luxury agency',
    url:'https://www.luxuryestate.com/p130021889-apartment-for-sale-cartagena',
    areaUrl:'https://www.luxuryestate.com/colombia/departamento-de-bolivar/cartagena/cartagena',
    photo:null,
    notes:{es:'5BR moderno en torre Infinitum, Cartagena.',
           en:'5BR modern in Infinitum tower, Cartagena.'} },
  { id:'co-cart-5', country:'CO', region:'Cartagena · Centro Histórico', type:'apartment',
    name:'Colonial Apartment Centro Histórico', sizeM2:0, bedrooms:7, priceUSD:1896000,
    status:'available', source:'LuxuryEstate · Colombia', broker:'Cartagena luxury agency',
    url:'https://www.luxuryestate.com/p131344757-apartment-for-sale-cartagena',
    areaUrl:'https://www.luxuryestate.com/colombia/departamento-de-bolivar/cartagena/cartagena',
    photo:null,
    notes:{es:'Apartamento colonial 4 niveles con piscina privada en Centro Histórico.',
           en:'4-level colonial with private pool in Centro Histórico.'} },

  /* ============================== BR ============================== */
  /* Trancoso */
  { id:'br-tran-1', country:'BR', region:'Trancoso · Bahia', type:'house',
    name:'Luxury Home Trancoso (7BR)', sizeM2:800, bedrooms:7, priceUSD:2456000,
    status:'available', source:'LuxuryEstate · Brazil', broker:'Bahia Luxury Trancoso',
    url:'https://www.luxuryestate.com/p130531110-luxury-home-for-sale-trancoso',
    areaUrl:'https://www.luxuryestate.com/brazil/estado-da-bahia/trancoso',
    photo:'https://pic.le-cdn.com/thumbs/520x390/04/1/properties/Property-26bf0000000007c7000166ad194f-130531110.jpg',
    notes:{es:'Casa 7 suites, 800 m². Renovada 2021.',
           en:'7-suite, 800 m². Renovated 2021.'} },
  { id:'br-tran-2', country:'BR', region:'Trancoso · Bahia', type:'house',
    name:'Luxury Home Trancoso (8BR)', sizeM2:1100, bedrooms:8, priceUSD:0,
    status:'available', source:'LuxuryEstate · Brazil', broker:'Bahia Luxury Trancoso',
    url:'https://www.luxuryestate.com/p125748663-luxury-home-for-sale-trancoso',
    areaUrl:'https://www.luxuryestate.com/brazil/estado-da-bahia/trancoso',
    photo:'https://pic.le-cdn.com/thumbs/520x390/04/1/properties/Property-b7c500000000077e0001627655fa-125748663.jpg',
    notes:{es:'Precio a consulta. 8 dormitorios, 1,100 m². Top-tier Trancoso.',
           en:'Price on request. 8 bedrooms, 1,100 m². Top-tier Trancoso.'} },
  { id:'br-tran-3', country:'BR', region:'Trancoso · 6,000 m² lot', type:'house',
    name:'Luxury Home Trancoso (large lot)', sizeM2:6000, bedrooms:8, priceUSD:3212000,
    status:'available', source:'LuxuryEstate · Brazil', broker:'Bahia Luxury Trancoso',
    url:'https://www.luxuryestate.com/p128867687-luxury-home-for-sale-trancoso',
    areaUrl:'https://www.luxuryestate.com/brazil/estado-da-bahia/trancoso',
    photo:null,
    notes:{es:'Lote 6,000 m² con 8BR. Posible pousada boutique.',
           en:'6,000 m² lot with 8BR. Boutique pousada potential.'} },
  { id:'br-tran-4', country:'BR', region:'Trancoso · Bahia', type:'house',
    name:'Luxury Home Trancoso (1,000 m²)', sizeM2:1000, bedrooms:8, priceUSD:2161000,
    status:'available', source:'LuxuryEstate · Brazil', broker:'Bahia Luxury Trancoso',
    url:'https://www.luxuryestate.com/p112216943-luxury-home-for-sale-trancoso',
    areaUrl:'https://www.luxuryestate.com/brazil/estado-da-bahia/trancoso',
    photo:null,
    notes:{es:'8BR Trancoso, 1,000 m². Cerca del Quadrado.',
           en:'8BR Trancoso, 1,000 m². Near the Quadrado.'} },

  /* ============================== AR ============================== */
  /* Buenos Aires */
  { id:'ar-ba-1', country:'AR', region:'BA · San Telmo', type:'apartment',
    name:'Apartment San Telmo', sizeM2:646, bedrooms:5, priceUSD:1232000,
    status:'available', source:'LuxuryEstate · Argentina', broker:'Buenos Aires luxury agency',
    url:'https://www.luxuryestate.com/p128941759-apartment-for-sale-buenos-aires',
    areaUrl:'https://www.luxuryestate.com/argentina/buenos-aires-f-d-/buenos-aires',
    photo:'https://pic.le-cdn.com/thumbs/520x390/04/1/properties/Property-bf7e0000000007af000164874dad-128941759.jpg',
    notes:{es:'5BR colonial en San Telmo, 646 m². Carácter histórico.',
           en:'5BR colonial in San Telmo, 646 m². Historic character.'} },
  { id:'ar-ba-2', country:'AR', region:'BA · Palermo Chico', type:'house',
    name:'Townhouse Palermo Chico', sizeM2:1234, bedrooms:5, priceUSD:11754000,
    status:'available', source:'LuxuryEstate · Argentina', broker:'Buenos Aires luxury agency',
    url:'https://www.luxuryestate.com/p132421270-townhouse-for-sale-buenos-aires',
    areaUrl:'https://www.luxuryestate.com/argentina/buenos-aires-f-d-/buenos-aires',
    photo:'https://pic.le-cdn.com/thumbs/520x390/08/1/properties/Property-ed173d17e45a47bf7b29fc8582865fb0-132421270.jpg',
    notes:{es:'Townhouse Palermo Chico 1,234 m². Top-tier residencial BA.',
           en:'Palermo Chico townhouse 1,234 m². Top-tier BA residential.'} },
  { id:'ar-ba-3', country:'AR', region:'BA · high-rise', type:'apartment',
    name:'High-Rise Apartment', sizeM2:250, bedrooms:4, priceUSD:3519000,
    status:'available', source:'LuxuryEstate · Argentina', broker:'Buenos Aires luxury agency',
    url:'https://www.luxuryestate.com/p129630300-apartment-for-sale-buenos-aires',
    areaUrl:'https://www.luxuryestate.com/argentina/buenos-aires-f-d-/buenos-aires',
    photo:null,
    notes:{es:'4BR alto piso, 250 m². Vista privilegiada.',
           en:'4BR high floor, 250 m². Privileged view.'} },
  { id:'ar-ba-4', country:'AR', region:'BA · Acassuso', type:'apartment',
    name:'Acassuso Residence', sizeM2:600, bedrooms:6, priceUSD:2559000,
    status:'available', source:'LuxuryEstate · Argentina', broker:'Buenos Aires luxury agency',
    url:'https://www.luxuryestate.com/p131547925-apartment-for-sale-buenos-aires',
    areaUrl:'https://www.luxuryestate.com/argentina/buenos-aires-f-d-/buenos-aires',
    photo:null,
    notes:{es:'Residencia 6BR Acassuso, 600 m².',
           en:'6BR Acassuso residence, 600 m².'} },
  { id:'ar-ba-5', country:'AR', region:'BA · Plaza San Martín', type:'apartment',
    name:'Plaza San Martín Apartment', sizeM2:0, bedrooms:0, priceUSD:3185000,
    status:'available', source:'LuxuryEstate · Argentina', broker:'Buenos Aires luxury agency',
    url:'https://www.luxuryestate.com/p131824205-apartment-for-sale-buenos-aires',
    areaUrl:'https://www.luxuryestate.com/argentina/buenos-aires-f-d-/buenos-aires',
    photo:null,
    notes:{es:'Apartamento Plaza San Martín. Heritage clásico BA.',
           en:'Plaza San Martín apartment. Classic BA heritage.'} },

  /* ============================== CR ============================== */
  /* Nosara */
  { id:'cr-nosa-1', country:'CR', region:'Nosara · K Section', type:'house',
    name:'La Capannina (K Section villa)', sizeM2:491, bedrooms:5, priceUSD:3981000,
    status:'available', source:'LuxuryEstate · Costa Rica', broker:'Nosara luxury agency',
    url:'https://www.luxuryestate.com/p131715935-villa-for-sale-nosara',
    areaUrl:'https://www.luxuryestate.com/costa-rica/provincia-de-guanacaste/canton-de-nicoya/nosara',
    photo:'https://pic.le-cdn.com/thumbs/520x390/08/1/properties/Property-d2f0a3eb8f393450fba474375fce70ff-131715935.jpg',
    notes:{es:'Villa de lujo en K Section, 491 m², 5BR. Sección más codiciada de Nosara.',
           en:'Luxury villa in coveted K Section, 491 m², 5BR. Most-coveted Nosara section.'} },
  { id:'cr-nosa-2', country:'CR', region:'Nosara · Oceana', type:'house',
    name:'Oceana Nosara', sizeM2:557, bedrooms:7, priceUSD:2796000,
    status:'available', source:'LuxuryEstate · Costa Rica', broker:'Nosara luxury agency',
    url:'https://www.luxuryestate.com/p131201977-detached-house-for-sale-nosara',
    areaUrl:'https://www.luxuryestate.com/costa-rica/provincia-de-guanacaste/canton-de-nicoya/nosara',
    photo:'https://pic.le-cdn.com/thumbs/520x390/08/1/properties/Property-0b0e8fb94510160da74a5f9c86f24e5b-131201977.jpg',
    notes:{es:'Casa contemporánea 7BR, 557 m².',
           en:'Contemporary 7BR home, 557 m².'} },
  { id:'cr-nosa-3', country:'CR', region:'Nosara · Pavones', type:'house',
    name:'Pavones Family Ranch', sizeM2:0, bedrooms:8, priceUSD:2796000,
    status:'available', source:'LuxuryEstate · Costa Rica', broker:'Nosara luxury agency',
    url:'https://www.luxuryestate.com/p132096581-luxury-home-for-sale-nosara',
    areaUrl:'https://www.luxuryestate.com/costa-rica/provincia-de-guanacaste/canton-de-nicoya/nosara',
    photo:null,
    notes:{es:'Retiro costero raro, 8BR family ranch.',
           en:'Rare coastal retreat, 8BR family ranch.'} },
  { id:'cr-nosa-4', country:'CR', region:'Nosara', type:'house',
    name:'Casa Ashaya', sizeM2:0, bedrooms:3, priceUSD:2453000,
    status:'available', source:'LuxuryEstate · Costa Rica', broker:'Nosara luxury agency',
    url:'https://www.luxuryestate.com/p130185851-detached-house-for-sale-nosara',
    areaUrl:'https://www.luxuryestate.com/costa-rica/provincia-de-guanacaste/canton-de-nicoya/nosara',
    photo:null,
    notes:{es:'3BR contemporáneo, paraíso absoluto Nosara.',
           en:'3BR contemporary, absolute Nosara paradise.'} },

  /* ============================== PE ============================== */
  /* Lima */
  { id:'pe-lim-1', country:'PE', region:'Lima · Barranco', type:'house',
    name:'Detached House Barranco (10BR)', sizeM2:850, bedrooms:10, priceUSD:3601000,
    status:'available', source:'LuxuryEstate · Peru', broker:'Lima luxury agency',
    url:'https://www.luxuryestate.com/p130916535-detached-house-for-sale-barranco',
    areaUrl:'https://www.luxuryestate.com/peru',
    photo:'https://pic.le-cdn.com/thumbs/520x390/08/1/properties/Property-3641fcede44efb0db2c06b8429f96135-130916535.jpg',
    notes:{es:'Casa colonial restaurada Barranco, 10BR, 850 m². Boutique-hotel potential.',
           en:'Restored Barranco colonial, 10BR, 850 m². Boutique-hotel potential.'} },
  { id:'pe-lim-2', country:'PE', region:'Lima · Barranco', type:'apartment',
    name:'Apartment Barranco', sizeM2:751, bedrooms:6, priceUSD:2141000,
    status:'available', source:'LuxuryEstate · Peru', broker:'Lima luxury agency',
    url:'https://www.luxuryestate.com/p132031828-apartment-for-sale-barranco',
    areaUrl:'https://www.luxuryestate.com/peru',
    photo:'https://pic.le-cdn.com/thumbs/520x390/08/1/properties/Property-aadc9edc9807ec582d0a101c9b537d2a-132031828.jpg',
    notes:{es:'6BR apartamento boutique Barranco, 751 m².',
           en:'6BR boutique apartment Barranco, 751 m².'} },
  { id:'pe-lim-3', country:'PE', region:'Lima · San Isidro', type:'apartment',
    name:'Apartment San Isidro', sizeM2:790, bedrooms:5, priceUSD:6160000,
    status:'available', source:'LuxuryEstate · Peru', broker:'Lima luxury agency',
    url:'https://www.luxuryestate.com/p130865192-apartment-for-sale-san-isidro',
    areaUrl:'https://www.luxuryestate.com/peru',
    photo:null,
    notes:{es:'5BR ultra-luxury San Isidro, 790 m². Top-tier Lima.',
           en:'5BR ultra-luxury San Isidro, 790 m². Top-tier Lima.'} },
  { id:'pe-lim-4', country:'PE', region:'Lima · San Isidro', type:'apartment',
    name:'Duplex San Isidro', sizeM2:440, bedrooms:4, priceUSD:2464000,
    status:'available', source:'LuxuryEstate · Peru', broker:'Lima luxury agency',
    url:'https://www.luxuryestate.com/p132557094-duplex-for-sale-san-isidro',
    areaUrl:'https://www.luxuryestate.com/peru',
    photo:null,
    notes:{es:'Duplex 4BR San Isidro, 440 m².',
           en:'4BR duplex San Isidro, 440 m².'} },

  /* ============================== CL ============================== */
  /* Chile mixed */
  { id:'cl-frut-1', country:'CL', region:'Frutillar · Llanquihue', type:'house',
    name:'Frutillar Lakefront Estate', sizeM2:740, bedrooms:10, priceUSD:2180000,
    status:'available', source:'LuxuryEstate · Chile', broker:'Chile luxury agency',
    url:'https://www.luxuryestate.com/p131800645-luxury-home-for-sale-frutillar',
    areaUrl:'https://www.luxuryestate.com/chile',
    photo:'https://pic.le-cdn.com/thumbs/520x390/04/1/properties/Property-451e0000000007db00016908e147-131800645.jpg',
    notes:{es:'Estate lakefront Llanquihue, 740 m², 10BR. Patagonia chilena norte.',
           en:'Llanquihue lakefront estate, 740 m², 10BR. North Chilean Patagonia.'} },
  { id:'cl-chic-1', country:'CL', region:'Santiago · Chicureo', type:'house',
    name:'Chicureo Architectural Residence', sizeM2:242, bedrooms:4, priceUSD:762000,
    status:'available', source:'LuxuryEstate · Chile', broker:'Santiago luxury agency',
    url:'https://www.luxuryestate.com/p131705065-luxury-home-for-sale-chicureo-abajo',
    areaUrl:'https://www.luxuryestate.com/chile',
    photo:null,
    notes:{es:'Residencia arquitectónica 4BR Chicureo Abajo, 242 m². Santiago premium.',
           en:'4BR architectural residence Chicureo Abajo, 242 m². Premium Santiago.'} },
  { id:'cl-puch-1', country:'CL', region:'Valparaíso · Puchuncaví', type:'house',
    name:'Puchuncaví Clifftop House', sizeM2:557, bedrooms:8, priceUSD:2820000,
    status:'available', source:'LuxuryEstate · Chile', broker:'Valparaíso luxury agency',
    url:'https://www.luxuryestate.com/p128010859-detached-house-for-sale-puchuncavi',
    areaUrl:'https://www.luxuryestate.com/chile',
    photo:null,
    notes:{es:'Casa acantilado Puchuncaví, 8BR, 557 m². Pacífico costa.',
           en:'Puchuncaví clifftop house, 8BR, 557 m². Pacific coast.'} },
  { id:'cl-pvar-1', country:'CL', region:'Puerto Varas · Llanquihue', type:'rural',
    name:'Puerto Varas Lakefront Lodge', sizeM2:940, bedrooms:9, priceUSD:2266000,
    status:'available', source:'LuxuryEstate · Chile', broker:'Patagonia luxury agency',
    url:'https://www.luxuryestate.com/p132512449-country-house-for-sale-puerto-varas',
    areaUrl:'https://www.luxuryestate.com/chile',
    photo:null,
    notes:{es:'Lodge frente al lago Puerto Varas, 940 m², 9BR. Lakes District CL.',
           en:'Puerto Varas lakefront lodge, 940 m², 9BR. Chilean Lakes District.'} },

  /* ============================== UY ============================== */
  /* José Ignacio */
  { id:'uy-ji-1', country:'UY', region:'José Ignacio · Garzón', type:'apartment',
    name:'Apartment José Ignacio', sizeM2:97, bedrooms:3, priceUSD:810000,
    status:'available', source:'LuxuryEstate · Uruguay', broker:'Uruguay Sotheby\'s International',
    url:'https://www.luxuryestate.com/p132145785-apartment-for-sale-jose-ignacio',
    areaUrl:'https://www.luxuryestate.com/uruguay/maldonado/garzon/jose-ignacio',
    photo:'https://pic.le-cdn.com/thumbs/520x390/04/1/properties/Property-79620000000007e0000169613e10-132145785.jpg',
    notes:{es:'3BR apartamento entrada JI, 97 m². Acceso premium temporada.',
           en:'3BR entry JI apartment, 97 m². Premium-season access.'} },
  { id:'uy-ji-2', country:'UY', region:'José Ignacio', type:'house',
    name:'Luxury Home José Ignacio (6BR)', sizeM2:436, bedrooms:6, priceUSD:2370000,
    status:'available', source:'LuxuryEstate · Uruguay', broker:'Uruguay Sotheby\'s International',
    url:'https://www.luxuryestate.com/p131975677-luxury-home-for-sale-jose-ignacio',
    areaUrl:'https://www.luxuryestate.com/uruguay/maldonado/garzon/jose-ignacio',
    photo:'https://pic.le-cdn.com/thumbs/520x390/04/1/properties/Property-fdc90000000007dd000169076a14-131975677.jpg',
    notes:{es:'Casa lujo 6BR, 436 m².',
           en:'6BR luxury home, 436 m².'} },
  { id:'uy-ji-3', country:'UY', region:'José Ignacio', type:'house',
    name:'Luxury Home José Ignacio (7BR)', sizeM2:700, bedrooms:7, priceUSD:3697000,
    status:'available', source:'LuxuryEstate · Uruguay', broker:'Uruguay Sotheby\'s International',
    url:'https://www.luxuryestate.com/p131892363-luxury-home-for-sale-jose-ignacio',
    areaUrl:'https://www.luxuryestate.com/uruguay/maldonado/garzon/jose-ignacio',
    photo:null,
    notes:{es:'Casa premium 7BR, 700 m². JI top-tier.',
           en:'7BR premium home, 700 m². Top-tier JI.'} },
  { id:'uy-ji-4', country:'UY', region:'José Ignacio · Playa Brava', type:'house',
    name:'Beachfront House José Ignacio', sizeM2:350, bedrooms:4, priceUSD:8057000,
    status:'available', source:'LuxuryEstate · Uruguay', broker:'Uruguay Sotheby\'s International',
    url:'https://www.luxuryestate.com/p132370236-detached-house-for-sale-jose-ignacio',
    areaUrl:'https://www.luxuryestate.com/uruguay/maldonado/garzon/jose-ignacio',
    photo:null,
    notes:{es:'Frente al mar Playa Brava 4BR, 350 m². Ultra-luxury.',
           en:'Playa Brava beachfront 4BR, 350 m². Ultra-luxury.'} },

  /* ============================== PA ============================== */
  /* Boquete */
  { id:'pa-bq-1', country:'PA', region:'Boquete · Cerro Punta', type:'rural',
    name:'93.66 ha Development Land Boquete', sizeM2:936612, bedrooms:0, priceUSD:0,
    status:'available', source:'LuxuryEstate · Panama', broker:'Boquete land specialist',
    url:'https://www.luxuryestate.com/p130035231-land-for-sale-boquete',
    areaUrl:'https://www.luxuryestate.com/panama/provincia-de-chiriqui/distrito-boquete',
    photo:null,
    notes:{es:'93.66 hectáreas a 2,500m. Agricultura activa + bosque virgen. Solo 4×4.',
           en:'93.66 ha at 2,500m. Active agriculture + virgin forest. 4×4 access only.'} },
  { id:'pa-bq-2', country:'PA', region:'Alto Boquete', type:'rural',
    name:'Alto Boquete Building Land', sizeM2:0, bedrooms:0, priceUSD:0,
    status:'available', source:'LuxuryEstate · Panama', broker:'Boquete land specialist',
    url:'https://www.luxuryestate.com/p130829159-land-for-sale-alto-boquete',
    areaUrl:'https://www.luxuryestate.com/panama/provincia-de-chiriqui/distrito-boquete',
    photo:null,
    notes:{es:'Lote constructivo Alto Boquete, suelo fértil cultivable.',
           en:'Alto Boquete building lot on fertile cultivable soil.'} }
],

/* =============================================================
   ADMIN CONTACTS — gov offices for land due-diligence
   ============================================================= */
ADMIN: [
  { country:'MX', region:'CDMX', type:'registro', name:'Registro Público de la Propiedad CDMX',
    contact:'Mariano Escobedo 446, Anzures · +52 55 4334 4500',
    notes:{es:'Liens y antecedentes propiedad CDMX. 5 días hábiles certificación.', en:'CDMX property liens and history. 5-day certification.'} },
  { country:'MX', region:'CDMX', type:'catastro', name:'Tesorería CDMX · Catastro',
    contact:'Calle Doctor Lavista 144 · trámite en línea sat.cdmx.gob.mx',
    notes:{es:'Predial + valor catastral. Verificar al-corriente antes compra.', en:'Property tax + cadastral value. Verify up-to-date before purchase.'} },
  { country:'MX', region:'Tulum · QR', type:'planning', name:'Dirección de Desarrollo Urbano Tulum',
    contact:'Palacio Municipal Tulum',
    notes:{es:'Crítico — zonificación Tulum cambió 2024. Restricciones costeras + Sian Ka\'an buffer.', en:'Critical — Tulum zoning changed 2024. Coastal + Sian Ka\'an buffer restrictions.'} },
  { country:'MX', region:'CDMX', type:'notary', name:'Notario #19 (Roma)', contact:'Dr. Roberto Vázquez · +52 55 5564 1188',
    notes:{es:'English-speaking. Honest. Recomendado para compras Roma/Condesa.', en:'English-speaking. Honest. Recommended Roma/Condesa.'} },
  { country:'CO', region:'Medellín', type:'registro', name:'Oficina de Registro de Instrumentos Públicos',
    contact:'Calle 51 # 50-32, Centro · 444-2700',
    notes:{es:'Inscripción título. 15 días hábiles. Boleta fiscal 1% del precio.', en:'Title registration. 15 business days. 1% transfer tax.'} },
  { country:'CO', region:'Medellín', type:'catastro', name:'Catastro Municipal Medellín',
    contact:'Calle 44 # 52-165 · medellín.gov.co/catastro',
    notes:{es:'Avalúo catastral + impuesto predial. Verificar paz y salvo vendedor.', en:'Cadastral value + property tax. Verify seller paz y salvo.'} },
  { country:'CO', region:'Cartagena', type:'planning', name:'Curaduría Urbana Cartagena',
    contact:'Plaza San Diego · 6645-3322',
    notes:{es:'Patrimonio histórico — restricciones reforma estrictas Centro+Getsemaní.', en:'Historic heritage — strict renovation restrictions Centro+Getsemaní.'} },
  { country:'CO', region:'Medellín', type:'notary', name:'Notaría 25 Medellín',
    contact:'Calle 49 # 50-21',
    notes:{es:'Escritura pública compraventa. Bilingüe disponible.', en:'Public sale deed. Bilingual available.'} },
  { country:'BR', region:'Bahia · Trancoso', type:'registro', name:'Cartório de Registro de Imóveis Porto Seguro',
    contact:'Praça Pero Campos de Tourinho · Porto Seguro',
    notes:{es:'Cartório regional para Trancoso. Lentitud histórica.', en:'Regional cartório for Trancoso. Historically slow.'} },
  { country:'BR', region:'Rio · Leblon', type:'registro', name:'4º Cartório de Registro de Imóveis RJ',
    contact:'Av. Rio Branco 156, Centro RJ',
    notes:{es:'Registro Leblon + Ipanema + Copacabana. Despachante recomendado.', en:'Leblon + Ipanema + Copacabana registry. Despachante recommended.'} },
  { country:'BR', region:'Bahia · Trancoso', type:'planning', name:'Secretaria de Meio Ambiente Trancoso',
    contact:'Vía Prefeitura Porto Seguro',
    notes:{es:'CRÍTICO — restricciones ambientales Costa do Descobrimento. Construcción altura limitada.', en:'CRITICAL — Discovery Coast environmental restrictions. Height-limited construction.'} },
  { country:'BR', region:'São Paulo', type:'notary', name:'Tabelionato de Notas Conde Matarazzo SP',
    contact:'Av. Paulista · agendar online',
    notes:{es:'Escritura compra estados nordeste vía SP. Tax-eficiente.', en:'Northeast purchase deeds via SP. Tax-efficient.'} },
  { country:'AR', region:'BA · CABA', type:'registro', name:'Registro de la Propiedad Inmueble CABA',
    contact:'Av. Belgrano 1130 · 4135-9100',
    notes:{es:'Inscripción escritura. Tiempos mejorados post-Milei.', en:'Deed registration. Times improved post-Milei.'} },
  { country:'AR', region:'BA · CABA', type:'planning', name:'Agencia Gubernamental de Control · GCBA',
    contact:'Tte. Gral. Perón 2933',
    notes:{es:'Habilitación uso comercial / vivienda. Importante si Sora compra para Airbnb.', en:'Commercial/residential use clearance. Important if Sora buys for Airbnb.'} },
  { country:'AR', region:'BA · CABA', type:'notary', name:'Escribanía Belgrano (Notaría #234 ejemplo)',
    contact:'consultar Colegio Escribanos CABA',
    notes:{es:'Escritura + recibe USD billete. CRÍTICO — la transacción real es cash USD on the table.', en:'Deed + receives physical USD. CRITICAL — real transaction is cash USD on the table.'} },
  { country:'AR', region:'Mendoza', type:'planning', name:'DGI Mendoza · uso suelo viñedo',
    contact:'Casa de Gobierno Mendoza',
    notes:{es:'Cambio uso suelo viñedo a turismo rural. Permiso especial.', en:'Vineyard-to-rural-tourism use change. Special permit.'} },
  { country:'CR', region:'Nicoya', type:'registro', name:'Registro Nacional CR · Liberia',
    contact:'Liberia, Guanacaste · rnpdigital.com',
    notes:{es:'Registro propiedades Nicoya cantón. Digital + ágil.', en:'Nicoya cantón property registry. Digital + agile.'} },
  { country:'CR', region:'Nosara', type:'planning', name:'Municipalidad Nicoya · Planificación Urbana',
    contact:'Palacio Municipal Nicoya',
    notes:{es:'Zonificación Blue Zone Nosara. Restricciones eco.', en:'Nosara Blue Zone zoning. Eco restrictions.'} },
  { country:'CR', region:'San José', type:'notary', name:'Notariado Costarricense',
    contact:'Colegio Notarial CR',
    notes:{es:'Cualquier notario público acreditado. Escritura segregación lote común.', en:'Any accredited public notary. Lot-segregation deed common.'} },
  { country:'PE', region:'Lima', type:'registro', name:'SUNARP · Zona Registral IX Lima',
    contact:'Av. Salaverry 2890, San Isidro',
    notes:{es:'Inscripción título. 15 días.', en:'Title registration. 15 days.'} },
  { country:'PE', region:'Cusco', type:'planning', name:'Municipalidad Cusco · Dirección Urbanismo',
    contact:'Plaza Regocijo · Cusco',
    notes:{es:'Valle Sagrado patrimonio UNESCO restricciones construcción.', en:'Sacred Valley UNESCO heritage construction restrictions.'} },
  { country:'PE', region:'Lima', type:'notary', name:'Notario Aparicio (Miraflores)',
    contact:'Av. Pardo Miraflores',
    notes:{es:'English-speaking. Compraventas extranjeros.', en:'English-speaking. Foreign purchases.'} },
  { country:'CL', region:'Santiago', type:'registro', name:'Conservador de Bienes Raíces Santiago',
    contact:'Morandé 440, Centro Santiago',
    notes:{es:'Inscripción. Sistema chileno bien organizado.', en:'Registration. Well-organized Chilean system.'} },
  { country:'CL', region:'Santiago', type:'notary', name:'Notaría 5 Santiago Centro',
    contact:'consultar Asociación Notarios Chile',
    notes:{es:'Escritura. Sistema notarial CL es uno de los mejores LATAM.', en:'Deed. CL notarial system is one of LATAM\'s best.'} },
  { country:'CL', region:'San Pedro Atacama', type:'planning', name:'Municipalidad San Pedro · Obras',
    contact:'Plaza San Pedro',
    notes:{es:'Restricción arqueológica + altura. Permisos lentos.', en:'Archaeological + height restriction. Slow permits.'} },
  { country:'UY', region:'Maldonado', type:'registro', name:'Registro de la Propiedad Punta del Este',
    contact:'Punta del Este, Av. Gorlero',
    notes:{es:'Sistema ágil. UY tiene seguridad jurídica top LATAM.', en:'Agile system. UY has top LATAM legal certainty.'} },
  { country:'UY', region:'Maldonado', type:'planning', name:'Intendencia Maldonado · Planificación',
    contact:'Av. Roosevelt esq. Mendoza · Maldonado',
    notes:{es:'José Ignacio + Punta zonificación. Restricciones playa.', en:'José Ignacio + Punta zoning. Beach restrictions.'} },
  { country:'UY', region:'Montevideo', type:'notary', name:'Escribanía Avda. Italia',
    contact:'consultar Asociación de Escribanos UY',
    notes:{es:'Escritura. UY notarial es highly trusted.', en:'Deed. UY notarial is highly trusted.'} },
  { country:'PA', region:'Boquete', type:'registro', name:'Registro Público Panamá · Sucursal David',
    contact:'David, Chiriquí',
    notes:{es:'Inscripción Boquete + Volcán + David. Sistema PA dolarizado limpio.', en:'Boquete + Volcán + David registration. Clean dollarized PA system.'} },
  { country:'PA', region:'Boquete', type:'planning', name:'Municipio Boquete · Urbanismo',
    contact:'Bajo Boquete · Av. Central',
    notes:{es:'Permiso construcción finca. Coordinar con alcaldesa Yipsy Méndez.', en:'Finca construction permit. Coordinate with Mayor Yipsy Méndez.'} },
  { country:'PA', region:'Bocas del Toro', type:'planning', name:'ANATI · Autoridad Nacional Tierras',
    contact:'Bocas Town',
    notes:{es:'CRÍTICO Bocas — tierras concesión vs título. Verificar antes compra isla.', en:'CRITICAL Bocas — concession vs title land. Verify before island purchase.'} },
  { country:'PA', region:'Panamá City', type:'notary', name:'Notaría 1 Panamá', contact:'Calle 50',
    notes:{es:'Escritura. PA notarial system fast.', en:'Deed. PA notarial system fast.'} }
],

/* ===========================================================
   SEARCH PORTALS · Entry & mid-tier inventory by country
   Each entry is a pre-filtered search URL on a real portal.
   Click → live listings under the target price. No fabricated
   URLs. These are the platforms locals + foreigners actually
   use to find affordable property in each market.
   =========================================================== */
PORTALS: [
  /* ============================== MX ============================== */
  { country:'MX', region:'Tulum', tier:'entry', priceCapUSD:300000, type:'apartment',
    portal:'Inmuebles24', url:'https://www.inmuebles24.com/departamentos-en-venta-en-tulum-hasta-300000-dolares.html',
    notes:{es:'Departamentos Aldea Zama / La Veleta < $300K — buen rendimiento renta vacacional, fideicomiso requerido.',
           en:'Aldea Zama / La Veleta apartments < $300K — strong vacation-rental yield, fideicomiso required.'} },
  { country:'MX', region:'Tulum', tier:'mid', priceCapUSD:600000, type:'house',
    portal:'Vivanuncios', url:'https://www.vivanuncios.com.mx/s-casas-en-venta/tulum/v1c1097l10169p1?ms=200_000%2C600_000',
    notes:{es:'Casas $200-600K. Zona Aldea Zama / Bahía Príncipe / Tulum centro.',
           en:'Houses $200-600K. Aldea Zama / Bahía Príncipe / Tulum center.'} },
  { country:'MX', region:'Mérida', tier:'entry', priceCapUSD:250000, type:'house',
    portal:'Inmuebles24', url:'https://www.inmuebles24.com/casas-en-venta-en-merida-hasta-250000-dolares.html',
    notes:{es:'Casonas coloniales centro Mérida < $250K. Hub colonial calidad-precio top LATAM.',
           en:'Colonial casonas Mérida center < $250K. Best LATAM colonial value-for-price.'} },
  { country:'MX', region:'San Miguel de Allende', tier:'mid', priceCapUSD:500000, type:'house',
    portal:'Vivanuncios', url:'https://www.vivanuncios.com.mx/s-casas-en-venta/san-miguel-de-allende-gto/v1c1097l10166p1?ms=200_000%2C500_000',
    notes:{es:'SMA segunda categoría — fuera del centro histórico pero dentro del municipio. $200-500K.',
           en:'SMA second tier — outside historic center but within municipality. $200-500K.'} },
  { country:'MX', region:'CDMX · Roma/Condesa', tier:'mid', priceCapUSD:450000, type:'apartment',
    portal:'Inmuebles24', url:'https://www.inmuebles24.com/departamentos-en-venta-en-roma-norte-hasta-450000-dolares.html',
    notes:{es:'Roma Norte / Condesa departamentos 1-2BR. Mercado más resiliente CDMX.',
           en:'Roma Norte / Condesa 1-2BR apartments. CDMX most resilient market.'} },

  /* ============================== CO ============================== */
  { country:'CO', region:'Medellín · El Poblado', tier:'entry', priceCapUSD:200000, type:'apartment',
    portal:'Fincaraíz', url:'https://www.fincaraiz.com.co/apartamentos/venta/el-poblado/medellin?precio=hasta-200000-dolares',
    notes:{es:'El Poblado / Provenza departamentos 1-2BR < $200K. Renta corta vacacional generosa.',
           en:'El Poblado / Provenza 1-2BR apartments < $200K. Generous short-term rental yields.'} },
  { country:'CO', region:'Medellín · Laureles', tier:'entry', priceCapUSD:150000, type:'apartment',
    portal:'Metrocuadrado', url:'https://www.metrocuadrado.com/apartamento/venta/medellin/laureles-estadio',
    notes:{es:'Laureles departamentos < $150K. Barrio en alza, mejor valor q El Poblado.',
           en:'Laureles apartments < $150K. Rising neighborhood, better value than El Poblado.'} },
  { country:'CO', region:'Pereira / Quindío', tier:'entry', priceCapUSD:200000, type:'rural',
    portal:'Fincaraíz', url:'https://www.fincaraiz.com.co/fincas/venta/pereira',
    notes:{es:'Fincas cafeteras Eje Cafetero $50-200K. Tierra agrícola + casa.',
           en:'Eje Cafetero coffee fincas $50-200K. Agricultural land + house.'} },
  { country:'CO', region:'Cartagena · Getsemaní', tier:'mid', priceCapUSD:400000, type:'house',
    portal:'Fincaraíz', url:'https://www.fincaraiz.com.co/casas/venta/getsemani/cartagena',
    notes:{es:'Casas coloniales Getsemaní / centro histórico $200-400K. Restauración con upside.',
           en:'Getsemaní / historic center colonial houses $200-400K. Restoration with upside.'} },
  { country:'CO', region:'Cartagena · Manga/Bocagrande', tier:'mid', priceCapUSD:300000, type:'apartment',
    portal:'Ciencuadras', url:'https://www.ciencuadras.com/apartamento-en-venta/cartagena',
    notes:{es:'Departamentos modernos Manga / Bocagrande $150-300K. Vista mar / bahía.',
           en:'Modern Manga / Bocagrande apartments $150-300K. Ocean / bay view.'} },

  /* ============================== AR ============================== */
  { country:'AR', region:'Buenos Aires · Palermo', tier:'entry', priceCapUSD:200000, type:'apartment',
    portal:'ZonaProp', url:'https://www.zonaprop.com.ar/departamentos-venta-palermo-hasta-200000-dolares.html',
    notes:{es:'Palermo Hollywood / Soho departamentos 1-2BR < $200K USD cash. Mercado en USD por crisis peso.',
           en:'Palermo Hollywood / Soho 1-2BR apartments < $200K USD cash. USD-denominated due to peso crisis.'} },
  { country:'AR', region:'Buenos Aires · Recoleta', tier:'mid', priceCapUSD:350000, type:'apartment',
    portal:'Argenprop', url:'https://www.argenprop.com/departamentos/venta/recoleta',
    notes:{es:'Recoleta apartamentos clásicos pre-1950 $150-350K. Calidad/precio mejor LATAM.',
           en:'Recoleta classic pre-1950 apartments $150-350K. Best LATAM quality-for-price.'} },
  { country:'AR', region:'Mendoza · Luján de Cuyo', tier:'mid', priceCapUSD:400000, type:'rural',
    portal:'ZonaProp', url:'https://www.zonaprop.com.ar/inmuebles-venta-lujan-de-cuyo.html',
    notes:{es:'Pequeñas bodegas y fincas vitivinícolas Mendoza $150-400K. Restricción extranjero rural — 1000ha max.',
           en:'Small vineyards and wine fincas Mendoza $150-400K. Rural foreign restriction — 1000ha max.'} },
  { country:'AR', region:'Bariloche · Patagonia', tier:'mid', priceCapUSD:300000, type:'house',
    portal:'Argenprop', url:'https://www.argenprop.com/casas/venta/bariloche',
    notes:{es:'Cabañas Bariloche / Villa La Angostura $100-300K. Vista lago / montaña.',
           en:'Bariloche / Villa La Angostura cabins $100-300K. Lake / mountain views.'} },

  /* ============================== UY ============================== */
  { country:'UY', region:'Punta del Este', tier:'mid', priceCapUSD:400000, type:'apartment',
    portal:'InfoCasas', url:'https://www.infocasas.com.uy/venta/apartamentos/punta-del-este/hasta-400000-dolares',
    notes:{es:'Apartamentos Punta + La Brava $200-400K. Seguridad jurídica top LATAM.',
           en:'Punta + La Brava apartments $200-400K. Top LATAM legal certainty.'} },
  { country:'UY', region:'José Ignacio', tier:'mid', priceCapUSD:500000, type:'house',
    portal:'InfoCasas', url:'https://www.infocasas.com.uy/venta/casas/jose-ignacio',
    notes:{es:'Casas José Ignacio $250-500K. Punta del Este boho-premium.',
           en:'José Ignacio houses $250-500K. Punta del Este boho-premium.'} },

  /* ============================== PE ============================== */
  { country:'PE', region:'Lima · Barranco/Miraflores', tier:'entry', priceCapUSD:250000, type:'apartment',
    portal:'Adondevivir', url:'https://www.adondevivir.com/departamentos-en-venta-en-barranco-precio-en-soles-hasta-1000000.html',
    notes:{es:'Barranco / Miraflores departamentos 1-2BR < $250K. Bohemio + premium.',
           en:'Barranco / Miraflores 1-2BR apartments < $250K. Bohemian + premium.'} },
  { country:'PE', region:'Cusco · Centro', tier:'entry', priceCapUSD:200000, type:'house',
    portal:'Urbania', url:'https://urbania.pe/buscar/venta-de-departamentos-en-cusco',
    notes:{es:'Cusco casas coloniales / departamentos modernos $80-200K. Restricción extranjero 50km frontera.',
           en:'Cusco colonial houses / modern apts $80-200K. 50km border foreign restriction.'} },

  /* ============================== CL ============================== */
  { country:'CL', region:'Santiago · Providencia/Las Condes', tier:'mid', priceCapUSD:350000, type:'apartment',
    portal:'Portal Inmobiliario', url:'https://www.portalinmobiliario.com/venta/departamento/santiago-rm-metropolitana',
    notes:{es:'Departamentos Providencia / Las Condes $150-350K. CBR independiente da certeza única.',
           en:'Providencia / Las Condes apartments $150-350K. Independent CBR gives unique certainty.'} },
  { country:'CL', region:'Casablanca Valley', tier:'mid', priceCapUSD:500000, type:'rural',
    portal:'Portal Inmobiliario', url:'https://www.portalinmobiliario.com/venta/casa/casablanca-valparaiso',
    notes:{es:'Parcelas vitivinícolas Casablanca $150-500K. Cerca Santiago + Viña del Mar.',
           en:'Casablanca vineyard plots $150-500K. Near Santiago + Viña del Mar.'} },

  /* ============================== CR ============================== */
  { country:'CR', region:'Nicoya · Santa Teresa/Tamarindo', tier:'entry', priceCapUSD:250000, type:'lot',
    portal:'Encuentra24', url:'https://www.encuentra24.com/costa-rica-es/bienes-raices-venta-de-propiedades-venta-de-lotes/nicoya',
    notes:{es:'Lotes Santa Teresa / Mal País / Tamarindo $50-250K. Surf coast. ZMT 200m costera restringida.',
           en:'Santa Teresa / Mal País / Tamarindo lots $50-250K. Surf coast. 200m maritime zone restricted.'} },
  { country:'CR', region:'Atenas / Central Valley', tier:'mid', priceCapUSD:400000, type:'house',
    portal:'Encuentra24', url:'https://www.encuentra24.com/costa-rica-es/bienes-raices-venta-de-propiedades/atenas',
    notes:{es:'Casas Atenas / Grecia / Sarchí $150-400K. Valle central, clima perfecto, hub expat.',
           en:'Atenas / Grecia / Sarchí houses $150-400K. Central valley, perfect climate, expat hub.'} },

  /* ============================== PA ============================== */
  { country:'PA', region:'Boquete · Chiriquí', tier:'entry', priceCapUSD:250000, type:'house',
    portal:'Encuentra24', url:'https://www.encuentra24.com/panama-es/bienes-raices-venta-de-propiedades/boquete',
    notes:{es:'Casas Boquete $80-250K. Highlands frescos. Hub expat veterano.',
           en:'Boquete houses $80-250K. Cool highlands. Veteran expat hub.'} },
  { country:'PA', region:'Bocas del Toro · Isla Colón', tier:'entry', priceCapUSD:200000, type:'house',
    portal:'Encuentra24', url:'https://www.encuentra24.com/panama-es/bienes-raices-venta-de-propiedades/bocas-del-toro',
    notes:{es:'Bocas casas + lotes $50-200K. CRÍTICO verificar título vs Rights of Possession.',
           en:'Bocas houses + lots $50-200K. CRITICAL verify title vs Rights of Possession.'} },
  { country:'PA', region:'Casco Viejo · Panamá', tier:'mid', priceCapUSD:500000, type:'apartment',
    portal:'Encuentra24', url:'https://www.encuentra24.com/panama-es/bienes-raices-venta-de-propiedades-apartamentos/casco-viejo',
    notes:{es:'Departamentos Casco Viejo $250-500K. Restauración con subsidio Patrimonio.',
           en:'Casco Viejo apartments $250-500K. Restoration with Heritage subsidy.'} },

  /* ============================== BR ============================== */
  { country:'BR', region:'Florianópolis · Santa Catarina', tier:'mid', priceCapUSD:400000, type:'apartment',
    portal:'VivaReal', url:'https://www.vivareal.com.br/venda/santa-catarina/florianopolis/apartamento_residencial/',
    notes:{es:'Florianópolis apartamentos $150-400K USD (~R$1M). Mejor calidad de vida BR.',
           en:'Florianópolis apartments $150-400K USD (~R$1M). BR best quality of life.'} },
  { country:'BR', region:'Trancoso · Bahia', tier:'mid', priceCapUSD:500000, type:'house',
    portal:'VivaReal', url:'https://www.vivareal.com.br/venda/bahia/trancoso/',
    notes:{es:'Trancoso casas $200-500K. Pueblo boho-premium. Costa: sin restricción extranjero.',
           en:'Trancoso houses $200-500K. Boho-premium village. Coast: no foreign restriction.'} },

  /* ============================== EC ============================== */
  { country:'EC', region:'Cuenca · Centro histórico', tier:'entry', priceCapUSD:200000, type:'house',
    portal:'Plusvalia', url:'https://www.plusvalia.com/casas-en-venta-en-cuenca.html',
    notes:{es:'Cuenca casas coloniales $80-200K. Hub expat consolidado, costo de vida bajo.',
           en:'Cuenca colonial houses $80-200K. Consolidated expat hub, low cost of living.'} },

  /* ============================== DO ============================== */
  { country:'DO', region:'Las Terrenas · Samaná', tier:'entry', priceCapUSD:300000, type:'house',
    portal:'Encuentra24', url:'https://www.encuentra24.com/republica-dominicana-es/bienes-raices-venta-de-propiedades/las-terrenas',
    notes:{es:'Las Terrenas casas $100-300K. Sistema Torrens da certeza máxima LATAM.',
           en:'Las Terrenas houses $100-300K. Torrens system gives max LATAM certainty.'} },
  { country:'DO', region:'Cabarete · Sosúa', tier:'entry', priceCapUSD:250000, type:'house',
    portal:'Encuentra24', url:'https://www.encuentra24.com/republica-dominicana-es/bienes-raices-venta-de-propiedades/cabarete',
    notes:{es:'Cabarete / Sosúa $80-250K. Kite + surf coast, mercado expat maduro.',
           en:'Cabarete / Sosúa $80-250K. Kite + surf coast, mature expat market.'} },

  /* ============================== VE ============================== */
  { country:'VE', region:'Margarita · Pampatar', tier:'entry', priceCapUSD:150000, type:'house',
    portal:'Mercado Libre', url:'https://inmuebles.mercadolibre.com.ve/casas/venta/margarita',
    notes:{es:'Margarita oportunidades $40-150K USD cash. Mercado dolarizado de facto.',
           en:'Margarita opportunities $40-150K USD cash. De facto dollarized market.'} }
]

};
