/* =============================================================
   SORA · OPS DATA · internal team only
   Locations to host at + contacts to target across 15 LATAM chapters.
   Both arrays loaded as globals; admin edits persist in localStorage.
   ============================================================= */

window.SORA_LOCATIONS = [
  /* ============================== MX ============================== */
  { id:'mx-pujol', country:'MX', region:'CDMX', name:'Pujol',
    type:'restaurant', capacity:'12 mesa privada', tier:5, status:'pursuing',
    contact:'Eduardo Eguiarte · GM', address:'Tennyson 133, Polanco',
    notes:{es:'Mesa privada de 12 ya negociada en preliminar. Reserva blindada 60 días antes. Maridaje mezcal opcional.',
           en:'Private 12-top in preliminary talks. Locked booking 60 days ahead. Optional mezcal pairing.'} },
  { id:'mx-quintonil', country:'MX', region:'CDMX', name:'Quintonil',
    type:'restaurant', capacity:'14 chef table', tier:5, status:'target',
    contact:'Alejandra Flores · sommelier-partner', address:'Av. Isaac Newton 55, Polanco',
    notes:{es:'Cuarto privado en piso superior. Compite con Pujol — usar como alternativa para clientes que ya cenaron Pujol.',
           en:'Private upstairs room. Competes with Pujol — use as alternative for clients who\'ve already dined Pujol.'} },
  { id:'mx-casa-polanco', country:'MX', region:'CDMX', name:'Casa Polanco',
    type:'hotel', capacity:'19 rooms', tier:5, status:'partnered',
    contact:'Mauricio Camou · GM', address:'Polanco V Sección',
    notes:{es:'Hotel base para weekends CDMX Roma/Polanco. Rate Sora 15% off rack en bloque de 6+.',
           en:'Base hotel for CDMX Roma/Polanco weekends. 15% off rack rate on 6+ room block.'} },
  { id:'mx-andaz-condesa', country:'MX', region:'CDMX', name:'Andaz Condesa',
    type:'hotel', capacity:'213 rooms', tier:4, status:'pursuing',
    contact:'Hyatt group sales', address:'Av. Veracruz 102, Condesa',
    notes:{es:'Alternativa más comercial cuando Casa Polanco está lleno. Rooftop bueno para welcome drinks.',
           en:'More commercial alternative when Casa Polanco is full. Good rooftop for welcome drinks.'} },
  { id:'mx-kurimanzutto', country:'MX', region:'CDMX', name:'Galería Kurimanzutto',
    type:'venue', capacity:'private tour 12', tier:4, status:'pursuing',
    contact:'Lorena Garza · curator relations', address:'Gob. Rafael Rebollar 94, San Miguel Chapultepec',
    notes:{es:'Tour curado privado con curadora. Lunes cerrados al público — slot perfecto para nosotros.',
           en:'Curated private tour with curator. Mondays closed to public — perfect slot for us.'} },
  { id:'mx-habitas-tulum', country:'MX', region:'Tulum', name:'Habitas Tulum',
    type:'hotel', capacity:'32 villas', tier:5, status:'partnered',
    contact:'Lior Yaffe · group sales', address:'Carretera Tulum-Punta Allen Km 11',
    notes:{es:'Bloqueo de 12 villas para Sora 4 weekends/año confirmado. 25% commission to Sora.',
           en:'12-villa block for Sora 4 weekends/year confirmed. 25% commission to Sora.'} },
  { id:'mx-azulik', country:'MX', region:'Tulum', name:'Azulik',
    type:'hotel', capacity:'48 villas', tier:5, status:'target',
    contact:'Booking dept — direct only', address:'Carretera Tulum-Punta Allen Km 5',
    notes:{es:'Marca icónica pero precio extremo y servicio inconsistente. Usar para grupos premium 6-pax con expectativa alta.',
           en:'Iconic brand but extreme pricing and inconsistent service. Use for premium 6-pax groups with high expectation.'} },
  { id:'mx-rosewood-sma', country:'MX', region:'San Miguel de Allende', name:'Rosewood San Miguel',
    type:'hotel', capacity:'67 rooms', tier:5, status:'pursuing',
    contact:'Patricia Ferro · DOSM', address:'Nemesio Diez 11, San Miguel de Allende',
    notes:{es:'El boutique #1 de SMA. Festival Día de Muertos sold-out Sept en adelante — bloquear con 9 meses.',
           en:'#1 boutique in SMA. Day of the Dead festival sold-out from Sept onwards — block 9 months ahead.'} },
  { id:'mx-bruma-valle', country:'MX', region:'Valle de Guadalupe', name:'Bruma Wine Garden',
    type:'hotel', capacity:'15 villas', tier:5, status:'target',
    contact:'Bruma direct', address:'Carretera El Tigre, Valle de Guadalupe',
    notes:{es:'Diseño extraordinario. Limita pax por capacidad — solo 12 max grupo Sora.',
           en:'Extraordinary design. Limits pax by capacity — only 12 max Sora group.'} },
  { id:'mx-encuentro-valle', country:'MX', region:'Valle de Guadalupe', name:'Encuentro Guadalupe',
    type:'hotel', capacity:'22 ecolofts', tier:4, status:'pursuing',
    contact:'Diego Hernández · GM', address:'Carretera Tecate-Ensenada Km 75',
    notes:{es:'Ecolofts brutalistas sobre la montaña. Excelente para fotografía. Restaurante propio.',
           en:'Brutalist ecolofts atop the mountain. Excellent for photography. In-house restaurant.'} },
  { id:'mx-casa-sandra', country:'MX', region:'Mazunte', name:'Casa Sandra',
    type:'hotel', capacity:'9 suites', tier:4, status:'target',
    contact:'Direct booking only', address:'Mazunte, Oaxaca',
    notes:{es:'Joya escondida en costa Oaxaca. Tomar todas las 9 suites para grupo Sora 12-16.',
           en:'Hidden gem on Oaxaca coast. Take all 9 suites for Sora group of 12-16.'} },
  { id:'mx-hotel-sin-nombre', country:'MX', region:'Oaxaca City', name:'Hotel Sin Nombre',
    type:'hotel', capacity:'14 rooms', tier:5, status:'target',
    contact:'Reservation desk', address:'Fiallo 102, Centro Histórico',
    notes:{es:'Boutique más interesante de Oaxaca City. Restaurante con chef Alejandro Ruiz.',
           en:'Most interesting boutique in Oaxaca City. Restaurant by chef Alejandro Ruiz.'} },

  /* ============================== CO ============================== */
  { id:'co-casa-san-agustin', country:'CO', region:'Cartagena', name:'Casa San Agustín',
    type:'hotel', capacity:'24 rooms', tier:5, status:'partnered',
    contact:'Catalina Pérez · group sales', address:'Calle de la Universidad 36-44, Centro',
    notes:{es:'Pieza ancla en Cartagena. Pool deck para welcome cocktail. Bloque 10 habitaciones Sora.',
           en:'Anchor piece in Cartagena. Pool deck for welcome cocktail. 10-room Sora block.'} },
  { id:'co-sofitel-santa-clara', country:'CO', region:'Cartagena', name:'Sofitel Legend Santa Clara',
    type:'hotel', capacity:'123 rooms', tier:5, status:'pursuing',
    contact:'Andrea Carrasquilla · DOSM', address:'Calle del Torno 39-29',
    notes:{es:'Ex-convento del siglo XVII. Mejor para grupos 16+. Cena en patio claustral es signature Sora.',
           en:'17th-century former convent. Best for 16+ groups. Cloister-patio dinner is Sora signature.'} },
  { id:'co-charlee-medellin', country:'CO', region:'Medellín', name:'The Charlee Hotel',
    type:'hotel', capacity:'42 suites', tier:4, status:'partnered',
    contact:'Camilo Mejía · sales', address:'Calle 9A # 37-16, El Poblado',
    notes:{es:'Rooftop legendario en Provenza. Discount Sora 18%. Anclar weekends Medellín aquí.',
           en:'Legendary rooftop in Provenza. 18% Sora discount. Anchor Medellín weekends here.'} },
  { id:'co-click-clack', country:'CO', region:'Medellín', name:'Click Clack Medellín',
    type:'hotel', capacity:'81 rooms', tier:4, status:'pursuing',
    contact:'Sebastián Ramírez · GM', address:'Cra. 37 # 8A-08',
    notes:{es:'Diseño tech-forward, juvenil. Buena alternativa al Charlee para grupos más activos.',
           en:'Tech-forward, youthful design. Good Charlee alternative for more active groups.'} },
  { id:'co-carmen-medellin', country:'CO', region:'Medellín', name:'Carmen',
    type:'restaurant', capacity:'12 chef table', tier:5, status:'pursuing',
    contact:'Rob Pevitts · chef-owner', address:'Cra. 36 # 10A-27, El Poblado',
    notes:{es:'Mejor mesa de chef Medellín. Rob escribe menú custom para grupos Sora 12+.',
           en:'Best chef\'s table Medellín. Rob writes custom menu for Sora 12+ groups.'} },
  { id:'co-bio-habitat', country:'CO', region:'Eje Cafetero', name:'Bio Habitat Hotel',
    type:'hotel', capacity:'12 cabañas', tier:4, status:'target',
    contact:'Direct only', address:'Vereda Cocora, Salento',
    notes:{es:'Cabañas en bosque nuboso. Excelente para silent retreats.',
           en:'Cloud-forest cabins. Excellent for silent retreats.'} },
  { id:'co-hacienda-bambusa', country:'CO', region:'Eje Cafetero', name:'Hacienda Bambusa',
    type:'hotel', capacity:'8 rooms', tier:5, status:'pursuing',
    contact:'Hacienda direct', address:'El Caimo, Quindío',
    notes:{es:'Finca de bambú con 200 ha. Toda la finca para grupo Sora — privacidad total.',
           en:'Bamboo finca on 200 ha. Whole finca for Sora group — total privacy.'} },
  { id:'co-bosko-guatape', country:'CO', region:'Guatapé', name:'Bosko',
    type:'hotel', capacity:'14 domos', tier:4, status:'partnered',
    contact:'María Lucía Calle · DOSM', address:'El Peñol, Antioquia',
    notes:{es:'Domos geodésicos sobre el embalse. Mesa del chef de Bosko es signature.',
           en:'Geodesic domes over the reservoir. Bosko chef\'s table is signature.'} },
  { id:'co-casa-sansara', country:'CO', region:'Tayrona', name:'Casa Sansara',
    type:'hotel', capacity:'10 villas', tier:5, status:'target',
    contact:'Direct only', address:'Costeño Beach, Magdalena',
    notes:{es:'Beach villa de lujo cerca de Tayrona. Yoga deck + chef privado.',
           en:'Beach luxury villa near Tayrona. Yoga deck + private chef.'} },

  /* ============================== BR ============================== */
  { id:'br-uxua-trancoso', country:'BR', region:'Trancoso', name:'UXUA Casa Hotel',
    type:'hotel', capacity:'14 casas', tier:5, status:'pursuing',
    contact:'Wilbert Das · founder', address:'Praça do Quadrado, Trancoso',
    notes:{es:'La pieza Sora en Trancoso — sin alternativa real al mismo nivel. Reservar 12+ meses antes.',
           en:'The Sora Trancoso piece — no real alternative at this level. Book 12+ months ahead.'} },
  { id:'br-janeiro-leblon', country:'BR', region:'Rio de Janeiro', name:'Janeiro Hotel',
    type:'hotel', capacity:'47 rooms', tier:5, status:'pursuing',
    contact:'Sales dept', address:'Av. Delfim Moreira 696, Leblon',
    notes:{es:'Frente al mar Leblon, rooftop con vista Pão de Açúcar. Mejor base Sora Río.',
           en:'Oceanfront Leblon, rooftop with Sugarloaf view. Best Sora Rio base.'} },
  { id:'br-belmond-copacabana', country:'BR', region:'Rio de Janeiro', name:'Belmond Copacabana Palace',
    type:'hotel', capacity:'239 rooms', tier:5, status:'target',
    contact:'Belmond group sales', address:'Av. Atlântica 1702',
    notes:{es:'Histórico, formal. Mejor para grupos más conservadores. Brunch dominical legendario.',
           en:'Historic, formal. Better for more conservative groups. Legendary Sunday brunch.'} },
  { id:'br-oteque', country:'BR', region:'Rio de Janeiro', name:'Oteque',
    type:'restaurant', capacity:'8 chef table', tier:5, status:'pursuing',
    contact:'Alberto Landgraf · chef-owner', address:'Rua Conde de Irajá 581, Botafogo',
    notes:{es:'Dos estrellas Michelin. Mesa de 8 max. Reservar con Sora 90 días.',
           en:'Two Michelin stars. 8-top max. Book through Sora 90 days ahead.'} },
  { id:'br-insolito-buzios', country:'BR', region:'Búzios', name:'Insólito Boutique',
    type:'hotel', capacity:'25 suites', tier:5, status:'target',
    contact:'Insólito direct', address:'Rua E-1 Lote 02, Praia da Ferradura',
    notes:{es:'Frente al mar Ferradura. Cada suite con piscina privada. Curaduría arte propia.',
           en:'Ferradura beachfront. Each suite with private pool. In-house art curation.'} },
  { id:'br-pousada-maravilha', country:'BR', region:'Fernando de Noronha', name:'Pousada Maravilha',
    type:'hotel', capacity:'8 bungalows', tier:5, status:'target',
    contact:'Maravilha direct', address:'BR-363, Fernando de Noronha',
    notes:{es:'Solo 8 bungalows = grupo entero. Vuelos limitados 6/día — bloquear con 6 meses.',
           en:'Only 8 bungalows = full group. Limited flights 6/day — block 6 months ahead.'} },
  { id:'br-vila-serrano', country:'BR', region:'Chapada Diamantina', name:'Vila Serrano',
    type:'hotel', capacity:'14 rooms', tier:3, status:'target',
    contact:'Vila Serrano direct', address:'Lençóis, Bahia',
    notes:{es:'Pousada base para Chapada. Cocina honesta, ubicación caminera.',
           en:'Base pousada for Chapada. Honest cuisine, walkable location.'} },
  { id:'br-praia-espelho', country:'BR', region:'Bahia', name:'Praia do Espelho',
    type:'beach', capacity:'private boat day', tier:5, status:'partnered',
    contact:'Silvinha (Restaurante Silvinha)', address:'Curuípe, Bahia',
    notes:{es:'Día privado en barco desde Trancoso. Almuerzo en Silvinha — fija de Sora.',
           en:'Private boat day from Trancoso. Lunch at Silvinha — Sora fixture.'} },

  /* ============================== AR ============================== */
  { id:'ar-faena-bsas', country:'AR', region:'Buenos Aires', name:'Faena Hotel',
    type:'hotel', capacity:'88 rooms', tier:5, status:'partnered',
    contact:'Carolina Casas · sales', address:'Marta Salotti 445, Puerto Madero',
    notes:{es:'Diseño Philippe Starck. Universo Faena 360°. Discount 12% bloques Sora 8+.',
           en:'Philippe Starck design. Faena Universe 360°. 12% discount on 8+ Sora blocks.'} },
  { id:'ar-casa-lucia', country:'AR', region:'Buenos Aires', name:'Casa Lucía',
    type:'hotel', capacity:'140 rooms', tier:4, status:'pursuing',
    contact:'Sales BWH Hotels group', address:'Av. de Mayo 825',
    notes:{es:'Casona restaurada barrio Monserrat. Vibe más auténtica que Faena. Cheaper.',
           en:'Restored mansion in Monserrat. More authentic vibe than Faena. Cheaper.'} },
  { id:'ar-don-julio', country:'AR', region:'Buenos Aires', name:'Don Julio Parrilla',
    type:'restaurant', capacity:'mesa privada 14', tier:5, status:'partnered',
    contact:'Pablo Rivero · chef-owner', address:'Guatemala 4699, Palermo',
    notes:{es:'#1 world\'s 50 best 2024. Mesa de 14 ya bloqueada Sora 4 fechas/año. Trato directo con Pablo.',
           en:'#1 world\'s 50 best 2024. 14-top already blocked Sora 4 dates/year. Direct deal with Pablo.'} },
  { id:'ar-tegui', country:'AR', region:'Buenos Aires', name:'Tegui',
    type:'restaurant', capacity:'chef counter 10', tier:5, status:'pursuing',
    contact:'Germán Martitegui · chef-owner', address:'Costa Rica 5852, Palermo',
    notes:{es:'Counter de chef. Buena alternativa cuando Don Julio no calza.',
           en:'Chef\'s counter. Good alternative when Don Julio doesn\'t fit.'} },
  { id:'ar-vines-uco', country:'AR', region:'Valle de Uco', name:'The Vines Resort & Spa',
    type:'hotel', capacity:'22 villas', tier:5, status:'pursuing',
    contact:'Andrea Beoletto · DOSM', address:'Ruta Provincial 94 Km 11, Tunuyán',
    notes:{es:'Casa por villa. Asado Siete Fuegos por Mallmann incluido. Anchor Mendoza.',
           en:'House per villa. Siete Fuegos asado by Mallmann included. Mendoza anchor.'} },
  { id:'ar-cavas-wine-lodge', country:'AR', region:'Luján de Cuyo', name:'Cavas Wine Lodge',
    type:'hotel', capacity:'18 villas', tier:5, status:'target',
    contact:'Cecilia Cariola · GM', address:'Costaflores s/n, Alto Agrelo',
    notes:{es:'Villas privadas con plunge pool individual. Más íntimo que The Vines.',
           en:'Private villas with individual plunge pool. More intimate than The Vines.'} },
  { id:'ar-llao-llao', country:'AR', region:'Bariloche', name:'Llao Llao Resort',
    type:'hotel', capacity:'205 rooms', tier:5, status:'target',
    contact:'Sales group dept', address:'Av. Bustillo Km 25, Bariloche',
    notes:{es:'Ícono nacional argentino. Anchor para weekend Patagonia Norte.',
           en:'Argentine national icon. Anchor for Patagonia Norte weekend.'} },
  { id:'ar-eolo-calafate', country:'AR', region:'El Calafate', name:'EOLO Patagonia Lodge',
    type:'hotel', capacity:'17 rooms', tier:5, status:'pursuing',
    contact:'EOLO direct', address:'RP 11 Km 23, Calafate',
    notes:{es:'Lodge en la estepa con vista al lago. Más íntimo que Eolo. Solo Sora dueño del lodge ciertas fechas.',
           en:'Steppe lodge with lake view. More intimate. Sora owns the lodge on select dates.'} },

  /* ============================== CR ============================== */
  { id:'cr-bodhi-tree', country:'CR', region:'Nosara', name:'Bodhi Tree Yoga Resort',
    type:'hotel', capacity:'34 rooms', tier:4, status:'partnered',
    contact:'Helena Lara · group sales', address:'Playa Guiones, Nosara',
    notes:{es:'Yoga ancla mundial. Schedule de 8 clases/día. Discount Sora 15% en bloque 12+.',
           en:'World yoga anchor. 8 classes/day schedule. 15% Sora discount on 12+ block.'} },
  { id:'cr-harmony-nosara', country:'CR', region:'Nosara', name:'Harmony Hotel',
    type:'hotel', capacity:'24 rooms', tier:5, status:'pursuing',
    contact:'Harmony direct', address:'Playa Guiones',
    notes:{es:'Eco-luxury, más adulto que Bodhi. Restaurante orgánico propio.',
           en:'Eco-luxury, more adult than Bodhi. Own organic restaurant.'} },
  { id:'cr-nantipa-st', country:'CR', region:'Santa Teresa', name:'Hotel Nantipa',
    type:'hotel', capacity:'15 rooms', tier:5, status:'target',
    contact:'Direct', address:'Playa Carmen, Santa Teresa',
    notes:{es:'El boutique con menos volumen turístico en ST. Diseño impecable.',
           en:'The boutique with least tourist volume in ST. Impeccable design.'} },
  { id:'cr-nayara-arenal', country:'CR', region:'La Fortuna', name:'Nayara Tented Camp',
    type:'hotel', capacity:'29 tents', tier:5, status:'pursuing',
    contact:'Sales dept', address:'La Fortuna, Alajuela',
    notes:{es:'Glamping de lujo con vista al Arenal. Cada tienda con plunge volcánico.',
           en:'Luxury glamping with Arenal view. Each tent with volcano-fed plunge.'} },
  { id:'cr-lapa-rios', country:'CR', region:'Osa Peninsula', name:'Lapa Rios Lodge',
    type:'hotel', capacity:'17 bungalows', tier:5, status:'target',
    contact:'Cayuga Collection sales', address:'Puerto Jiménez, Península de Osa',
    notes:{es:'Eco-lodge en Corcovado. Sora alquila lodge entero ciertas fechas.',
           en:'Eco-lodge in Corcovado. Sora rents the whole lodge on select dates.'} },
  { id:'cr-senda-monteverde', country:'CR', region:'Monteverde', name:'Senda Monteverde',
    type:'hotel', capacity:'29 suites', tier:5, status:'target',
    contact:'Sales dept', address:'Monteverde, Puntarenas',
    notes:{es:'Único eco-lujo verdadero en Monteverde. Spa con productos del bosque.',
           en:'Only true eco-luxury in Monteverde. Spa with forest products.'} },

  /* ============================== PE ============================== */
  { id:'pe-belmond-rio-sagrado', country:'PE', region:'Valle Sagrado', name:'Belmond Río Sagrado',
    type:'hotel', capacity:'23 casitas', tier:5, status:'pursuing',
    contact:'Belmond LATAM sales', address:'Carretera Cuzco-Urubamba Km 75',
    notes:{es:'Anchor Valle Sagrado. Aclimatación crítica antes de Cusco/Machu Picchu.',
           en:'Sacred Valley anchor. Critical altitude acclimatization before Cusco/MP.'} },
  { id:'pe-belmond-sanctuary', country:'PE', region:'Machu Picchu', name:'Belmond Sanctuary Lodge',
    type:'hotel', capacity:'31 rooms', tier:5, status:'target',
    contact:'Belmond LATAM sales', address:'Machu Picchu Pueblo',
    notes:{es:'Único hotel ADENTRO del parque MP. Entrada al amanecer sin crowd.',
           en:'Only hotel INSIDE MP park. Sunrise entry with no crowd.'} },
  { id:'pe-hotel-b-lima', country:'PE', region:'Lima', name:'Hotel B',
    type:'hotel', capacity:'17 rooms', tier:5, status:'partnered',
    contact:'Beto Cinader · GM', address:'Sáenz Peña 204, Barranco',
    notes:{es:'Casona Belle Époque en Barranco. Anclar weekends Lima aquí.',
           en:'Belle Époque mansion in Barranco. Anchor Lima weekends here.'} },
  { id:'pe-central', country:'PE', region:'Lima', name:'Central',
    type:'restaurant', capacity:'mesa privada 12', tier:5, status:'pursuing',
    contact:'Pia León · co-chef', address:'Av. Pedro de Osma 301, Barranco',
    notes:{es:'#1 mundo 50 best 2023. Reservar 60+ días. Sora tiene línea directa.',
           en:'#1 world 50 best 2023. Book 60+ days ahead. Sora has direct line.'} },
  { id:'pe-maido', country:'PE', region:'Lima', name:'Maido',
    type:'restaurant', capacity:'omakase counter 14', tier:5, status:'target',
    contact:'Mitsuharu Tsumura · chef', address:'Calle San Martín 399, Miraflores',
    notes:{es:'Nikkei fusion top mundo. Counter omakase 14. Reserva con 45 días.',
           en:'Top-world Nikkei fusion. 14-seat omakase counter. 45-day booking.'} },
  { id:'pe-tambopata-rc', country:'PE', region:'Tambopata', name:'Tambopata Research Center',
    type:'hotel', capacity:'18 rooms', tier:4, status:'target',
    contact:'Rainforest Expeditions', address:'Río Tambopata, Madre de Dios',
    notes:{es:'7 horas en bote desde Puerto Maldonado. Colpa de guacamayos a 100m.',
           en:'7-hour boat from Puerto Maldonado. Macaw clay-lick 100m away.'} },

  /* ============================== CL ============================== */
  { id:'cl-tierra-atacama', country:'CL', region:'Atacama', name:'Tierra Atacama Hotel & Spa',
    type:'hotel', capacity:'32 rooms', tier:5, status:'pursuing',
    contact:'Tierra Hotels sales', address:'Calle Domingo Atienza, San Pedro',
    notes:{es:'All-inclusive con excursiones. Mejor diseño en San Pedro.',
           en:'All-inclusive with excursions. Best design in San Pedro.'} },
  { id:'cl-explora-patagonia', country:'CL', region:'Torres del Paine', name:'Explora Patagonia',
    type:'hotel', capacity:'49 rooms', tier:5, status:'pursuing',
    contact:'Explora group sales', address:'Salto Chico, Torres del Paine',
    notes:{es:'Ícono mundial trekking. All-inclusive con guías. Anchor Patagonia.',
           en:'World trekking icon. All-inclusive with guides. Patagonia anchor.'} },
  { id:'cl-singular-santiago', country:'CL', region:'Santiago', name:'The Singular Santiago',
    type:'hotel', capacity:'62 rooms', tier:5, status:'target',
    contact:'Sales dept', address:'Merced 294, Lastarria',
    notes:{es:'Lastarria. Rooftop con vista a los Andes. Base de operaciones Sora-CL.',
           en:'Lastarria. Rooftop with Andes view. Sora-CL operations base.'} },
  { id:'cl-borago', country:'CL', region:'Santiago', name:'Boragó',
    type:'restaurant', capacity:'chef table 12', tier:5, status:'pursuing',
    contact:'Rodolfo Guzmán · chef', address:'Av. Nueva Costanera 3467, Vitacura',
    notes:{es:'Top 30 mundo. Endémicos chilenos. Sora reserva 60 días.',
           en:'World top 30. Chilean endemics. Sora books 60 days.'} },
  { id:'cl-lapostolle-residence', country:'CL', region:'Colchagua', name:'Lapostolle Residence',
    type:'hotel', capacity:'4 casitas', tier:5, status:'target',
    contact:'Direct', address:'Camino San Fernando, Apalta',
    notes:{es:'Solo 4 casitas — grupo Sora íntimo. Clos Apalta cata vertical incluida.',
           en:'Only 4 casitas — intimate Sora group. Clos Apalta vertical tasting included.'} },
  { id:'cl-explora-rapa-nui', country:'CL', region:'Isla de Pascua', name:'Explora Rapa Nui',
    type:'hotel', capacity:'30 rooms', tier:5, status:'target',
    contact:'Explora group sales', address:'Isla de Pascua',
    notes:{es:'Único all-inclusive serio en Rapa Nui. Vuelos LATAM 5h desde Santiago.',
           en:'Only serious all-inclusive on Rapa Nui. 5h LATAM flight from Santiago.'} },

  /* ============================== UY ============================== */
  { id:'uy-bahia-vik', country:'UY', region:'José Ignacio', name:'Bahía Vik',
    type:'hotel', capacity:'12 casas', tier:5, status:'partnered',
    contact:'Carrie Vik · founder', address:'Playa Mansa, José Ignacio',
    notes:{es:'Anchor Sora-UY. Cada casa diseñada por artista distinto. Bloquear Dic-Mar 12 meses antes.',
           en:'Sora-UY anchor. Each house designed by a different artist. Block Dec-Mar 12 months ahead.'} },
  { id:'uy-playa-vik', country:'UY', region:'José Ignacio', name:'Playa Vik',
    type:'hotel', capacity:'7 casas', tier:5, status:'pursuing',
    contact:'Vik Retreats sales', address:'Calle Los Cisnes, José Ignacio',
    notes:{es:'Hermana arquitectónica de Bahía. Menos pax — para grupos VIP 8-10.',
           en:'Architectural sister of Bahía. Fewer pax — for VIP 8-10 groups.'} },
  { id:'uy-la-huella', country:'UY', region:'José Ignacio', name:'Parador La Huella',
    type:'restaurant', capacity:'mesa de 16', tier:5, status:'partnered',
    contact:'Martín Pittaluga · co-owner', address:'Playa Brava, José Ignacio',
    notes:{es:'Restaurante más famoso Cono Sur. Sora tiene mesa de 16 garantizada Dic-Feb.',
           en:'Most famous restaurant Southern Cone. Sora has guaranteed 16-top Dec-Feb.'} },
  { id:'uy-garzon', country:'UY', region:'Garzón', name:'Hotel & Restaurante Garzón',
    type:'hotel', capacity:'5 suites', tier:5, status:'pursuing',
    contact:'Francis Mallmann · founder', address:'Pueblo Garzón',
    notes:{es:'5 suites = grupo Sora íntimo + cena Mallmann. Reservar Diciembre 14 meses antes.',
           en:'5 suites = intimate Sora group + Mallmann dinner. Book December 14 months ahead.'} },
  { id:'uy-grand-pde', country:'UY', region:'Punta del Este', name:'The Grand Hotel',
    type:'hotel', capacity:'108 rooms', tier:5, status:'target',
    contact:'Sales dept', address:'Calle 23 esq. Gorlero',
    notes:{es:'Re-apertura 2023. Diseño contemporáneo en pleno Punta. Bueno para grupos 14+.',
           en:'2023 reopening. Contemporary design right in Punta. Good for 14+ groups.'} },
  { id:'uy-bodega-garzon', country:'UY', region:'Garzón', name:'Bodega Garzón',
    type:'wine', capacity:'private tasting 16', tier:4, status:'pursuing',
    contact:'Christian Wylie · CEO', address:'Camino Garzón a Pueblo Edén',
    notes:{es:'Arquitectura premiada. Tannat + olivos. Cata privada con sommelier.',
           en:'Award-winning architecture. Tannat + olives. Private tasting with sommelier.'} },

  /* ============================== PA ============================== */
  { id:'pa-volcan-lodge', country:'PA', region:'Volcán', name:'Volcán Lodge',
    type:'hotel', capacity:'8 cabañas', tier:4, status:'partnered',
    contact:'Direct (Sora origin partner)', address:'Volcán, Chiriquí',
    notes:{es:'Lodge fundacional de Mirador Barú weekend. Ya tenemos rate de origen.',
           en:'Founding lodge for Mirador Barú weekend. We have origin rate locked.'} },
  { id:'pa-tranquilo-bay', country:'PA', region:'Bocas del Toro', name:'Tranquilo Bay',
    type:'hotel', capacity:'12 cabañas', tier:5, status:'partnered',
    contact:'Jay & Renee Vias · owners', address:'Isla Bastimentos',
    notes:{es:'Eco-lodge en isla privada. Caribbean Drift weekend ancla aquí.',
           en:'Eco-lodge on private island. Caribbean Drift weekend anchors here.'} },
  { id:'pa-finca-lerida', country:'PA', region:'Boquete', name:'Finca Lerida',
    type:'hotel', capacity:'25 rooms', tier:4, status:'partnered',
    contact:'Tuti Aguilera · GM', address:'Alto Quiel, Boquete',
    notes:{es:'Finca de café histórica. Geisha de origen. Sora ancla Coffee Sunrise.',
           en:'Historic coffee finca. Origin Geisha. Sora anchors Coffee Sunrise.'} },
  { id:'pa-bocas-bali', country:'PA', region:'Bocas del Toro', name:'Bocas Bali',
    type:'hotel', capacity:'10 villas overwater', tier:5, status:'pursuing',
    contact:'Direct', address:'Isla Solarte, Bocas',
    notes:{es:'Villas sobre el agua estilo Maldivas. Mejor opción premium en Bocas.',
           en:'Maldives-style overwater villas. Best premium option in Bocas.'} },
  { id:'pa-american-trade', country:'PA', region:'Casco Viejo', name:'American Trade Hotel',
    type:'hotel', capacity:'50 rooms', tier:4, status:'pursuing',
    contact:'Conservatorio sales', address:'Plaza Herrera, Casco Viejo',
    notes:{es:'Edificio histórico restaurado. Mejor anclar weekends Casco aquí.',
           en:'Restored historic building. Best to anchor Casco weekends here.'} },
  { id:'pa-casa-hassan', country:'PA', region:'Boquete', name:'Casa Hassan',
    type:'restaurant', capacity:'mesa privada 12', tier:4, status:'partnered',
    contact:'Chef Hassan · owner', address:'Bajo Boquete',
    notes:{es:'Cocina del chef Hassan, partner red local. Trato directo La Compañía.',
           en:'Chef Hassan kitchen, local network partner. Direct La Compañía deal.'} },

  /* ============================== VE ============================== */
  { id:'ve-renaissance-caracas', country:'VE', region:'Caracas', name:'Renaissance Caracas La Castellana',
    type:'hotel', capacity:'202 rooms', tier:4, status:'target',
    contact:'Marriott sales LATAM', address:'Av. Eugenio Mendoza, La Castellana',
    notes:{es:'Anchor Caracas eastside. Seguridad confirmada. Restaurante propio decente.',
           en:'Caracas eastside anchor. Confirmed security. Decent in-house restaurant.'} },
  { id:'ve-posada-la-cigala', country:'VE', region:'Los Roques', name:'Posada La Cigala',
    type:'hotel', capacity:'8 rooms', tier:5, status:'pursuing',
    contact:'Posada direct', address:'Gran Roque, Los Roques',
    notes:{es:'Toda la posada para grupo Sora 8. Vuelo charter desde Caracas.',
           en:'Whole posada for 8-Sora group. Charter flight from Caracas.'} },
  { id:'ve-alto-caracas', country:'VE', region:'Caracas', name:'Alto Restaurant',
    type:'restaurant', capacity:'mesa privada 14', tier:5, status:'pursuing',
    contact:'Carlos García · chef-owner', address:'Centro Comercial San Ignacio',
    notes:{es:'Top restaurante VE. Carlos es figura cultural. Mesa Sora 14 confirmada.',
           en:'Top VE restaurant. Carlos is cultural figure. Sora 14-top confirmed.'} },
  { id:'ve-waku-lodge', country:'VE', region:'Canaima', name:'Waku Lodge',
    type:'hotel', capacity:'14 rooms', tier:4, status:'target',
    contact:'Waku direct', address:'Parque Nacional Canaima',
    notes:{es:'Lodge frente a la laguna de Canaima. Salida en curiara al Salto Ángel.',
           en:'Lodge facing Canaima lagoon. Departure by canoe to Angel Falls.'} },
  { id:'ve-hacienda-aljorra', country:'VE', region:'Choroní', name:'Hacienda La Aljorra',
    type:'hotel', capacity:'9 rooms', tier:4, status:'target',
    contact:'Direct', address:'Choroní, Aragua',
    notes:{es:'Hacienda colonial reconvertida. Día a Chuao en lancha 30 min.',
           en:'Reconverted colonial hacienda. 30-min boat day to Chuao.'} },

  /* ============================== Tier 3 light coverage ============================== */
  { id:'do-amanera', country:'DO', region:'Cabrera', name:'Amanera',
    type:'hotel', capacity:'25 casitas', tier:5, status:'target',
    contact:'Aman group sales', address:'Playa Grande, Cabrera',
    notes:{es:'El Aman caribeño. Golf + océano + diseño minimalista. Caro pero ancla.',
           en:'The Caribbean Aman. Golf + ocean + minimalist design. Pricey but anchor.'} },
  { id:'gt-casa-palopo', country:'GT', region:'Lago Atitlán', name:'Casa Palopó',
    type:'hotel', capacity:'12 rooms', tier:5, status:'target',
    contact:'Direct', address:'Santa Catarina Palopó',
    notes:{es:'Vista absoluta al lago + 3 volcanes. Anchor weekend Atitlán.',
           en:'Total view of lake + 3 volcanoes. Atitlán weekend anchor.'} },
  { id:'gt-mesón-panza-verde', country:'GT', region:'Antigua', name:'Mesón Panza Verde',
    type:'hotel', capacity:'13 suites', tier:4, status:'target',
    contact:'Direct', address:'5a Avenida Sur 19, Antigua',
    notes:{es:'Casa colonial restaurada. Cocina propia bien valorada.',
           en:'Restored colonial house. Well-rated in-house kitchen.'} },
  { id:'ec-mashpi-lodge', country:'EC', region:'Mindo', name:'Mashpi Lodge',
    type:'hotel', capacity:'24 rooms', tier:5, status:'target',
    contact:'Metropolitan Touring', address:'Bosque Nublado Mashpi',
    notes:{es:'Eco-lodge premiado. Teleférico aerial sobre la canopy.',
           en:'Award-winning eco-lodge. Aerial cable car over the canopy.'} },
  { id:'pr-dorado-beach', country:'PR', region:'Dorado', name:'Dorado Beach Ritz Reserve',
    type:'hotel', capacity:'114 rooms', tier:5, status:'target',
    contact:'Ritz Reserve sales', address:'Dorado, Puerto Rico',
    notes:{es:'Único Ritz Reserve en LATAM. Anchor para weekends PR premium.',
           en:'Only Ritz Reserve in LATAM. Anchor for PR premium weekends.'} }
];

/* =============================================================
   CONTACTS — internal CRM
   ============================================================= */
window.SORA_CONTACTS = [
  /* ============================== MX ============================== */
  { id:'ct-mx-eduardo-eguiarte', country:'MX', name:'Eduardo Eguiarte', role:'hotelier',
    org:'Casa Polanco', region:'CDMX', email:'eduardo@casapolanco.mx', whatsapp:'+52 55 5281 7900',
    status:'partnered', lastTouched:'2026-04-12', owner:'Abraham',
    notes:{es:'GM hotel. Negociado bloque 6+ habitaciones con 15% off.', en:'Hotel GM. Negotiated 6+ room block with 15% off.'} },
  { id:'ct-mx-eduardo-garcia', country:'MX', name:'Eduardo García', role:'chef',
    org:'Máximo Bistrot', region:'CDMX', email:'reservaciones@maximobistrot.com.mx', whatsapp:'+52 55 5264 4291',
    status:'pursuing', lastTouched:'2026-03-08', owner:'Abraham',
    notes:{es:'Chef puede hospedar cenas privadas para Sora. Mesa 14 max.', en:'Chef can host Sora private dinners. 14-max table.'} },
  { id:'ct-mx-daniela-soto', country:'MX', name:'Daniela Soto-Innes', role:'chef',
    org:'Independiente · ex-Cosme', region:'CDMX / Tulum', email:'hola@danielasi.com', instagram:'@danielasi',
    status:'warm', lastTouched:'2026-02-19', owner:'Abdiel',
    notes:{es:'Disponible para colaboraciones pop-up Sora. Cobra premium pero el valor de marca paga.', en:'Available for Sora pop-up collabs. Premium fee but brand value pays.'} },
  { id:'ct-mx-felipe-romero', country:'MX', name:'Felipe Romero', role:'photographer',
    org:'Freelance · ex-Habitas content', region:'CDMX', email:'felipe@feliperomero.mx', instagram:'@feliperomero',
    status:'partnered', lastTouched:'2026-05-01', owner:'Abraham',
    notes:{es:'Fotógrafo de marca confirmado para todo weekend MX. $1.2k/día.', en:'Brand photographer confirmed for all MX weekends. $1.2k/day.'} },
  { id:'ct-mx-mijares', country:'MX', name:'Pablo Mijares', role:'lawyer',
    org:'Mijares Angoitia Cortés y Fuentes', region:'CDMX', email:'pmijares@macf.com.mx',
    status:'pursuing', lastTouched:'2026-04-22', owner:'Abraham',
    notes:{es:'Counsel para constitución SAPI Sora-México. Cotizó $4.5k todo incluido.', en:'Counsel for Sora-Mexico SAPI incorporation. Quoted $4.5k all-in.'} },
  { id:'ct-mx-aldea-zama', country:'MX', name:'Sofía Camargo', role:'broker',
    org:'Aldea Zama Realty', region:'Tulum', email:'sofia@aldeazama.com', whatsapp:'+52 984 116 5544',
    status:'partnered', lastTouched:'2026-05-10', owner:'Abraham',
    notes:{es:'Broker Tulum lotes selva. Comisión split 50/50 con Sora en referidos.', en:'Tulum jungle-lot broker. 50/50 commission split with Sora on referrals.'} },
  { id:'ct-mx-bitso', country:'MX', name:'Aldo Quiroga', role:'banker',
    org:'Bitso Business', region:'CDMX', email:'business@bitso.com',
    status:'pursuing', lastTouched:'2026-04-30', owner:'Abraham',
    notes:{es:'On-ramp USDC para tesorería Sora-México. Cuenta corporativa en proceso KYC.', en:'USDC on-ramp for Sora-Mexico treasury. Corporate account in KYC process.'} },
  { id:'ct-mx-graciela-angeles', country:'MX', name:'Graciela Ángeles', role:'talent',
    org:'Real Minero', region:'Oaxaca', email:'realminero@gmail.com', whatsapp:'+52 951 506 0098',
    status:'warm', lastTouched:'2026-03-15', owner:'Abdiel',
    notes:{es:'Master mezcalera. Cata privada para grupo Sora en su palenque.', en:'Mezcal master. Private tasting for Sora group at her palenque.'} },

  /* ============================== CO ============================== */
  { id:'ct-co-catalina-perez', country:'CO', name:'Catalina Pérez', role:'hotelier',
    org:'Casa San Agustín', region:'Cartagena', email:'cperez@hotelcasasanagustin.com', whatsapp:'+57 300 819 4480',
    status:'partnered', lastTouched:'2026-05-05', owner:'Abraham',
    notes:{es:'Sales senior. Bloque de 10 hab. Sora confirmado. Comisión 12%.', en:'Senior sales. 10-room Sora block confirmed. 12% commission.'} },
  { id:'ct-co-rob-pevitts', country:'CO', name:'Rob Pevitts', role:'chef',
    org:'Carmen Medellín', region:'Medellín', email:'chef@carmenmedellin.com', instagram:'@robpevitts',
    status:'pursuing', lastTouched:'2026-04-18', owner:'Abdiel',
    notes:{es:'Chef-owner. Acepta mesa privada Sora 12+. Escribe menú custom.', en:'Chef-owner. Accepts private Sora 12+ table. Writes custom menu.'} },
  { id:'ct-co-brigard-urrutia', country:'CO', name:'Daniela Castaño', role:'lawyer',
    org:'Brigard Urrutia', region:'Bogotá', email:'dcastano@bu.com.co',
    status:'pursuing', lastTouched:'2026-04-25', owner:'Abraham',
    notes:{es:'Counsel para SAS Sora-Colombia. Cotizó $1.8k todo incluido + DIAN setup.', en:'Counsel for Sora-Colombia SAS. Quoted $1.8k all-in + DIAN setup.'} },
  { id:'ct-co-compass-medellin', country:'CO', name:'Felipe Restrepo', role:'broker',
    org:'Compass Real Estate Medellín', region:'Medellín', email:'felipe@compass.com.co', whatsapp:'+57 314 720 8800',
    status:'pursuing', lastTouched:'2026-05-08', owner:'Abraham',
    notes:{es:'Broker premium El Poblado/Provenza. Comisión 3-4% split.', en:'Premium El Poblado/Provenza broker. 3-4% split commission.'} },
  { id:'ct-co-pergamino', country:'CO', name:'Pedro Echavarría', role:'talent',
    org:'Pergamino Café', region:'Medellín', email:'pedro@pergamino.co', instagram:'@pergaminocafe',
    status:'partnered', lastTouched:'2026-04-30', owner:'Abdiel',
    notes:{es:'Tostador café especialidad. Cata privada para grupos Sora en finca.', en:'Specialty coffee roaster. Private tasting for Sora groups at finca.'} },
  { id:'ct-co-buda-com', country:'CO', name:'Juan Pablo Henao', role:'banker',
    org:'Buda.com', region:'Bogotá', email:'business@buda.com',
    status:'warm', lastTouched:'2026-03-22', owner:'Abraham',
    notes:{es:'On-ramp USDC/COP para Sora-Colombia. Cuenta business en setup.', en:'USDC/COP on-ramp for Sora-Colombia. Business account in setup.'} },

  /* ============================== BR ============================== */
  { id:'ct-br-wilbert-das', country:'BR', name:'Wilbert Das', role:'hotelier',
    org:'UXUA Casa Hotel', region:'Trancoso', email:'wilbert@uxua.com', instagram:'@uxua',
    status:'pursuing', lastTouched:'2026-04-12', owner:'Abraham',
    notes:{es:'Fundador. Conversación inicial Sora 4-weekend deal Trancoso 2027. Necesita commit anual.', en:'Founder. Initial talks for Sora 4-weekend Trancoso 2027 deal. Needs annual commitment.'} },
  { id:'ct-br-alberto-landgraf', country:'BR', name:'Alberto Landgraf', role:'chef',
    org:'Oteque', region:'Rio de Janeiro', email:'reservas@oteque.com', instagram:'@albertolandgraf',
    status:'pursuing', lastTouched:'2026-03-28', owner:'Abraham',
    notes:{es:'Chef 2 estrellas. Mesa de 8 max — formato chef\'s table.', en:'2-star chef. 8-top max — chef\'s-table format.'} },
  { id:'ct-br-mattos-filho', country:'BR', name:'Renata Pinheiro', role:'lawyer',
    org:'Mattos Filho', region:'São Paulo', email:'rpinheiro@mattosfilho.com.br',
    status:'pursuing', lastTouched:'2026-05-02', owner:'Abraham',
    notes:{es:'Counsel para Ltda Sora-Brasil. Cripto + tax expertise.', en:'Counsel for Sora-Brazil Ltda. Crypto + tax expertise.'} },
  { id:'ct-br-mercado-bitcoin', country:'BR', name:'Beatriz Souza', role:'banker',
    org:'Mercado Bitcoin', region:'São Paulo', email:'business@mercadobitcoin.com.br',
    status:'warm', lastTouched:'2026-04-10', owner:'Abraham',
    notes:{es:'On-ramp BRL/USDC. Cuenta corporativa abierta en 3 semanas.', en:'BRL/USDC on-ramp. Corporate account opened in 3 weeks.'} },
  { id:'ct-br-bossa-nova-sothebys', country:'BR', name:'Marina Vasquez', role:'broker',
    org:'Bossa Nova Sotheby\'s', region:'Trancoso / Rio', email:'marina@bossanovasir.com',
    status:'target', lastTouched:'2026-04-05', owner:'Abraham',
    notes:{es:'Broker para Trancoso casas $1M+. Comisión 5-6% split.', en:'Broker for Trancoso $1M+ houses. 5-6% split commission.'} },

  /* ============================== AR ============================== */
  { id:'ct-ar-pablo-rivero', country:'AR', name:'Pablo Rivero', role:'chef',
    org:'Don Julio Parrilla', region:'Buenos Aires', email:'reservas@parrilladonjulio.com', whatsapp:'+54 9 11 4831 9564',
    status:'partnered', lastTouched:'2026-05-15', owner:'Abraham',
    notes:{es:'Chef-owner #1 mundo 50 Best. Mesa 14 bloqueada 4 fechas/año Sora.', en:'Chef-owner #1 world 50 Best. 14-top blocked 4 Sora dates/year.'} },
  { id:'ct-ar-francis-mallmann', country:'AR', name:'Francis Mallmann', role:'chef',
    org:'Siete Fuegos (The Vines) / Garzón', region:'Mendoza / UY', email:'francis@mallmann.com', instagram:'@francismallmann',
    status:'warm', lastTouched:'2026-02-28', owner:'Abraham',
    notes:{es:'Cubre Mendoza + Uruguay. Acepta Sora con block-booking serio. Manager Ana Sallaberry.', en:'Covers Mendoza + Uruguay. Accepts Sora with serious block-booking. Manager Ana Sallaberry.'} },
  { id:'ct-ar-marval-ofarrell', country:'AR', name:'Sebastián Ferrero', role:'lawyer',
    org:'Marval O\'Farrell Mairal', region:'Buenos Aires', email:'sferrero@marval.com',
    status:'pursuing', lastTouched:'2026-04-18', owner:'Abraham',
    notes:{es:'Counsel para SA Sora-Argentina + asesoría cambiaria AFIP.', en:'Counsel for Sora-Argentina SA + AFIP currency advisory.'} },
  { id:'ct-ar-lemon-cash', country:'AR', name:'Marcelo Cavazzoli', role:'banker',
    org:'Lemon Cash', region:'Buenos Aires', email:'business@lemon.me',
    status:'warm', lastTouched:'2026-03-30', owner:'Abraham',
    notes:{es:'On-ramp USDC. Carril principal cripto para Argentina.', en:'USDC on-ramp. Main crypto rail for Argentina.'} },
  { id:'ct-ar-catena-zapata', country:'AR', name:'Laura Catena', role:'talent',
    org:'Bodega Catena Zapata', region:'Mendoza', email:'catas@catenawines.com',
    status:'target', lastTouched:'2026-04-22', owner:'Abdiel',
    notes:{es:'Cata privada vertical Malbec en pirámide icónica. Coordinar 90 días antes.', en:'Private vertical Malbec tasting at iconic pyramid. Coordinate 90 days ahead.'} },

  /* ============================== CR ============================== */
  { id:'ct-cr-helena-lara', country:'CR', name:'Helena Lara', role:'hotelier',
    org:'Bodhi Tree Yoga Resort', region:'Nosara', email:'helena@bodhitreeyogaresort.com', whatsapp:'+506 8334 2200',
    status:'partnered', lastTouched:'2026-05-12', owner:'Abraham',
    notes:{es:'Group sales. Bloque Sora 12+ confirmado con 15% off. Yoga schedule full incluido.', en:'Group sales. Sora 12+ block confirmed at 15% off. Full yoga schedule included.'} },
  { id:'ct-cr-blp-legal', country:'CR', name:'Andrés Sánchez', role:'lawyer',
    org:'BLP Legal', region:'San José', email:'asanchez@blplegal.com',
    status:'pursuing', lastTouched:'2026-04-15', owner:'Abraham',
    notes:{es:'Counsel para SA Sora-CR. Cotizó $1.8k todo incluido + 3 semanas.', en:'Counsel for Sora-CR SA. Quoted $1.8k all-in + 3 weeks.'} },
  { id:'ct-cr-2costa-rica', country:'CR', name:'Pamela Rojas', role:'broker',
    org:'2Costa Rica Real Estate', region:'Nosara', email:'pamela@2costarica.com', whatsapp:'+506 8888 1234',
    status:'pursuing', lastTouched:'2026-04-30', owner:'Abraham',
    notes:{es:'Broker Nosara. Comisión 5-6% split. Speaks English perfectly.', en:'Nosara broker. 5-6% split commission. English-fluent.'} },
  { id:'ct-cr-cayuga-collection', country:'CR', name:'Hans Pfister', role:'hotelier',
    org:'Cayuga Collection (Lapa Rios)', region:'Osa', email:'hans@cayugacollection.com',
    status:'target', lastTouched:'2026-04-20', owner:'Abdiel',
    notes:{es:'Operator de varios eco-lodges premium. Sora puede alquilar lodge entero ciertas fechas.', en:'Operator of several premium eco-lodges. Sora can rent the whole lodge on select dates.'} },

  /* ============================== PE ============================== */
  { id:'ct-pe-beto-cinader', country:'PE', name:'Beto Cinader', role:'hotelier',
    org:'Hotel B', region:'Lima', email:'beto@hotelb.pe', whatsapp:'+51 999 555 444',
    status:'partnered', lastTouched:'2026-05-08', owner:'Abraham',
    notes:{es:'GM hotel B. Bloque Sora confirmado Barranco. Tour arte privado incluido.', en:'GM Hotel B. Sora block confirmed Barranco. Private art tour included.'} },
  { id:'ct-pe-pia-leon', country:'PE', name:'Pia León', role:'chef',
    org:'Central / Kjolle', region:'Lima', email:'reservas@centralrestaurante.com.pe',
    status:'pursuing', lastTouched:'2026-03-18', owner:'Abdiel',
    notes:{es:'Co-chef Central. Reserva con 60 días. Línea directa Sora establecida.', en:'Co-chef Central. Book 60 days ahead. Direct Sora line established.'} },
  { id:'ct-pe-echecopar', country:'PE', name:'Luis Vinatea', role:'lawyer',
    org:'Estudio Echecopar (Baker McKenzie)', region:'Lima', email:'luis.vinatea@bakermckenzie.com',
    status:'target', lastTouched:'2026-04-08', owner:'Abraham',
    notes:{es:'Counsel para SAC Sora-Perú. Permisos MP en su scope.', en:'Counsel for Sora-Peru SAC. MP permits within scope.'} },
  { id:'ct-pe-rainforest-exp', country:'PE', name:'Kurt Holle', role:'talent',
    org:'Rainforest Expeditions', region:'Tambopata', email:'kurt@rainforest.com.pe',
    status:'target', lastTouched:'2026-04-12', owner:'Abdiel',
    notes:{es:'Operador Tambopata Research Center. Coordinar weekend Amazonia exclusivo.', en:'Tambopata Research Center operator. Coordinate exclusive Amazon weekend.'} },

  /* ============================== CL ============================== */
  { id:'ct-cl-rodolfo-guzman', country:'CL', name:'Rodolfo Guzmán', role:'chef',
    org:'Boragó', region:'Santiago', email:'reservas@borago.cl', instagram:'@rodolfoguzman',
    status:'pursuing', lastTouched:'2026-04-22', owner:'Abdiel',
    notes:{es:'Chef-owner top 30 mundo. Mesa chef 12. Endémicos chilenos.', en:'Chef-owner world top 30. 12-chef-table. Chilean endemics.'} },
  { id:'ct-cl-tierra-hotels', country:'CL', name:'Joaquín Vial', role:'hotelier',
    org:'Tierra Hotels group', region:'San Pedro / Patagonia', email:'jvial@tierrahotels.com',
    status:'pursuing', lastTouched:'2026-04-30', owner:'Abraham',
    notes:{es:'Cubre Tierra Atacama + Tierra Patagonia + Tierra Chiloé. Block-booking 12+ con 12% off.', en:'Covers Tierra Atacama + Patagonia + Chiloé. 12+ block-booking with 12% off.'} },
  { id:'ct-cl-carey', country:'CL', name:'María Paz Hidalgo', role:'lawyer',
    org:'Carey y Cía.', region:'Santiago', email:'mphidalgo@carey.cl',
    status:'target', lastTouched:'2026-04-15', owner:'Abraham',
    notes:{es:'Counsel para SpA Sora-Chile. Setup en 2-3 semanas.', en:'Counsel for Sora-Chile SpA. 2-3 week setup.'} },

  /* ============================== UY ============================== */
  { id:'ct-uy-carrie-vik', country:'UY', name:'Carrie Vik', role:'hotelier',
    org:'Vik Retreats (Bahía + Playa)', region:'José Ignacio', email:'carrie@vikretreats.com',
    status:'partnered', lastTouched:'2026-05-10', owner:'Abraham',
    notes:{es:'Fundadora. Anchor Sora-UY confirmado. Acceso a 3 Vik properties.', en:'Founder. Sora-UY anchor confirmed. Access to 3 Vik properties.'} },
  { id:'ct-uy-martin-pittaluga', country:'UY', name:'Martín Pittaluga', role:'chef',
    org:'Parador La Huella', region:'José Ignacio', email:'martin@paradorlahuella.com',
    status:'partnered', lastTouched:'2026-05-12', owner:'Abraham',
    notes:{es:'Co-owner. Mesa 16 garantizada Sora Dic-Feb. Línea directa.', en:'Co-owner. Guaranteed 16-top Sora Dec-Feb. Direct line.'} },
  { id:'ct-uy-ferrere', country:'UY', name:'Pablo Mariño', role:'lawyer',
    org:'Ferrere', region:'Montevideo', email:'pmarino@ferrere.com',
    status:'pursuing', lastTouched:'2026-04-18', owner:'Abraham',
    notes:{es:'Counsel para SA Sora-Uruguay. Régimen residencia fiscal en scope.', en:'Counsel for Sora-Uruguay SA. Fiscal residency regime in scope.'} },

  /* ============================== PA ============================== */
  { id:'ct-pa-tuti-aguilera', country:'PA', name:'Tuti Aguilera', role:'hotelier',
    org:'Finca Lerida', region:'Boquete', email:'tuti@fincalerida.com', whatsapp:'+507 6677 8899',
    status:'partnered', lastTouched:'2026-05-20', owner:'Abraham',
    notes:{es:'GM Finca Lerida. Origin partner Sora. Geisha cata privada incluida.', en:'GM Finca Lerida. Sora origin partner. Private Geisha tasting included.'} },
  { id:'ct-pa-chef-hassan', country:'PA', name:'Chef Hassan', role:'chef',
    org:'Casa Hassan', region:'Boquete', email:'chef@casahassan.com', whatsapp:'+507 6555 1234',
    status:'partnered', lastTouched:'2026-05-22', owner:'Abraham',
    notes:{es:'Partner directo La Compañía. Mesa privada para weekends Boquete.', en:'Direct La Compañía partner. Private table for Boquete weekends.'} },
  { id:'ct-pa-bambi-roots', country:'PA', name:'Bambi Roots', role:'musician',
    org:'Bambi Roots band', region:'Panamá', whatsapp:'+507 6300 5500', instagram:'@bambirootsmusic',
    status:'partnered', lastTouched:'2026-05-15', owner:'Abdiel',
    notes:{es:'Set acústico para Mirador Barú weekend. Tarifa Sora amiga.', en:'Acoustic set for Mirador Barú weekend. Friend rate for Sora.'} },
  { id:'ct-pa-camila-vega', country:'PA', name:'Camila Vega', role:'talent',
    org:'Sommelier independiente', region:'Casco Viejo', whatsapp:'+507 6700 4400', instagram:'@camilasomm',
    status:'partnered', lastTouched:'2026-05-08', owner:'Abdiel',
    notes:{es:'Sommelier Sora oficial. Maridajes para cenas privadas Casco + Boquete.', en:'Official Sora sommelier. Pairings for Casco + Boquete private dinners.'} },
  { id:'ct-pa-aff', country:'PA', name:'Jorge Lee', role:'lawyer',
    org:'Arias, Fábrega & Fábrega', region:'Panamá City', email:'jlee@arifa.com',
    status:'partnered', lastTouched:'2026-05-01', owner:'Abraham',
    notes:{es:'Counsel La Compañía + Sora-PA. Estructura ya en pie.', en:'La Compañía + Sora-PA counsel. Structure already in place.'} },
  { id:'ct-pa-towerbank', country:'PA', name:'Carlos Tovar', role:'banker',
    org:'Towerbank', region:'Panamá City', email:'ctovar@towerbank.com',
    status:'partnered', lastTouched:'2026-04-25', owner:'Abraham',
    notes:{es:'Banker corporativo. On/off-ramp USDC para tesorería La Compañía.', en:'Corporate banker. USDC on/off-ramp for La Compañía treasury.'} },
  { id:'ct-pa-casa-solution', country:'PA', name:'Mike Hernández', role:'broker',
    org:'Casa Solution', region:'Boquete', email:'mike@casasolution.com', whatsapp:'+507 6677 1100',
    status:'partnered', lastTouched:'2026-05-04', owner:'Abraham',
    notes:{es:'Broker Boquete. Comisión 50/50 referidos Sora. Veterano del mercado.', en:'Boquete broker. 50/50 commission on Sora referrals. Market veteran.'} },

  /* ============================== VE ============================== */
  { id:'ct-ve-carlos-garcia', country:'VE', name:'Carlos García', role:'chef',
    org:'Alto Restaurant', region:'Caracas', email:'reservas@altorestaurant.com', instagram:'@altovenezuela',
    status:'pursuing', lastTouched:'2026-04-08', owner:'Abraham',
    notes:{es:'Chef-owner. Top de Venezuela. Mesa 14 Sora confirmada.', en:'Chef-owner. Top of Venezuela. Sora 14-top confirmed.'} },
  { id:'ct-ve-mercedes-oropeza', country:'VE', name:'Mercedes Oropeza', role:'chef',
    org:'Amapola', region:'Caracas', whatsapp:'+58 412 555 8800',
    status:'warm', lastTouched:'2026-03-25', owner:'Abdiel',
    notes:{es:'Chef de mercado. Tour Mercado Chacao para grupos Sora con cocina al final.', en:'Market chef. Mercado Chacao tour for Sora groups with cooking at the end.'} },
  { id:'ct-ve-dempaire', country:'VE', name:'Carlos Domínguez', role:'lawyer',
    org:'D\'Empaire', region:'Caracas', email:'cdominguez@dempaire.com',
    status:'pursuing', lastTouched:'2026-04-18', owner:'Abraham',
    notes:{es:'Counsel Tier-1 con expertise sanciones. Crítico para OFAC compliance.', en:'Tier-1 counsel with sanctions expertise. Critical for OFAC compliance.'} },
  { id:'ct-ve-binance-p2p', country:'VE', name:'Carolina Mendoza', role:'banker',
    org:'Binance Venezuela', region:'Caracas', email:'carolina@binance.com',
    status:'warm', lastTouched:'2026-03-30', owner:'Abraham',
    notes:{es:'Soporte P2P Venezuela. Carril cripto principal para retail VE.', en:'Venezuela P2P support. Main crypto rail for VE retail.'} },

  /* ============================== Cross-chapter / global ============================== */
  { id:'ct-global-belmond-latam', country:'BR/PE', name:'Sofía Marín', role:'hotelier',
    org:'Belmond LATAM Sales', region:'São Paulo HQ', email:'smarin@belmond.com',
    status:'pursuing', lastTouched:'2026-04-22', owner:'Abraham',
    notes:{es:'Cubre Belmond Río Sagrado, Sanctuary MP, Copacabana Palace, Hiram Bingham. Master deal en discusión.', en:'Covers Belmond Río Sagrado, Sanctuary MP, Copacabana Palace, Hiram Bingham. Master deal in discussion.'} },
  { id:'ct-global-aman-resorts', country:'DO', name:'Aman Group Sales', role:'hotelier',
    org:'Aman Resorts', region:'Global HQ', email:'sales@aman.com',
    status:'cold', lastTouched:'2026-02-15', owner:'Abraham',
    notes:{es:'Acceso para Amanera (DO) + futuro Aman LATAM. Necesita commit serio.', en:'Access for Amanera (DO) + future Aman LATAM. Needs serious commitment.'} },
  { id:'ct-global-tierra-collection', country:'CL', name:'Joaquín Vial', role:'hotelier',
    org:'Tierra Hotels group', region:'Santiago HQ', email:'jvial@tierrahotels.com',
    status:'pursuing', lastTouched:'2026-04-30', owner:'Abraham',
    notes:{es:'Multi-property deal Tierra (Atacama + Patagonia + Chiloé). Bloque 12+ con 12% off.', en:'Multi-property Tierra deal (Atacama + Patagonia + Chiloé). 12+ block with 12% off.'} }
];
